### ISSUE TITLE
Requested amount issue

### ISSUE THREAD

**Issue by surveshoeb** [razorpay/razorpay-flutter#100]
## Description
The amount added in the options map is always actualAmount/100. I also tried to send the decimal value example 1000.00 still it shows 1 on the payment page.

### Flutter Version :
```
Flutter beta 1.20.2
```

### Device use for testing :
```
Nexus_5_API_30  • Nexus 5 API 30  • Google • android • Emulator
```

### Options Map Value
```
options = {
      'key': '****test_key****',
      'amount':1000,
      'name': 'Company Pvt Ltd',
      'currency': 'INR',
      'payment_capture': 1,
      'order_id': requestId,
      'description': requestType,
      'prefill': {
        'contact': locator<AuthenticationService>().userData.number,
        'email': locator<AuthenticationService>().userData.email,
      }
    }
```

### Expected Results
Amount on payment page should be 1000 INR

**Comment by ambujap94** [comment]
@surveshoeb Razorpay accepts the amount in integer and in the basic unit that is paise. If you will pass the amount=1000, it will be equivalent to 10 INR.
 If you want to pass 23.56 INR then please amount=2356 in the checkout options.
Please refer [here](https://razorpay.com/docs/payment-gateway/web-integration/standard/checkout-options/) for further details

please let us know if you need further clarification.
