### ISSUE TITLE
Closing the checkout window multiple times freezes the app (without proceeding to pay).

### ISSUE THREAD

**Issue by himanshusharma89** [razorpay/razorpay-flutter#101]
## Description
Application freezes/hangs if we close the checkout window multiple times without proceeding to pay. And the app gets stuck at a grey screen.

This issue might be similar to #21, but the steps are different and maybe log's too.

**Log:**
```
[INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.5.16&library=checkoutjs&platform=android (1)
```

## Razorpay Version :
1.2.1

## Flutter Version :
Flutter (Channel beta, 1.21.0-9.1.pre, on Microsoft Windows [Version 10.0.19041.450], locale en-IN

## Steps To Reproduce
1. Open the checkout window.
2. Close the checkout window without proceeding to pay.
3. Repeat steps 1 & 2.

## Expected Results
The app is expected to continue working supposedly even if we close the checkout window repeatedly.

## Snack, code example, screenshot, or link to a repository:
You can try the code mentioned in the repository. Nothing is wrong in the code.

**Comment by Nautiyalsachin** [comment]
Hey @himanshusharma89, try updating the plugin to the latest version or you can delete the plugin and re-install, which will help you to get the latest frameworks, let me know if that helps to solve this issue.

**Comment by Nautiyalsachin** [comment]
@himanshusharma89, closing this issue now because of no response, let me know if the issue still persists, you can always re-open the issue or comment on the same. Thanks!
