### ISSUE TITLE
Unknown attribute '_hasMissingDesignatedInitializers'

### ISSUE THREAD

**Issue by ravipromact2306** [razorpay/razorpay-flutter#102]
Not able to Run project after implementing razorpay_flutter.

## Description
Receiving below errors,
![Screenshot 2020-09-01 at 11 51 37 AM](https://user-images.githubusercontent.com/60922861/91806285-8ec0f700-ec49-11ea-8a89-38e66bf485a8.png)

![Screenshot 2020-09-01 at 11 26 35 AM](https://user-images.githubusercontent.com/60922861/91800256-4b18be00-ec46-11ea-8d08-b76d32e25b15.png)

## Flutter Version :
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (3 weeks ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

## Xcode Version :
Version 11.2 (11B52)

## Cocoapod Version :
Installing razorpay-pod (1.1.7)
Installing razorpay_flutter (1.1.5)

## Steps To Reproduce
Just install razorpay_flutter in your flutter project, do configuration as asked in the installation guide. I have tried all the things but not able to find any solution.
Here are my Podfile changes I have done,
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
    	config.build_settings['ENABLE_BITCODE'] = 'YES'
    	config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end`

## Expected Results
The project should run without errors.

Any help would be appreciated! Thanks.

**Comment by sajithstorybox** [comment]
Same here any solutions?

**Comment by ravipromact2306** [comment]
I have updated it to the latest Xcode version 11.7 and it runs successfully. Which version of Xcode you are using?

**Comment by ravipromact2306** [comment]
> Same here any solutions?

I have updated it to the latest Xcode version 11.7 and it runs successfully. Which version of Xcode you are using?

**Comment by Nautiyalsachin** [comment]
Hey @sajithstorybox, Please try to update your Xcode and also your razorpay-pod to the latest, I hope you have already solved this issue, if not then please feel free to add a comment/re-open this issue.
