### ISSUE TITLE
Module compiled with Swift 5.2.4 cannot be imported by the swift 5.1.3 compiler

### ISSUE THREAD

**Issue by deepakatom** [razorpay/razorpay-flutter#106]
Module compiled with Swift 5.2.4 cannot be imported by the swift 5.1.3 compiler

## Razorpay Version : 1.2.2

##Cocopod version: 1.10.0

![Capture](https://user-images.githubusercontent.com/71891121/94284840-92a61780-ff70-11ea-98d9-4be7e409c757.PNG)

**Comment by Nautiyalsachin** [comment]
Hi @deepakatom, can you share the Razorpay pod details here? Which razorpay-pod version are you using right now? you can find that in your podfile.lock file.

**Comment by sumedht** [comment]
@deepakatom Closing this issue as there is no further update. U can reopen it facing some issue
