### ISSUE TITLE
Pay Later Option 

### ISSUE THREAD

**Issue by hiteshgarg002** [razorpay/razorpay-flutter#108]
Hi, I tried disabling Pay Later option but it seems its not working, please fix this.

I tried the following way but its not working
 "method": {
     "paylater": false,
  },

**Comment by Prajwal625** [comment]
Hi Hitesh,
Pay later option does not work with the method parameter, could you please raise a ticket on our dashboard for better assistance on the use case.

**Comment by hiteshgarg002** [comment]
Hi @Prajwal625 
Can you tell me how can I hide Pay later option?

**Comment by Nautiyalsachin** [comment]
Hey @hiteshgarg002, you can hide Pay Later option from your Razorpay's dashboard, or by syncing up with our support team. Let me know if you still facing this issue. Thank you.

**Comment by anjalijagtapbacancy** [comment]
> Hey @hiteshgarg002, you can hide Pay Later option from your Razorpay's dashboard, or by syncing up with our support team. Let me know if you still facing this issue. Thank you.

How to do this steps?
