### ISSUE TITLE
Feature request : enable for flutter web

### ISSUE THREAD

**Issue by paras-28** [razorpay/razorpay-flutter#110]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay Flutter plugin release to make sure your issue has not already been fixed: 

## Flutter Version :
Run `flutter version` in your terminal and copy the results here.

## Xcode Version :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.

## Cocoapod Version :
Go to iOS folder > open `podfile.lock` > copy the `razorpay-pod version` and `razorpay_flutter`a version.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by AYAN249** [comment]
Thanks for the effort could you please raise a pull request to the repository post which we will merge it accordingly from our end.

**Comment by h4rdw1r3** [comment]
wrap the existing razorpay web sdk for easy payment integration for the flutter web apps

**Comment by GauravCalidig** [comment]
https://pub.dev/packages/razorpay_web You Can use this till the official one starts supporting
