### ISSUE TITLE
Could you please upgraded the version checkout to 1.6.4. In this package it is still 1.5.x. I am having issues because of this. and  google is about to remove my app from playstore

### ISSUE THREAD

**Issue by faisalmushtaq007** [razorpay/razorpay-flutter#112]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay Flutter plugin release to make sure your issue has not already been fixed: 

## Flutter Version :
Run `flutter version` in your terminal and copy the results here.

## Xcode Version :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.

## Cocoapod Version :
Go to iOS folder > open `podfile.lock` > copy the `razorpay-pod version` and `razorpay_flutter`a version.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by sumedht** [comment]
@faisalmushtaq007 Apologies for inconviniance. We will update version till tomorrow

**Comment by faisalmushtaq007** [comment]
@sumedht Thankyou so much, i was so stressed due to this issue. I just had this week and after that  googleplaystore would remove my app. Once again thanks and please do inform me here.

**Comment by faisalmushtaq007** [comment]
@sumedht Could you please confirm until what time you'll update this package

**Comment by faisalmushtaq007** [comment]
Still nothing??? @sumedht

**Comment by faisalmushtaq007** [comment]
@sumedht When will you update the changes, because the package is still with version 1.2.2.

**Comment by faisalmushtaq007** [comment]
@sumedht  i am still waiting for the update!!!

**Comment by faisalmushtaq007** [comment]
with the new update, the intent redirection issue has been solved.
Cheers!

**Comment by vivekshindhe** [comment]
@faisalmushtaq007. Could you please send a screenshot or the text with Google's reply? It will contain the part where this Intent Redirection issue will be there. it would help us greatly in solving this faster.
