### ISSUE TITLE
Google is still showing intent redirection.

### ISSUE THREAD

**Issue by faisalmushtaq007** [razorpay/razorpay-flutter#117]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay Flutter plugin release to make sure your issue has not already been fixed: 

## Flutter Version :
Run `flutter version` in your terminal and copy the results here.

## Xcode Version :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.

## Cocoapod Version :
Go to iOS folder > open `podfile.lock` > copy the `razorpay-pod version` and `razorpay_flutter`a version.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by vivekshindhe** [comment]
@faisalmushtaq007 Could you please send a screenshot or the complete text of Google's reply for this? It will contain information about the class where the Intent Redirection issue exists. This will help us solve this issue for you faster.

**Comment by faisalmushtaq007** [comment]
@vivekshindhe Please check this
![Screenshot (12)](https://user-images.githubusercontent.com/24683159/102744474-e82b6e00-437f-11eb-9441-01c9b009130a.png)

**Comment by Nautiyalsachin** [comment]
Hey @faisalmushtaq007, we are working on a new release for fixing this issue, we will be releasing an update soon. Thank you.

**Comment by vivekshindhe** [comment]
Hey @faisalmushtaq007, continuing from our email thread, could you please confirm if everything was working fine now? We'd like to close this ticket if everything was fine.

**Comment by Nautiyalsachin** [comment]
Closing this issue due to no response from @faisalmushtaq007, feel free to re-open or add more comments.
