### ISSUE TITLE
Failed to load module 'Razorpay

### ISSUE THREAD

**Issue by RNSuthar** [razorpay/razorpay-flutter#120]
Running pod install...
Running Xcode build...
Xcode build done.                                           22.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Command CompileSwift failed with a nonzero exit code
    /Users/dotsquares/Documents/Projects/Flutter/2020/HighTournaments/hightournaments/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:44:1: error: unknown attribute '_hasMissingDesignatedInitializers'
    @_hasMissingDesignatedInitializers @objc public class PluginPaymentModel : ObjectiveC.NSObject {
    ^
    /Users/dotsquares/Documents/Projects/Flutter/2020/HighTournaments/hightournaments/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:51:41: error: unknown attribute '_hasMissingDesignatedInitializers'
    @objc @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers public class Otpelf : ObjectiveC.NSObject {
                                            ^
    /Users/dotsquares/Documents/Projects/Flutter/2020/HighTournaments/hightournaments/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:51:7: error: unknown attribute '_inheritsConvenienceInitializers'
    @objc @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers public class Otpelf : ObjectiveC.NSObject {
          ^
    /Users/dotsquares/Documents/Projects/Flutter/2020/HighTournaments/hightournaments/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:59:35: error: unknown attribute '_hasMissingDesignatedInitializers'
    @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @objc final public class RazorpayCheckout : ObjectiveC.NSObject {
                                      ^
    /Users/dotsquares/Documents/Projects/Flutter/2020/HighTournaments/hightournaments/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:59:1: error: unknown attribute '_inheritsConvenienceInitializers'
    @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @objc final public class RazorpayCheckout : ObjectiveC.NSObject {
    ^
    /Users/dotsquares/Documents/soft/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.3/ios/Classes/RazorpayDelegate.swift:2:8: error: failed to load module 'Razorpay'
    import Razorpay
           ^
    /Users/dotsquares/Documents/Projects/Flutter/2020/HighTournaments/hightournaments/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:44:1: error: unknown attribute '_hasMissingDesignatedInitializers'
    @_hasMissingDesignatedInitializers @objc public class PluginPaymentModel : ObjectiveC.NSObject {
    ^
    /Users/dotsquares/Documents/Projects/Flutter/2020/HighTournaments/hightournaments/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:51:41: error: unknown attribute '_hasMissingDesignatedInitializers'
    @objc @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers public class Otpelf : ObjectiveC.NSObject {
                                            ^
    /Users/dotsquares/Documents/Projects/Flutter/2020/HighTournaments/hightournaments/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:51:7: error: unknown attribute '_inheritsConvenienceInitializers'
    @objc @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers public class Otpelf : ObjectiveC.NSObject {
          ^
    /Users/dotsquares/Documents/Projects/Flutter/2020/HighTournaments/hightournaments/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:59:35: error: unknown attribute '_hasMissingDesignatedInitializers'
    @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @objc final public class RazorpayCheckout : ObjectiveC.NSObject {
                                      ^
    /Users/dotsquares/Documents/Projects/Flutter/2020/HighTournaments/hightournaments/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:59:1: error: unknown attribute '_inheritsConvenienceInitializers'
    @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @objc final public class RazorpayCheckout : ObjectiveC.NSObject {
    ^
    /Users/dotsquares/Documents/soft/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.3/ios/Classes/RazorpayDelegate.swift:2:8: error: failed to load module 'Razorpay'
    import Razorpay
           ^
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 8.

when using Xcode 11.3
& try with flutter version
-razorpay_flutter: ^1.1.0
-razorpay_flutter: ^1.1.1
-razorpay_flutter: ^1.1.2

**Comment by Nautiyalsachin** [comment]
Hi @RNSuthar, please try updating razorpay-pod to the latest version, you can check the current version in podfile.lock

This [issue](https://github.com/razorpay/razorpay-flutter/issues/107) is repeated, please refer the existing issues before raising any new issue.

**Comment by hardikvij195** [comment]
@Nautiyalsachin it's not working on latest flutter version on iOS simulator
