### ISSUE TITLE
 Webview JS Error: Uncaught ReferenceError: otpPermissionCallback is not defined /// and Uncaught TypeError: window.getDeviceDetails is not a function

### ISSUE THREAD

**Issue by muqaddir** [razorpay/razorpay-flutter#124]
The open checkout page not working . Instead it's showing two errors. One is **otpPermissionCallback is not defined** .Other one is **Uncaught TypeError: window.getDeviceDetails is not a function** .

I'm using 
-**Flutter 1.25.0-8.2.pre**
**razorpay_flutter: ^1.2.3**

dependencies 
**implementation('com.razorpay:checkout:1.6.3')**

I've attached two screenshots of these errors .

![razorerror 1](https://user-images.githubusercontent.com/36444566/104163121-e05d6780-541b-11eb-9234-6646fd2a98d3.png)
![razorpay](https://user-images.githubusercontent.com/36444566/104163130-e5221b80-541b-11eb-86cf-eea90b4777a2.png)

**Comment by sriki77** [comment]
How was this fixed? We are facing the same issue. Please advise.

**Comment by faisalmushtaq007** [comment]
Any luck with this issue??? @sriki77 @muqaddir

**Comment by tehsunnliu** [comment]
I'm getting the same error after payment. 

`E/com.razorpay.checkout(26274): Webview JS Error: Uncaught TypeError: window.getDeviceDetails is not a function`
`I/chromium(26274): [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/payments/pay_GiuBNzmX1smpN6/callback/ab19a9fb5ddb537ab319ecdbd2cf4160ef1e5b3a/rzp_test_n9zLAtqjtf0njn?status=authorized&token_recurring_status=rejected&language_code=en (1)`

`E/com.razorpay.checkout(26274): Webview JS Error: Uncaught ReferenceError: otpPermissionCallback is not defined`

**Comment by holy-dev** [comment]
`log
E/com.razorpay.checkout(31678): Webview JS Error: Uncaught ReferenceError: otpPermissionCallback is not defined
I/chromium(31678): [INFO:CONSOLE(1)] "Uncaught ReferenceError: otpPermissionCallback is not defined", source: https://api.razorpay.com/v1/payments/pay_HQnWAAu19B3Irz/callback/c6718de18eeef2b2ccf25468319ad25b55f37d2d/rzp_test_CDyCI4M4HfeteX?status=authorized&token_recurring_status=rejected&language_code=en (1)
E/ActivityThread(31678): Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@fe62c0 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(31678): android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@fe62c0 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(31678): 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1724)
E/ActivityThread(31678): 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1462)
E/ActivityThread(31678): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1684)
E/ActivityThread(31678): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1650)
E/ActivityThread(31678): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1638)
E/ActivityThread(31678): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:686)
E/ActivityThread(31678): 	at com.razorpay.CheckoutPresenterImpl.onSubmit(CheckoutPresenterImpl.java:922)
E/ActivityThread(31678): 	at com.razorpay.CheckoutBridge$10.secure(CheckoutBridge.java:157)
E/ActivityThread(31678): 	at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1221)
E/ActivityThread(31678): 	at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:49)
E/ActivityThread(31678): 	at com.razorpay.CheckoutPresenterImpl$17.run(CheckoutPresenterImpl.java:1207)
E/ActivityThread(31678): 	at android.os.Handler.handleCallback(Handler.java:938)
E/ActivityThread(31678): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/ActivityThread(31678): 	at android.os.Looper.loop(Looper.java:246)
E/ActivityThread(31678): 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/ActivityThread(31678): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(31678): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/ActivityThread(31678): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
E/ActivityThread(31678): Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@c4d0df2 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(31678): android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@c4d0df2 that was originally registered here. Are you missing a call to unregisterReceiver()?
`

**Comment by flutterdevelop** [comment]
what was the fix for this ?
