### ISSUE TITLE
razorpay pay not working for ios 

### ISSUE THREAD

**Issue by rohitsainik** [razorpay/razorpay-flutter#125]
### I Was Trying to build my app in ios but was unable to do it as I was getting these errors every time I try to build my app. I was able to build it for android but was getting these errors for ios. if I remove razorpay plugin everything works properly.

> Error output from Xcode build:
↳
* BUILD FAILED *

Xcode's output:
↳
/Users/ganpat/Desktop/Flutter_Apps_Projects_2021/wsflutter/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:44:1: error: unknown attribute '_hasMissingDesignatedInitializers'
@_hasMissingDesignatedInitializers @objc public class PluginPaymentModel : ObjectiveC.NSObject {
^
/Users/ganpat/Desktop/Flutter_Apps_Projects_2021/wsflutter/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:51:41: error: unknown attribute '_hasMissingDesignatedInitializers'
@objc @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers public class Otpelf : ObjectiveC.NSObject {
^
/Users/ganpat/Desktop/Flutter_Apps_Projects_2021/wsflutter/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:51:7: error: unknown attribute '_inheritsConvenienceInitializers'
@objc @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers public class Otpelf : ObjectiveC.NSObject {
^
/Users/ganpat/Desktop/Flutter_Apps_Projects_2021/wsflutter/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:59:35: error: unknown attribute '_hasMissingDesignatedInitializers'
@_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @objc final public class RazorpayCheckout : ObjectiveC.NSObject {
^
/Users/ganpat/Desktop/Flutter_Apps_Projects_2021/wsflutter/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:59:1: error: unknown attribute '_inheritsConvenienceInitializers'
@_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @objc final public class RazorpayCheckout : ObjectiveC.NSObject {
^
/Users/ganpat/develop/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.2/ios/Classes/RazorpayDelegate.swift:2:8: error: failed to load module 'Razorpay'
import Razorpay
^
/Users/ganpat/Desktop/Flutter_Apps_Projects_2021/wsflutter/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:44:1: error: unknown attribute '_hasMissingDesignatedInitializers'
@_hasMissingDesignatedInitializers @objc public class PluginPaymentModel : ObjectiveC.NSObject {
^
/Users/ganpat/Desktop/Flutter_Apps_Projects_2021/wsflutter/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:51:41: error: unknown attribute '_hasMissingDesignatedInitializers'
@objc @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers public class Otpelf : ObjectiveC.NSObject {
^
/Users/ganpat/Desktop/Flutter_Apps_Projects_2021/wsflutter/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:51:7: error: unknown attribute '_inheritsConvenienceInitializers'
@objc @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers public class Otpelf : ObjectiveC.NSObject {
^
/Users/ganpat/Desktop/Flutter_Apps_Projects_2021/wsflutter/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:59:35: error: unknown attribute '_hasMissingDesignatedInitializers'
@_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @objc final public class RazorpayCheckout : ObjectiveC.NSObject {
^
/Users/ganpat/Desktop/Flutter_Apps_Projects_2021/wsflutter/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:59:1: error: unknown attribute '_inheritsConvenienceInitializers'
@_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @objc final public class RazorpayCheckout : ObjectiveC.NSObject {
^
/Users/ganpat/develop/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.2/ios/Classes/RazorpayDelegate.swift:2:8: error: failed to load module 'Razorpay'
import Razorpay
^
Command CompileSwift failed with a nonzero exit code
/Users/ganpat/develop/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-4.4.0/ios/Classes/strategies/NotificationPermissionStrategy.m:71:5: warning: 'UIRemoteNotificationType' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]
UIRemoteNotificationType type = [[UIApplication sharedApplication] enabledRemoteNotificationTypes];
^
In module 'UIKit' imported from /Users/ganpat/Desktop/Flutter_Apps_Projects_2021/wsflutter/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
/Users/ganpat/Desktop/Xcode 2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:69:32: note: 'UIRemoteNotificationType' has been explicitly marked deprecated here
typedef NS_OPTIONS(NSUInteger, UIRemoteNotificationType) {
^
/Users/ganpat/develop/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-4.4.0/ios/Classes/strategies/NotificationPermissionStrategy.m:71:72: warning: 'enabledRemoteNotificationTypes' is deprecated: first deprecated in iOS 8.0 - Use -[UIApplication isRegisteredForRemoteNotifications] and UserNotifications Framework's -[UNUserNotificationCenter getNotificationSettingsWithCompletionHandler:] to retrieve user-enabled remote notification and user notification settings [-Wdeprecated-declarations]
UIRemoteNotificationType type = [[UIApplication sharedApplication] enabledRemoteNotificationTypes];
^
In module 'UIKit' imported from /Users/ganpat/Desktop/Flutter_Apps_Projects_2021/wsflutter/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
/Users/ganpat/Desktop/Xcode 2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:229:1: note: 'enabledRemoteNotificationTypes' has been explicitly marked deprecated here
- (UIRemoteNotificationType)enabledRemoteNotificationTypes API_DEPRECATED("Use -[UIApplication isRegisteredForRemoteNotifications] and UserNotifications Framework's -[UNUserNotificationCenter getNotificationSettingsWithCompletionHandler:] to retrieve user-enabled remote notification and user notification settings", ios(3.0, 8.0)) API_UNAVAILABLE(tvos);
^
2 warnings generated.
note: Using the new build system
note: Planning build
note: Constructing a build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max

**Comment by Nautiyalsachin** [comment]
Hey @rohitsainik, please follow the issue template which we have added whenever you creates an issue. It helps us to get the basic details like package version, pod version, XCode version etc. Please create a new issue including all details.

**Comment by KalyaniGhumare** [comment]
I have the same issue. I have tried several things to resolve it but couldn't.

This is a major issue with Razorpay Flutter. Please don't close this issue by bluntly saying to check pod version, flutter doctor etc. Please address it.

**Comment by Nautiyalsachin** [comment]
Hey @KalyaniGhumare, Please try updating Razorpay-flutter plugin to the latest version. This will help you to fix this issue. Let me know how it goes for you. Our latest version is  v1.2.3. Also the razorpay-pod version should also be latest. Try updating it by `pod update`.
