### ISSUE TITLE
Screen closes and status is PaymentFailure

### ISSUE THREAD

**Issue by Aravind-Tamizh** [razorpay/razorpay-flutter#126]
The error is
[INFO:CONSOLE(1)] "Uncaught ReferenceError: otpPermissionCallback is not defined", source: https://api.razorpay.com/v1/checkout/public?version=1.6.4&library=checkoutjs&platform=android (1)

**Comment by virenvvarasadiya** [comment]
I face the same issues!

**Comment by ujwalp15** [comment]
I face the same issues!

**Comment by Malkhansingh4883** [comment]
I face the same issues! 😕

**Comment by Nautiyalsachin** [comment]
Hey @Malkhansingh4883, @ujwalp15 @virenvvarasadiya and @Aravind-Tamizh: We are working on this issue, this will be resolved soon as we are working on a future release. We will inform you soon about this. Thank you.

**Comment by sumedht** [comment]
@Aravind-Tamizh @virenvvarasadiya @ujwalp15 @Malkhansingh4883 We have updated our razrpay SDK version. Can u check with it

**Comment by kabirsaheb** [comment]
I am getting same error in API 29 Android with 1.6.6 checkout version.

Webview JS Error: Uncaught ReferenceError: otpPermissionCallback is not defined

**Comment by protocentralashwin** [comment]
Any update of this issue?

**Comment by RajaLG** [comment]
Updated to latest version of plugin Still getting same error

**Comment by Nautiyalsachin** [comment]
@protocentralashwin @RajaLG Can you guys try removing and adding it again?

**Comment by michaelspeed** [comment]
this is still happening. any permanent fixes?

**Comment by priya-jain-dev** [comment]
I am facing the same issue. Did anyone find a solution?

**Comment by venky9885** [comment]
i am also facing the issue

**Comment by venky9885** [comment]
Dear Developers @razorpay please Solve this issue in webview javascript, I think you are facing issue because not including Context , i faced same issue  with this type code

**Comment by venky9885** [comment]
Actually i solved issue by changing amount 5000(for 50 INR) see official documentation

**Comment by kakashi01s** [comment]
E/com.razorpay.checkout: Webview JS Error: Uncaught ReferenceError: otpPermissionCallback is not defined

I/chromium: [INFO:CONSOLE(1)] "Uncaught ReferenceError: otpPermissionCallback is not defined", source: https://api.razorpay.com/v1/payments/pay_Hn4DITjGXlL3bP/callback/3dbb0080d7724cf59fb3bfacc9f6c3d7315f2f3e/rzp_test_yQg0rVOwdQLsu3?status=authorized&token_recurring_status=rejected&language_code=en (1)
2021-08-19 18:36:20.410 5371-5371/com.firefly.bikerr.navigation.community.map.bikerr E/ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@2cde7cb that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@2cde7cb that was originally registered here. Are you missing a call to unregisterReceiver()?


Am i doing some Mistake? , whats the problem

**Comment by Priyanshu-2001** [comment]
> E/com.razorpay.checkout: Webview JS Error: Uncaught ReferenceError: otpPermissionCallback is not defined
> 
> I/chromium: [INFO:CONSOLE(1)] "Uncaught ReferenceError: otpPermissionCallback is not defined", source: https://api.razorpay.com/v1/payments/pay_Hn4DITjGXlL3bP/callback/3dbb0080d7724cf59fb3bfacc9f6c3d7315f2f3e/rzp_test_yQg0rVOwdQLsu3?status=authorized&token_recurring_status=rejected&language_code=en (1) 2021-08-19 18:36:20.410 5371-5371/com.firefly.bikerr.navigation.community.map.bikerr E/ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@2cde7cb that was originally registered here. Are you missing a call to unregisterReceiver()? android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@2cde7cb that was originally registered here. Are you missing a call to unregisterReceiver()?
> 
> Am i doing some Mistake? , whats the problem

did u find any solution I am facing same issue

**Comment by xmrdot0** [comment]
I had the same issue, alhamdulillah solved it by multiplying the amount * 100
