### ISSUE TITLE
Unable to hide payment methods

### ISSUE THREAD

**Issue by aadil058** [razorpay/razorpay-flutter#132]
## Description
I am trying to use the below options object to hide payment methods other than net banking and card but unfortunately, it is not working on Android (haven't tried it on iOS yet)

```
        var options = {
          'key': Config.RAZORPAY_CLIENT_ID,
          'amount': (widget.price * 100).toInt().toString(),
          'name': 'wellOwise',
          'description': widget.product,
          'order_id': model.generatedOrderId,
          'prefill': { 'contact': phone, 'email': email },
          'send_sms_hash': '1',
          'external': {
            'wallets': ['paytm']
          },
          "options": {
            "checkout": {
              "method": {
                "netbanking": "1",
                "card": "1",
                "upi": "0",
                "wallet": "0"
              }
            }
          }
        };
```

## Flutter Version :
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (5 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open checkout with the above options object

## Expected Results
Only net banking and card options are enabled on the checkout page

**Comment by Nautiyalsachin** [comment]
Hi @aadil058, If you want to hide the options then please use your razorpay dashboard for hiding and unhiding the options.

**Comment by VimeshLunagariya** [comment]
@aadil058 Are you able to find the option to hide/unhide?
Can I do this in test mode also or not?
