### ISSUE TITLE
Migrate to NNBD

### ISSUE THREAD

**Issue by SirusCodes** [razorpay/razorpay-flutter#133]
## Description
As we know that flutter/dart is migrating to null-safety. It would be great if we could get this package migrated.
https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010

**Comment by Nautiyalsachin** [comment]
@SirusCodes We will still wait for some time to have some proof on this as it is launched very recently, it can have some dependencies around it or might brake something. 

Might be some where end of the year we can take this and include in our plugin.

We will consider it earlier if people starts interacting on this.

 But for now we will do more researches around this.

**Comment by SirusCodes** [comment]
Will wait for the migration

**Comment by akshaybhange** [comment]
@Nautiyalsachin we understand your concern and it is fairly logical to wait for some time and see, but year-end is way too far. In my project, there are only 3 plugins that have not moved to null safety and 2 of them are already under development. Many developers have started moving to null-safe plugins. I'll also request to check your dependencies, if all of them have moved to a null safety then I think you can also go for it.

**Comment by SirusCodes** [comment]
Only `eventify` is not migrated and looking at the package last updated on `Feb 10, 2019` I feel that it won't be migrated as well.

**Comment by yebookin** [comment]
By year end will be very late. we have shifted our app to flutter 2 and now we are unable to accept payments from clients.

**Comment by utrayn** [comment]
> @SirusCodes We will still wait for some time to have some proof on this as it is launched very recently, it can have some dependencies around it or might brake something.
> 
> Might be some where end of the year we can take this and include in our plugin.
> 
> We will consider it earlier if people starts interacting on this.
> 
> But for now we will do more researches around this.

******************** ******************** ******************** ******************** ******************** ********************
By year end will be too late. All of my customers apps have been migrated to flutter 2 and we may be forced to move to another payment gateway if RazorPay plugin does not migrate to null-safety in another month or two at the most.
******************** ******************** ******************** ******************** ******************** ********************

**Comment by SirusCodes** [comment]
@Nautiyalsachin looking at the current condition 2k packages has already been migrated I don't think you need any other proof to migrate the package or if you feel that this won't work properly you can push a development package with -nullsafety suffix so people who really want to try it out they can use it otherwise they can ignore it.

**Comment by Nautiyalsachin** [comment]
@SirusCodes We are working on it with priority here, will update you soon on this. Give us some more time. Thank you for the patience 🙂.

**Comment by SirusCodes** [comment]
Thanks for your response @Nautiyalsachin 😄 Hope you'll can work on it ASAP👍

**Comment by dopecoder** [comment]
Hi @Nautiyalsachin, Any updates on null safety?

**Comment by Nautiyalsachin** [comment]
@dopecoder Working on it, the migration is done, please allow me a couple of days more to test it out thoroughly. We will update you soon here. Thank you for the patience.

**Comment by dopecoder** [comment]
Hi @Nautiyalsachin, how is the null safety migration going?

**Comment by GJJ2019** [comment]
Hi @Nautiyalsachin, are we going to get null safety in this week ?

**Comment by debasmitasarkar** [comment]
@Nautiyalsachin Can you please tell us a timeline if possible? I mean we are out on a limb here.

**Comment by thelazyindian** [comment]
https://github.com/thelazyindian/razorpay-flutter

Made this to work with my flutter project with sound null safety u guys can use this for now.

**Comment by SirusCodes** [comment]
That's great I wasn't expecting that eventify would be migrated, but they did. Hopefully this will also migrate.

@Nautiyalsachin can you accept a PR from @thelazyindian if the migration is not completed yet?

**Comment by GJJ2019** [comment]
@thelazyindian have u tested it on real transactions ?

**Comment by thelazyindian** [comment]
Nope I've just used test cards but I think it'll work in real transactions too.

**Comment by SirusCodes** [comment]
> @thelazyindian have u tested it on real transactions ?

I don't think there should be any issues as all the heavy lifting is done by platform channel and it has a really less dart code.

**Comment by thelazyindian** [comment]
> > @thelazyindian have u tested it on real transactions ?
> 
> I don't think there should be any issues as all the heavy lifting is done by platform channel and it has a really less dart code.

exactly. Just tested which all usecases return null values and made variables nullable accordingly.

**Comment by GJJ2019** [comment]
@SirusCodes & @thelazyindian if that's the case then why its taking so much time to migrate. I think there must be some breaking change in communicating with platform channels.

**Comment by thelazyindian** [comment]
They already did it here https://github.com/razorpay/razorpay-flutter/commit/2f88d0b119a365bc50edb8b9c0efcbff78acd4fb

**Comment by GJJ2019** [comment]
cool so we can close this issue now @SirusCodes

**Comment by SirusCodes** [comment]
Yes thank you team razorpay team!!
