### ISSUE TITLE
Could not run app after add razorpay ONLY IN VERSION 1.2.4

### ISSUE THREAD

**Issue by Aravind-Tamizh** [razorpay/razorpay-flutter#134]
../../.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.4/lib/razorpay_flutter.dart:90:29: Error: The getter 'context' isn't defined for the class 'Razorpay'.
     - 'Razorpay' is from 'package:razorpay_flutter/razorpay_flutter.dart' ('../../.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.4/lib/razorpay_flutter.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'context'.
        _eventEmitter.on(event, context, cb);

**Comment by anugrahkora** [comment]
Same issue

**Comment by shouryalala** [comment]
Faced the same issue. Had to resort to an earlier version:
razorpay_flutter: '1.1.0'

**Comment by sumedht** [comment]
@Aravind-Tamizh @anugrahkora checking with this to resolved on priority. If it's blocking, u can use razorpay_flutter 1.2.3

**Comment by rajmouryapi** [comment]
same issue after updating dependencies.

**Comment by sumedht** [comment]
@rajmouryapi @shouryalala @anugrahkora @Aravind-Tamizh  We have updated to the new version of the flutter plugin with this fix. Plz update to latest.
Closing this ticket. You can always reopen an issue.
