### ISSUE TITLE
While making payment through UPI if I cancel it at last it shows up a form (reason for cancellation) and after one second razorpay calls its Razorpay.EVENT_PAYMENT_SUCCESS.

### ISSUE THREAD

**Issue by Ajay19990** [razorpay/razorpay-flutter#136]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
While making payment through UPI if I cancel it while processing payment it shows up as it is cancelled and a form (reason for cancellation) but after one second razorpay calls its Razorpay.EVENT_PAYMENT_SUCCESS and in code the success part of transaction runs.

## Flutter Version :
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (5 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

## Steps To Reproduce
A simple implementation with a test account of razorpay would do. 

class Cart extends StatefulWidget {
  @override
  _CartState createState() => _CartState();
}

class _CartState extends State<Cart> {
  Razorpay _razorpay;

  @override
  void initState() {
    super.initState();
    _razorpay = Razorpay();
    _razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS, _handlePaymentSuccess);
    _razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, _handlePaymentError);
    _razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET, _handleExternalWallet);
  }

  @override
  void dispose() {
    super.dispose();
    _razorpay.clear();
  }

  void openCheckout() async {
    var options = {
      'key': 'rzp_test_NNbwJ9tmM0fbxj',
      'amount': 28200,
      'name': 'Shaiq',
      'description': 'Payment',
      'prefill': {'contact': '8888888888', 'email': 'test@razorpay.com'},
      'external': {
        'wallets': ['paytm']
      }
    };

    try {
      _razorpay.open(options);
    } catch (e) {
      debugPrint(e);
    }
  }

  void _handlePaymentSuccess(PaymentSuccessResponse response) {
    Fluttertoast.showToast(
        msg: "SUCCESS: " + response.paymentId, timeInSecForIos: 4);
  }

  void _handlePaymentError(PaymentFailureResponse response) {
    Fluttertoast.showToast(
        msg: "ERROR: " + response.code.toString() + " - " + response.message,
        timeInSecForIos: 4);
  }

  void _handleExternalWallet(ExternalWalletResponse response) {
    Fluttertoast.showToast(
        msg: "EXTERNAL_WALLET: " + response.walletName, timeInSecForIos: 4);
  }

  @override
  Widget build(BuildContext context) {
    return BaseView<CartViewModel>(
        onModelReady: (model) {},
        builder: (context, model, build) {
          return Scaffold(
            appBar: AppBar(
              backgroundColor: Colors.white,
              elevation: 0.0,
              centerTitle: true,
              leading: IconButton(
                icon: Icon(Icons.arrow_back, color: Color(0xFF545D68)),
                onPressed: () {
                  Navigator.of(context).pop();
                },
              ),
              title: Text('Cart',
                  style: TextStyle(
                      fontSize: 20.0,
                      color: Color(0xFF545D68))),
              actions: <Widget>[
                IconButton(
                  icon: Icon(
                      Icons.notifications_none, color: Color(0xFFF17532)),
                  onPressed: () {},
                ),
              ],
            ),

            body: ListView(
                children: [
                  SizedBox(height: 15.0),
                  Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Card(
                      child: Row(
                        children: <Widget>[
                          SizedBox(height: 15.0),
                          Hero(
                            tag: 'assets/browniecookies.jpg',
                              child: Image.asset('assets/browniecookies.jpg',
                                  height: 90.0,
                                  width: 90.0,
                                  fit: BoxFit.contain
                              )
                          ),
                          SizedBox(width: 20.0),
                          Column(
                            children: <Widget>[
                              Text('\$3.99',
                                  style: TextStyle(
                                      fontSize: 22.0,
                                      fontWeight: FontWeight.bold,
                                      color: Color(0xFFF17532))),
                              SizedBox(height: 10.0),
                              Text('brownie cookies',
                                  style: TextStyle(
                                      color: Color(0xFF575E67),
                                      fontSize: 24.0)),
                            ],
                          ),

                        ],
                      ),
                    ),
                  ),

                  SizedBox(height: 20.0),
                  InkWell(
                      onTap: () {
                        openCheckout();
                      },
                      child: Padding(
                        padding: const EdgeInsets.only(left:18.0,right: 18),
                        child: Container(
                            width: MediaQuery
                                .of(context)
                                .size
                                .width - 50.0,
                            height: 50.0,
                            decoration: BoxDecoration(
                                borderRadius:
                                BorderRadius.circular(25.0),
                                color: Color(0xFFF17532)),
                            child: Center(
                                child: Text('Checkout',
                                    style: TextStyle(
                                        fontFamily: 'nunito',
                                        fontSize: 14.0,
                                        fontWeight: FontWeight.bold,
                                        color: Colors.white)))),
                      ))
                
                ]
            ),

          );
        }
    );
  }
}

**Comment by synapsecode** [comment]
Similar thing happened to me. I redirected to Google Pay and it showed invalid UPI (I have not activated my account and it is running in test mode) but as it exits, it comes payment successful. Is that a bug or intentional?

**Comment by sumedht** [comment]
@Ajay19990 @synapsecode Ideally it should not call onSuccess(). We will check with this. Is it happening with ios, Android or both

**Comment by PraveenGirishNadumani** [comment]
@Ajay19990  @synapsecode  It seems that you folks are using a test API key for testing the payment. 
please do test the intent payments with the Live API key. PSP apps will throw an invalid VPA error because, in test mode, we are not passing the actual data to PSPs, instead we are passing some dummy details.
Try testing it using the Live API key's post which should work fine.

**Comment by Nautiyalsachin** [comment]
@Ajay19990  @synapsecode Closing this issue due to no response, feel free to add more comments or reopen this issue if this issue persists.

**Comment by reshuashish** [comment]
Having the same issue I am on test api

**Comment by hetthummar** [comment]
I am also having this issue with test API.  Google pay is showing an invalid UPI error but Razorpay status in-app is a success.
Is it intentional behavior for test API?

**Comment by jainharsh21** [comment]
Hello, why is this issue closed, facing the same issue in live APIs as well

**Comment by jainharsh21** [comment]
@PraveenGirishNadumani @sumedht, have been using live API credentials, still facing this same issue with apps like phonepe bhim upi, can you please provide a fix or a solution, thank you!

**Comment by bhoominn** [comment]
I am facing same issue, showing invalid UPI id and even payment failed, razorpay is showing as successful payment. This is big issue. Please do not close this issue, and fix the issue ASAP.

Thank you!

**Comment by maulikpz** [comment]
@bhoominn  I'm also get same error in razorpay integration. Please dont close this issue and solve this ASAP.
