### ISSUE TITLE
Android Build Failed

### ISSUE THREAD

**Issue by mustakimpawle** [razorpay/razorpay-flutter#139]
Facing a build issue since I update my firebase plugins. Below is the error while running on the device using debug.

**Plugin project :razorpay_flutter not found. Please update settings.gradle.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':firebase_core:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':firebase_core:debugCompileClasspath'.
   > Could not find com.google.firebase:firebase-common:.
     Required by:
         project :firebase_core

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1
**

Please find the output of flutter doctor cmd below.
**Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)
    ! Error: Shaheen’s iPhone is not connected. Xcode will continue when Shaheen’s iPhone is connected. (code -13)

• No issues found!**

Below is a list of dependencies used for App.
  cupertino_icons: ^1.0.0
  http:
  get: 3.24.0
  get_storage:
  flutter_cache_manager: ^2.1.1 #^1.1.3
  cached_network_image: ^2.5.0 #^2.0.0
  firebase_messaging:
  firebase_crashlytics:
  firebase_analytics:
  path_provider: ^1.6.27
  razorpay_flutter: ^1.2.4
  firebase_core:
  firebase_auth:
  flutter_svg:

**Comment by sau2019** [comment]
Try to using this package:
razorpay_flutter:^1.1.0

or read the official docs.
https://razorpay.com/docs/payment-gateway/flutter-integration/

**Comment by sumedht** [comment]
@mustakimpawle  We have updated to the new version of the flutter plugin with this fix. Plz update to latest.
Closing this ticket. You can always reopen an issue.
