### ISSUE TITLE
Error: MissingPluginException(No implementation found for method open on channel razorpay_flutter)

### ISSUE THREAD

**Issue by sasi765** [razorpay/razorpay-flutter#142]
Error: MissingPluginException(No implementation found for method open on channel razorpay_flutter)

razorpay 
razorpay_flutter: ^1.1.4
flutter error/
i stuck in this error in before one month.
please help me.

github link : https://github.com/sasi765/razorpay

**Comment by sumedht** [comment]
@sasi765 can u update to version 1.2.3

**Comment by sasi765** [comment]
> @sasi765 can u update to version 1.2.3



> @sasi765 can u update to version 1.2.3

brother, it shows same error.

 throw MissingPluginException('No implementation found for method $method on channel $name');

in platform_channel.dart

**Comment by sumedht** [comment]
@sasi765 We have updated to the new version of the flutter plugin with this fix. Plz update to latest.
Closing this ticket. You can always reopen an issue.
