### ISSUE TITLE
Try correcting the name to the name of an existing getter, or defining a getter or field named 'context'

### ISSUE THREAD

**Issue by xu2012** [razorpay/razorpay-flutter#144]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
/D:/install/flutter/.pub-cache/hosted/pub.flutter-io.cn/razorpay_flutter-1.2.4/lib/razorpay_flutter.dart:1:8: Error: Not found: 'dart:js'
import 'dart:js';
       ^
/D:/install/flutter/.pub-cache/hosted/pub.flutter-io.cn/razorpay_flutter-1.2.4/lib/razorpay_flutter.dart:91:29: Error: The getter 'context' isn't defined for the class 'Razorpay'.
 - 'Razorpay' is from 'package:razorpay_flutter/razorpay_flutter.dart' ('/D:/install/flutter/.pub-cache/hosted/pub.flutter-io.cn/razorpay_flutter-1.2.4/lib/razorpay_flutter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'context'.
    _eventEmitter.on(event, context, cb);
                            ^^^^^^^
U
nhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ajs; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:599:37)
#2      writeDepfile (package:vm/kernel_front_end.d
a
rt:738:21)

## Flutter Version :
2.0

## AndroidStudio Version :
androidstudio4.2

## pluginVersion :
razorpay_flutter: ^1.2.3

## Steps To Reproduce
can not to buildapp

## Expected Results

![image](https://user-images.githubusercontent.com/12170444/109926297-c9414480-7cfd-11eb-9286-f0b3b1b374a1.png)

**Comment by AmSn6** [comment]
Same error occurs in razorpay_flutter: ^1.2.4
Kindly Look into it.

**Comment by sumedht** [comment]
@xu2012 @AmSn6 We have updated to the new version of the flutter plugin with this fix. Plz update to latest.
Closing this ticket. You can always reopen an issue.
