### ISSUE TITLE
App got rejected in the App Store

### ISSUE THREAD

**Issue by surveshoeb** [razorpay/razorpay-flutter#147]
## Description
Like with many applications, we do use Razorpay as the payment gateway for any kind of purchase in our app. Our app is used to sell digital content like Netflix and Amazon Kindle.

### Flutter Version
**1.22.6**

### Xcode Version
**12.4**

### Steps To Reproduce
Same as an example on https://pub.dev/packages/razorpay_flutter

### Expected Results
Smooth deployment on AppStore and PlayStore

### Error from AppStore Review
We noticed that your app includes or accesses paid digital content, services, or functionality by means other than in-app purchase, which is not appropriate for the App Store.
Specifically, the ‘Video Shoutouts’ and ‘Masterclass’ can be purchased by means other than in-app purchase.
Specifically, we noticed that your app offers a subscription with a mechanism other than in-app purchase.
Next Steps
The paid digital content, services, or subscriptions included in or accessed by your app must be available for purchase using in-app purchase.
Apps that offer paid digital services and content across multiple platforms may allow customers to access the content they acquired outside the app as long as it is also available for purchase using in-app purchase. Please see Guideline 3.1.3(b) Multiplatform Services for more information.

### Mine Next Step

- Published the new version with In-App Purchase Capabilities Enabled but still using Razorpay for payment
- Waiting for your response

**Comment by sumedht** [comment]
@surveshoeb What is the razorpay-flutter plugin version ur using? Facing this issue only on iOS?

**Comment by surveshoeb** [comment]
#### Razorpay Version
**1.2.2**

Only on iOS

**Comment by sumedht** [comment]
@surveshoeb From [this](https://developer.apple.com/forums/thread/117900) looks like Apple does not allow to redirect out of the app for digital product purchase.
@Nautiyalsachin add more here

**Comment by VrushankShah01** [comment]
@surveshoeb You need to use In App purchases in IOS if you want to sell digital content. You cannot use any third party payment gateway for selling digital content in IOS. It's allowed in Android but not in IOS.

**Comment by Nautiyalsachin** [comment]
Hi @surveshoeb, as above discussed you can't do the subscription on your app without using Apple's subscription model. You can discuss this with your team for how to proceed, they may have some suggestion on this. Let us know how it goes. Thanks.

**Comment by surveshoeb** [comment]
@Nautiyalsachin it's not just about the subscription model it's the digital content that we are trying to sell. Apple doesn't allow any other payment gateway for this. I have verified many apps such as Netflix, Cameo, Amazon Kindle and more they either use Apples In-App purchase or ask the user to use a different platform for Payment because they don't want to pay Apple 30% cut neither we. 

It will great if Razorpay adds this restriction of Apple on documentation.

**Comment by Nautiyalsachin** [comment]
@surveshoeb We are adding this in our FAQ section so that the merchants can have a reference of the same. Thanks.
