### ISSUE TITLE
Intent Flow for UPI payments in custom checkout implementation

### ISSUE THREAD

**Issue by muhsinzyne** [razorpay/razorpay-flutter#149]
I need some help to integrate the UPI payment custom checkout for google pay and Phonepe.

Right now when my customer wants to make UPI payments the customer needs to click 3 times on the screen to move the installed google pay intent collection request page.

I need to make it as a dedicated button click do redirect to google pay for collection 

I saw a few apps like OYO Zomato are already doing this effectively.

**Comment by sumedht** [comment]
@muhsinzyne We are not providing a custom implementation in a flutter as of now. For custom implementation, u can follow
https://razorpay.com/docs/payment-gateway/android-integration/custom/
https://github.com/razorpay/razorpay-android-custom-sample-app

**Comment by Mayur-9** [comment]
Hi @muhsinzyne,

You can also refer to the document here. https://razorpay.com/docs/payment-gateway/android-integration/custom/payment-methods/#intent-flow_

**Comment by muhsinzyne** [comment]
Hey @Mayur-9  @sumedht  

Do you have any idea about how the OYO App and Zomato have successfully implemented the button click redirect to supported UPI apps and collecting payments. 

I tried many references and non of them are not working with Razorpay default payment with all the options

if I am getting native full documentation of sample app source code I can convert it in to flutter 

somebody, please help me...

**Comment by Nautiyalsachin** [comment]
Hey @muhsinzyne, by our approach there has to be at least two clicks before doing the intent redirection. 

Let us know if you want any help in integrating the existing flow. 

Closing this issue for now. Feel free to add more comments here.

**Comment by keyurcodeShastra** [comment]
@muhsinzyne  Have you found any solution because I am facing the same issue

**Comment by shajin-screl** [comment]
Any updates?
