### ISSUE TITLE
After upgrading RazorPay to 1.2.5 app not running

### ISSUE THREAD

**Issue by Aj4Android** [razorpay/razorpay-flutter#154]
Below is the error I am getting when I tried to run the app:
-> There is some plugin issue. Please resolve this ASAP as project not runninng without it

/E:/PROJECTS/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.5/lib/razorpay_flutter.dart:86:24: Error: A value of type 'Null Function(Event, dynamic)' can't be assigned to a variable of type 'void Function(Event)'.
 - 'Event' is from 'package:eventify/eventify.dart' ('/E:/PROJECTS/flutter/.pub-cache/hosted/pub.dartlang.org/eventify-0.1.4/lib/eventify.dart').
    EventCallback cb = (event, cont) {
                       ^
/E:/PROJECTS/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.5/lib/razorpay_flutter.dart:89:21: Error: Too many positional arguments: 2 allowed, but 3 found.
Try removing the extra positional arguments.
    _eventEmitter.on(event, null, cb);
                    ^

FAILURE: Build failed with an exception.

* Where:
Script 'E:\PROJECTS\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\PROJECTS\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by sumedht** [comment]
@Aj4Android Looks like 
- for 1st error, dark lib is not able to identify the Event class. Which version of Dart ur using. Suggesting to sync it properly.
- From 2nd error, it's an extra parameter issue. which version of flutter ur using? we have tested it till 1.20.0. Planning to move to 2.0.0 in a couple of weeks.

Meanwhile, u can follow doc for ease of integration
https://razorpay.com/docs/payment-gateway/flutter-integration/

**Comment by Aj4Android** [comment]
@sumedht below is the response from Flutter doctor(When I am using RazorPay plugin 1.2.3)

E:\PROJECTS\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.804], locale en-IN)
    • Flutter version 2.0.2 at E:\PROJECTS\flutter
    • Framework revision 8962f6dc68 (7 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Ajinkya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: E:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at E:\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Users\Ajinkya\AppData\Local\JetBrains\IntelliJ IDEA Community Edition 2020.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.54

• No issues found!

**Comment by sumedht** [comment]
@Aj4Android As I said, we are currently on flutter 1.2.0. From docker, it's showing ur using v2.0.2 because of which it may causing issue

**Comment by sumedht** [comment]
@Aj4Android Have u still facing this issue?

**Comment by sumedht** [comment]
@Aj4Android Closing this as there is no further communication. Please feel free to re-open it if u facing same issue.

**Comment by Aj4Android** [comment]
We wrote Webview based Razorpay integration for Android part. Please also
update docs on Razorpay to latest version of flutter 2.0 & also do testing
on 'One plus','Oppo', 'Vivo' android devices
