### ISSUE TITLE
Subscriptions Based Model 

### ISSUE THREAD

**Issue by Prashant4900** [razorpay/razorpay-flutter#155]
Sir is razor pay flutter SDK supports Subscriptions based model in a flutter 
I want to implement the Subscriptions model in flutter but I don't find any docs related to this
## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay Flutter plugin release to make sure your issue has not already been fixed: 

## Flutter Version :
2.0.2

## Xcode Version :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.

## Cocoapod Version :
Go to iOS folder > open `podfile.lock` > copy the `razorpay-pod version` and `razorpay_flutter`a version.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by Nautiyalsachin** [comment]
@Prashant4900 You can take a reference for subscriptions from [here](https://razorpay.com/docs/api/subscriptions/#checkout-integration). There is no specific changes needed for subscriptions from flutter platform. For more details you can contact our tech support team.
