### ISSUE TITLE
Will you please add null-safety support?

### ISSUE THREAD

**Issue by sureace** [razorpay/razorpay-flutter#156]
Hi,
       I am using this razorpay-flutter plugin most of my projects where ever i want to integrate payment gateway. I want migrate all of my projects to null-safety. But razorpay-flutter yet to support null-safety. May i know what is ETA for new release with null-safety support.

Thanks,
Sureace.

**Comment by sumedht** [comment]
@sureace It's in our plan & we are planning to release it in the early week of April. Will update once it is done. Apologise for the inconvenience.

**Comment by ShanmugarajMuthukani** [comment]
**@sureace same question**

**Comment by easwaran198** [comment]
@sumedht  **I am also facing this same problem...**

**Comment by NanthaSekarKumar** [comment]
@sumedht i too facing same issue. I request you to resolve it as soon as possible

**Comment by selvajkumargithub** [comment]
@sumedht I am  facing this problem too. please solve it as soon as possible...

**Comment by sandpsunil** [comment]
@sumedht Hope Razorpay null safe version will be released soon

**Comment by pankaj-nikam** [comment]
Please release it soon.

**Comment by deepak-ra** [comment]
@sureace 
Please check and update the version.
We are facing the issue with our production App.
RazorPay Plugin is the blockage for some other issues. Please....

**Comment by sumedht** [comment]
We have picked this up in our current sprint & will release it soon.

**Comment by deepak-ra** [comment]
@sumedht 
Please. I am not able to debug the app also...
Let me know If it is possible in a day or 2.

**Comment by hurbes** [comment]
Please release null safety version soon

**Comment by dpkswn4** [comment]
Hi RazorPay,
Please release the version with null-safety.
Directly dependent on your package.....
Please.... Release it ASAP....

**Comment by surajmandalcell** [comment]
We also are upgrading to null-safety so we are directly dependent on this package too. Please update.

**Comment by sumedht** [comment]
@deepak-ra we are on it. U Will get update soon

**Comment by dpkswn4** [comment]
> @deepak-ra we are on it. U Will get update soon

🙏 Hope to get the update very soon 🙏

**Comment by deepak-kumar-swain** [comment]
@sumedht 
Sir, Any Update...
We are really struggling, please add the Null Safety feature

**Comment by saurabhguptarock** [comment]
> @sumedht
> Sir, Any Update...
> We are really struggling, please add the Null Safety feature

Please reply @sumedht

**Comment by asbansal** [comment]
> @sureace It's in our plan & we are planning to release it in the early week of April. Will update once it is done. Apologise for the inconvenience.

Hi @sumedht , Thank you for your prompt responses. Is it possible for us to get an ETA so that we can plan our projects better?

Since Razorpay and PayTM are the only ones possible and easy (official flutter documentation is made available by these two only) to integrate, I'll be forced to use PayTM. I was hoping to get an update by April first or second week, but it seems delayed. So, if it's gonna take more weeks, we can re-evaluate our options. I understand you might not have many users using flutter and hence might not be your priority. All I ask is better communication. Thank you for your understanding.

**Comment by deepak-kumar-swain** [comment]
Hi @sumedht 
We are still waiting for the Update.
Lot of things are on queue and we are not able to move forward because of this as this is a direct dependent.
Please give ETA so that we can plan the development.

**Comment by prasant10050** [comment]
Hi @sumedht 
Please release the version with null-safety.
We are still waiting for the Update.

**Comment by Yash-Garg** [comment]
> Hi @sumedht
> Please release the version with null-safety.
> We are still waiting for the Update.

+1 Please release null safety version.

**Comment by mregandla** [comment]
Hi @sumedht, It would be great if you can share the ETA. That will help us plan our project.
This is the only package that is blocking our app upgrade.

**Comment by pankaj-nikam** [comment]
Agree with @mregandla , please update this package. Only thing stopping us also for updating the app.

**Comment by asbansal** [comment]
@ChintanAcharya @pronav @umanghome

**Comment by surendrasahi** [comment]
+1

**Comment by deepak-kumar-swain** [comment]
No Update !!!

**Comment by Srj-Love** [comment]
Hello, 
Is there any ETA?..
We are planning to use Razorpay. But it stopping us due to null-safe.

**Comment by Nautiyalsachin** [comment]
Hi everyone, we are working on it. We will update you soon on this. Thank you for your patience.

**Comment by prasant10050** [comment]
We are already waited too much and our production app is stucked due to
razorpay payment integration. How can we wait without any ETA plan and help.
Now I am able to open razorpay payment in null safety mode but the
callbacks are not returning from plug-in. Can you guys help me where I am
wrong.

**Comment by praveenkprathap** [comment]
use old razorpay package with  --no-sound-null-safety if it's urgent. then when the razorpay release null safety you can enable sound null safety.

**Comment by deepak-kumar-swain** [comment]
@praveenkprathap 
I already have

> @sureace It's in our plan & we are planning to release it in the early week of April. Will update once it is done. Apologise for the inconvenience.

@praveenkprathap 
As per this commitment, I/We migrated to null-safety and designed the code accordingly with other dependencies.
Now it is quite impossible to degrade the code. Hope you understand.

**Comment by praveenkprathap** [comment]
i also migrated entire project to null safety. you don't need to change any code only migrated the project with --no-sound-null-safety then you can use non null safety package as well as null safety packages alone.

**Comment by sureace** [comment]
Hi @sumedht,
                        it has been pending since 40 days. Many apps releases are pending(including my apps) due to null-safety update. I don't know why it is not high priority for razorpay. This kind of delay, creates doubts on Razorpay. For new projects we will look for other alternatives.

**Comment by sumedht** [comment]
@sureace Definitely, it's on our priority It's got a delay because of some unavoidable things come in between which needs to be prioritised. Apologies for the same. We will make sure to release it before 15th May.

**Comment by UjjwaRaijada** [comment]
> @sureace Definitely, it's on our priority It's got a delay because of some unavoidable things come in between which needs to be prioritised. Apologies for the same. We will make sure to release it before 15th May.

It seems either you have a very bad developer team or you do not care about your customers. It has been more than 2 months since you declared this task as your priority. But till date it has not been done. I wonder want happens to the matters which are not your priority.

**Comment by prasant10050** [comment]
I migrated code to null-safety and it took an hour.  It opened in Null
-safety mode in my app but the payment code(java)/dependency is not
responding success callbacks in both release and debug.
When I can migrate the code into null safety in an hour, so why not Razor
Pay team ..they have been fooling us for so many days.

**Comment by deepak-kumar-swain** [comment]
> > @sureace Definitely, it's on our priority It's got a delay because of some unavoidable things come in between which needs to be prioritised. Apologies for the same. We will make sure to release it before 15th May.
> 
> It seems either you have a very bad developer team or you do not care about your customers. It has been more than 2 months since you declared this task as your priority. But till date it has not been done. I wonder want happens to the matters which are not your priority.

Hi @UjjwaRaijada We should not use such words for them. Even my project has direct dependency over this plugin. But such words are not professional. Sorry.

**Comment by deepak-kumar-swain** [comment]
> @sureace Definitely, it's on our priority It's got a delay because of some unavoidable things come in between which needs to be prioritised. Apologies for the same. We will make sure to release it before 15th May.

@sumedht Completely understood your point. But Please understand, people like me dependent on this plugin of yours. Nothing should come before product which is working for certain set of customers. This should be prioritised.
If anything is needed please reach out to us/me. But please release the null-safely version on priority.

**Comment by arshmancodes** [comment]
> @sureace Definitely, it's on our priority It's got a delay because of some unavoidable things come in between which needs to be prioritised. Apologies for the same. We will make sure to release it before 15th May.

Waiting For Null Safe Version anxiously. Already 2 Days late on my project. Please Try to update is as soon as possible.

**Comment by NGC185air110** [comment]
Hello ! We use your project extensively and hope to update the null-safety as soon as possible.
Thank you.

**Comment by prasant10050** [comment]
> @sureace Definitely, it's on our priority It's got a delay because of some unavoidable things come in between which needs to be prioritised. Apologies for the same. We will make sure to release it before 15th May.

It's 16th May, where is your release?

**Comment by mehrozone** [comment]
Still Waiting for the Null Safe Release.

**Comment by UjjwaRaijada** [comment]
> > @sureace Definitely, it's on our priority It's got a delay because of some unavoidable things come in between which needs to be prioritised. Apologies for the same. We will make sure to release it before 15th May.
> 
> It's 16th May, where is your release?

I am sure they are working on it as it is their priority.  PRIORITY .... lol
You can try PayTM if you client is ok with it. They have already released null safety version.

**Comment by prasant10050** [comment]
Yes you are right, 👍

**Comment by asbansal** [comment]
> > > @sureace Definitely, it's on our priority It's got a delay because of some unavoidable things come in between which needs to be prioritised. Apologies for the same. We will make sure to release it before 15th May.
> > 
> > 
> > It's 16th May, where is your release?
> 
> I am sure they are working on it as it is their priority. PRIORITY .... lol
> You can try PayTM if your client is ok with it. They have already released null safety version.
I tried PayTM. Their official plugin is also not null-safe. The one named "paytm" is not the official plugin. The one named "paytm_allinonesdk" is official.

**Comment by asbansal** [comment]
> > > @sureace Definitely, it's on our priority It's got a delay because of some unavoidable things come in between which needs to be prioritised. Apologies for the same. We will make sure to release it before 15th May.
> > 
> > 
> > It's 16th May, where is your release?
> 
> I am sure they are working on it as it is their priority. PRIORITY .... lol
> You can try PayTM if your client is ok with it. They have already released null safety version.

I tried PayTM. Their official plugin is also not null-safe. The one named "paytm" is not the official plugin. The one named "paytm_allinonesdk" is official.

**Comment by sumedht** [comment]
Please update to v1.2.6, we have released it with Null safety support. Thanks for all ur support & patience. Apologies for delay

**Comment by deepak-kumar-swain** [comment]
Thank You @sumedht
