### ISSUE TITLE
Razorpay Flutter-iOS integartion

### ISSUE THREAD

**Issue by SGOPI498** [razorpay/razorpay-flutter#157]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Hi,
We are using razorpay for our flutter apps in test mode.it is working fine for android, in which it is allowing user to type values for payment, but this is not the case with iOS. We are unable to provide/type details like card number, expiry etc.

## Please test using the latest Razorpay Flutter plugin release to make sure your issue has not already been fixed: 
we are using the latest razor pay plugin
razorpay_flutter: ^1.2.5

## Flutter Version :
Run `flutter version` in your terminal and copy the results here.
Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (3 weeks ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

## Xcode Version :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.
Version 12.1
the below is the screenshot for flutter doctor
![Fluuter_doctor](https://user-images.githubusercontent.com/70192595/112462507-21acb480-8d87-11eb-8500-38e35cfb7cd7.jpeg)

the below screen shot is razorpay for android, it is allowing to type card number, expiry etc.
![Razorpay_Android](https://user-images.githubusercontent.com/70192595/112462934-a992be80-8d87-11eb-9f60-b1f0d89931cb.jpeg)

the below screen shot is razorpay for iOS. Unable to type card number and expiry etc.
![Razorpay_iOS](https://user-images.githubusercontent.com/70192595/112462953-aef00900-8d87-11eb-9d95-0fe1365a9907.jpeg)

## Cocoapod Version :
Go to iOS folder > open `podfile.lock` > copy the `razorpay-pod version` and `razorpay_flutter`a version.
razorpay-pod: e2e8cf25aea59eef51c6851716f188df71adab86
razorpay_flutter: 84b3bfd206ae9c9c2a9ba585524a1b3d8102b6c1
COCOAPODS: 1.10.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Integrate the razorpay plugin to the flutter app
2. add the dependency in "pubspec.yaml" file
3. use the "test key" generated from razorpay dashboard
4. test the application for payments like adding card, UPI details etc.

## Expected Results
Describe what you expected to happen.
The razorpay interface is expected to allow user to type card number, expiry and Virtual Payment Address(VPA) values.

## Snack, code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by hiteshgarg002** [comment]
Hi @SGOPI498, as far as I know, this is not related to razorpay.
Follow these steps to resolve your issue

1) Run your application on iOS simulator
2) Go to I/O -> Keyboard
3) Uncheck "Connect Hardware Keyboard"

Hope this helps you.

**Comment by SGOPI498** [comment]
hi hiteshgarg002,
         the issue was resolved. I know it was a silly mistake.

Thanks for your timely response.

**Comment by ohm1998** [comment]
> Hi @SGOPI498, as far as I know, this is not related to razorpay.
> Follow these steps to resolve your issue
> 
> 1. Run your application on iOS simulator
> 2. Go to I/O -> Keyboard
> 3. Uncheck "Connect Hardware Keyboard"
> 
> Hope this helps you.

Works Thank you!

**Comment by Nautiyalsachin** [comment]
Closing this issue now.
