### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by Nilesh-Patel** [razorpay/razorpay-flutter#169]
## Description
After completing the subscription application crashes. It's not happening always but happened few times with me. 
Exception at : com.razorpay.AutoReadOtpHelper.onReceive (AutoReadOtpHelper.java)

## Flutter Version :
Flutter 2.0.0 • channel stable • https://github.com/flutter/flutter.git

## Xcode Version :
Version 12.4

## Cocoapod Version :
  - razorpay-pod (1.1.12)
  - razorpay_flutter (1.1.10):

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Start payment process.
2. Use cards option for payment. 
3. After doing payment, App crashes because of exception. Exception is generated at : com.razorpay.AutoReadOtpHelper.onReceive (AutoReadOtpHelper.java)

## Expected Results
Payment process have to be completed without crash.

**Comment by sumedht** [comment]
@Nilesh-Patel Can u update to a newer version of our SDK. We have fixed this issue in the latest version.

**Comment by sumedht** [comment]
@Nilesh-Patel Closing this as there is no update. Feel free to reopen it if ur facing this again.
