### ISSUE TITLE
When would the package migrate to null safety?

### ISSUE THREAD

**Issue by xenowits** [razorpay/razorpay-flutter#171]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay Flutter plugin release to make sure your issue has not already been fixed: 

## Flutter Version :
Flutter 2.0.6 • channel stable

## Xcode Version :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.

## Cocoapod Version :
Go to iOS folder > open `podfile.lock` > copy the `razorpay-pod version` and `razorpay_flutter`a version.

## Expected Results
I expect the razorpay_flutter package to be migrated to null safety.

**Comment by Iamsdt** [comment]
Check this issue
https://github.com/razorpay/razorpay-flutter/issues/133

**Comment by sumedht** [comment]
@xenowits @Iamsdt Please update to v1.2.6, we have released it with Null safety support.
