### ISSUE TITLE
Prefill Method issue

### ISSUE THREAD

**Issue by xirainfotech** [razorpay/razorpay-flutter#182]
## Description
I have a scenario where i have options for users to select payment mode i.e: UPI, Net Banking, Wallet, and with prefill method im able to achieve that and when razor pay checkout form is opened then users can go back and change payment method from razor pay

## Flutter Version :
2.0.6

## Steps To Reproduce

1.  'prefill': {'contact': '$phone', 'email': '$email', 'method': 'upi'},
2. Then when razorpay form opens you can change payment method

## Expected Results
It shouldn't allow users to switch pay method once we prefill our pay method

**Comment by vivekshindhe** [comment]
@xirainfotech Hey, thanks for reaching out to us. So, prefill only gives control upto such extent. If you want to hard-control the payment methods via which customer can pay you'll have to use config. I'm attaching the link to the docs for that here. [Link](https://razorpay.com/docs/payment-links/api/new/advanced-options/customize/payment-methods/)

Please follow the steps here to achieve the end goal. Thank you. Closing this for now. Please leave a comment or open another issue for more assistance from us.

**Comment by xirainfotech** [comment]
Any example on how to implement this with flutter?

**Comment by xirainfotech** [comment]
Hello, Im not able to do this in flutter, Can you help?
Here's my code.
'description': 'Thank You For Shopping With Us',
      'prefill': {'contact': '$phone', 'email': '$email', 'method': '$method'},
      'checkout': {
        'method': {
          "netbanking": netbanking,
          "card": card,
          "upi": upi,
          "wallet": wallet,
        }
      },
      'external': {
        'wallets': ['paytm']
      },
      'theme': {'color': '#ffE39B54'}
