### ISSUE TITLE
Repayment gets failed.

### ISSUE THREAD

**Issue by anup-geeky** [razorpay/razorpay-flutter#185]
When I try to make payment, I am getting the below error message.

{"code":"BAD_REQUEST_ERROR","description":"The id provided does not exist","source":"NA","step":"NA","reason":"NA","metadata":{}}

"error_message":"Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference","error_level":"critical"

What I actually doing is
1) Login with a mobile number whose subscription is expired
2) Initiate payment, enter mobile number in Razorpay payment gateway, enter OTP, enter card CVC number, and succeed.
3) Logout (Clear all shared preference) and log in with another mobile number whose subscription is expired
4) Initiate payment and get payment failed error.

D/com.razorpay.checkout( 7444): Modified Url: https://api.razorpay.com/v1/checkout/public?version=1.6.10&library=checkoutjs&platform=android&invoice_id=inv_HdvpqAyFjlt9kr
W/System.err( 7444): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
W/System.err( 7444): 	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
W/System.err( 7444): 	at org.json.JSONTokener.nextValue(JSONTokener.java:94)
W/System.err( 7444): 	at org.json.JSONObject.<init>(JSONObject.java:159)
W/System.err( 7444): 	at org.json.JSONObject.<init>(JSONObject.java:176)
W/System.err( 7444): 	at com.razorpay.CheckoutPresenterImpl.setOptions(:196)
W/System.err( 7444): 	at com.razorpay.BaseCheckoutActivity.onCreate(:106)
W/System.err( 7444): 	at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(:26)
W/System.err( 7444): 	at com.razorpay.CheckoutActivity.onCreate(:8)
W/System.err( 7444): 	at android.app.Activity.performCreate(Activity.java:6984)
W/System.err( 7444): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
W/System.err( 7444): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2857)
W/System.err( 7444): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2986)
W/System.err( 7444): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
W/System.err( 7444): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1671)
W/System.err( 7444): 	at android.os.Handler.dispatchMessage(Handler.java:108)
W/System.err( 7444): 	at android.os.Looper.loop(Looper.java:206)
W/System.err( 7444): 	at android.app.ActivityThread.main(ActivityThread.java:6784)
W/System.err( 7444): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7444): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err( 7444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
W/ResourceType( 7444): Attempt to retrieve bag 0x7f1000a1 which is invalid or in a cycle.
D/WebView ( 7444): WebView<init>
D/WebView ( 7444): addJavascriptInterface=StorageBridge
D/WebView ( 7444): clearFormData
D/WebView ( 7444): addJavascriptInterface=CheckoutBridge
D/WebView ( 7444): WebView<init>
D/WebView ( 7444): addJavascriptInterface=StorageBridge
D/WebView ( 7444): clearFormData
D/WebView ( 7444): addJavascriptInterface=MagicBridge
D/WebView ( 7444): addJavascriptInterface=CheckoutBridge
W/System.err( 7444): java.lang.Exception: No dash options defined
W/System.err( 7444): 	at com.razorpay.CheckoutPresenterImpl.getProgressBarColor(:650)
W/System.err( 7444): 	at com.razorpay.BaseCheckoutActivity.createContainer(:227)
W/System.err( 7444): 	at com.razorpay.BaseCheckoutActivity.onCreate(:113)
W/System.err( 7444): 	at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(:26)
W/System.err( 7444): 	at com.razorpay.CheckoutActivity.onCreate(:8)
W/System.err( 7444): 	at android.app.Activity.performCreate(Activity.java:6984)
W/System.err( 7444): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
W/System.err( 7444): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2857)
W/System.err( 7444): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2986)
W/System.err( 7444): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
W/System.err( 7444): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1671)
W/System.err( 7444): 	at android.os.Handler.dispatchMessage(Handler.java:108)
W/System.err( 7444): 	at android.os.Looper.loop(Looper.java:206)
W/System.err( 7444): 	at android.app.ActivityThread.main(ActivityThread.java:6784)
W/System.err( 7444): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7444): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err( 7444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
W/System.err( 7444): org.json.JSONException: No value for theme
W/System.err( 7444): 	at org.json.JSONObject.get(JSONObject.java:392)
W/System.err( 7444): 	at org.json.JSONObject.getJSONObject(JSONObject.java:612)
W/System.err( 7444): 	at com.razorpay.CheckoutPresenterImpl.getProgressBarColor(:635)
W/System.err( 7444): 	at com.razorpay.BaseCheckoutActivity.createContainer(:227)
W/System.err( 7444): 	at com.razorpay.BaseCheckoutActivity.onCreate(:113)
W/System.err( 7444): 	at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(:26)
W/System.err( 7444): 	at com.razorpay.CheckoutActivity.onCreate(:8)
W/System.err( 7444): 	at android.app.Activity.performCreate(Activity.java:6984)
W/System.err( 7444): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
W/System.err( 7444): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2857)
W/System.err( 7444): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2986)
W/System.err( 7444): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
W/System.err( 7444): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1671)
W/System.err( 7444): 	at android.os.Handler.dispatchMessage(Handler.java:108)
W/System.err( 7444): 	at android.os.Looper.loop(Looper.java:206)
W/System.err( 7444): 	at android.app.ActivityThread.main(ActivityThread.java:6784)
W/System.err( 7444): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7444): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err( 7444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
D/com.razorpay.checkout( 7444): OTPElf Constructor
D/com.razorpay.checkout( 7444): No permission for reading SMS
D/WebView ( 7444): addJavascriptInterface=OTPElfBridge
D/com.razorpay.checkout( 7444): OTPElf Constructor
D/com.razorpay.checkout( 7444): No permission for reading SMS
D/WebView ( 7444): addJavascriptInterface=OTPElfBridge
D/WebView ( 7444): loadUrl
I/System.out( 7444): isEmailSend:GET
I/System.out( 7444): [OkHttp] sendRequest>>
I/System.out( 7444): [OkHttp] sendRequest<<
I/zygote64( 7444): Compiler allocated 4MB to compile void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int)
D/com.razorpay.checkout( 7444): NOT FULLSCREEN
D/WebView ( 7444): WebView<init>
W/System.err( 7444): java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
W/System.err( 7444): 	at android.app.ContextImpl.checkMode(ContextImpl.java:2411)
W/System.err( 7444): 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:386)
W/System.err( 7444): 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:373)
W/System.err( 7444): 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:167)
W/System.err( 7444): 	at com.razorpay.SharedPreferenceUtil.getPublicPrefs(:63)
W/System.err( 7444): 	at com.razorpay.CardSaving.getDeviceToken(:265)
W/System.err( 7444): 	at com.razorpay.CardSaving.fetchDeviceTokenFromOtherAppsIfRequired(:167)
W/System.err( 7444): 	at com.razorpay.CheckoutPresenterImpl.handleCardSaving(:406)
W/System.err( 7444): 	at com.razorpay.BaseCheckoutActivity.onCreate(:152)
W/System.err( 7444): 	at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(:26)
W/System.err( 7444): 	at com.razorpay.CheckoutActivity.onCreate(:8)
W/System.err( 7444): 	at android.app.Activity.performCreate(Activity.java:6984)
W/System.err( 7444): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
W/System.err( 7444): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2857)
W/System.err( 7444): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2986)
W/System.err( 7444): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
W/System.err( 7444): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1671)
W/System.err( 7444): 	at android.os.Handler.dispatchMessage(Handler.java:108)
W/System.err( 7444): 	at android.os.Looper.loop(Looper.java:206)
W/System.err( 7444): 	at android.app.ActivityThread.main(ActivityThread.java:6784)
W/System.err( 7444): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7444): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err( 7444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
V/PhoneWindow( 7444): DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@af69d8e[]
D/WindowClient( 7444): Add to mViews: DecorView@af69d8e[CheckoutActivity], this = android.view.WindowManagerGlobal@f71b260
D/OpenGLRenderer( 7444): CanvasContext() 0x79759ecac0
D/Surface ( 7444): Surface::allocateBuffers(this=0x7948e9e000)
D/OpenGLRenderer( 7444): CanvasContext() 0x79759ecac0 initialize window=0x7948e9e000
D/Surface ( 7444): Surface::connect(this=0x7948e9e000,api=1)
D/mali_winsys( 7444): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
D/Surface ( 7444): Surface::disconnect(this=0x7985dfb000,api=1)
D/Surface ( 7444): Surface::disconnect(this=0x7985dfb000,api=-1)
D/Surface ( 7444): Surface::disconnect(this=0x7985cb8000,api=1)
I/System.out( 7444): isEmailSend:GET
I/System.out( 7444): [OkHttp] sendRequest>>
I/System.out( 7444): [OkHttp] sendRequest<<
D/com.razorpay.checkout( 7444): Updating OTPElf
D/WindowClient( 7444): Add to mViews: DecorView@b43b677[], this = android.view.WindowManagerGlobal@f71b260
D/OpenGLRenderer( 7444): CanvasContext() 0x794d338100
D/com.razorpay.checkout( 7444): RzpAssist onPageStarted: https://api.razorpay.com/v1/checkout/public?version=1.6.10&library=checkoutjs&platform=android&invoice_id=inv_HdvpqAyFjlt9kr
D/OpenGLRenderer( 7444): CanvasContext() 0x794d338100 initialize window=0x7947b4d000
D/Surface ( 7444): Surface::allocateBuffers(this=0x7947b4d000)
D/Surface ( 7444): Surface::connect(this=0x7947b4d000,api=1)
D/mali_winsys( 7444): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
I/System.out( 7444): isEmailSend:GET
I/System.out( 7444): [OkHttp] sendRequest>>
I/System.out( 7444): [OkHttp] sendRequest<<
D/com.razorpay.checkout( 7444): Updating OTPElf
W/ResourceType( 7444): ResTable_typeSpec entry count inconsistent: given 818, previously 1276
W/ResourceType( 7444): ResTable_typeSpec entry count inconsistent: given 4638, previously 4639
W/ResourceType( 7444): ResTable_typeSpec entry count inconsistent: given 196, previously 1312
D/skia    ( 7444): --- SkAndroidCodec::NewFromStream returned null
W/System.err( 7444): java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
W/System.err( 7444): 	at android.app.ContextImpl.checkMode(ContextImpl.java:2411)
W/System.err( 7444): 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:386)
W/System.err( 7444): 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:373)
W/System.err( 7444): 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:167)
W/System.err( 7444): 	at com.razorpay.SharedPreferenceUtil.getPublicPrefs(:63)
W/System.err( 7444): 	at com.razorpay.CardSaving.getDeviceToken(:265)
W/System.err( 7444): 	at com.razorpay.CheckoutPresenterImpl.getOptionsForHandleMessage(:848)
W/System.err( 7444): 	at com.razorpay.CheckoutPresenterImpl.getHandleMessageFormattedString(:865)
W/System.err( 7444): 	at com.razorpay.CheckoutPresenterImpl.access$300(:49)
W/System.err( 7444): 	at com.razorpay.CheckoutPresenterImpl$7.run(:777)
W/System.err( 7444): 	at android.app.Activity.runOnUiThread(Activity.java:6161)
W/System.err( 7444): 	at com.razorpay.CheckoutPresenterImpl.onLoad(:774)
W/System.err( 7444): 	at com.razorpay.CheckoutBridge$1.secure(:27)
W/System.err( 7444): 	at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(:1257)
W/System.err( 7444): 	at com.razorpay.CheckoutPresenterImpl.access$700(:49)
W/System.err( 7444): 	at com.razorpay.CheckoutPresenterImpl$17.run(:1243)
W/System.err( 7444): 	at android.os.Handler.handleCallback(Handler.java:869)
W/System.err( 7444): 	at android.os.Handler.dispatchMessage(Handler.java:101)
W/System.err( 7444): 	at android.os.Looper.loop(Looper.java:206)
W/System.err( 7444): 	at android.app.ActivityThread.main(ActivityThread.java:6784)
W/System.err( 7444): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7444): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err( 7444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
D/WebView ( 7444): loadUrl
D/Surface ( 7444): Surface::disconnect(this=0x7947b4d000,api=1)
D/WindowClient( 7444): Remove from mViews: DecorView@b43b677[], this = android.view.WindowManagerGlobal@f71b260
D/com.razorpay.checkout( 7444): Checkout loaded in 0.56 sec.
D/WebView ( 7444): clearHistory
D/com.razorpay.checkout( 7444): not magic
D/WebView ( 7444): loadUrl
D/WebView ( 7444): loadUrl
I/System.out( 7444): isEmailSend:GET
I/System.out( 7444): [OkHttp] sendRequest>>
I/System.out( 7444): [OkHttp] sendRequest<<
D/NativeCrypto( 7444): ssl=0x79a17283c0 NativeCrypto_SSL_interrupt
I/System.out( 7444): isEmailSend:GET
E/com.razorpay.checkout( 7444): Webview JS Error: Uncaught SyntaxError: Invalid or unexpected token
I/chromium( 7444): [INFO:CONSOLE(1)] "Uncaught SyntaxError: Invalid or unexpected token", source: https://api.razorpay.com/v1/checkout/public?version=1.6.10&library=checkoutjs&platform=android&invoice_id=inv_HdvpqAyFjlt9kr (1)
I/System.out( 7444): isEmailSend:GET
D/NativeCrypto( 7444): ssl=0x79a17283c0 NativeCrypto_SSL_do_handshake fd=0x796af2c9f8 shc=0x796af2c9fc timeout_millis=150
D/NativeCrypto( 7444): ssl=0x79a17283c0 info_callback completed
D/NativeCrypto( 7444): ssl=0x79a163c340 NativeCrypto_SSL_do_handshake fd=0x796a5faa18 shc=0x796a5faa1c timeout_millis=20000
D/NativeCrypto( 7444): ssl=0x79a163c340 info_callback completed
D/NativeCrypto( 7444): ssl=0x79a17283c0 cert_verify_callback => 1
I/System.out( 7444): [OkHttp] sendRequest>>
I/System.out( 7444): [OkHttp] sendRequest<<
D/NativeCrypto( 7444): ssl=0x79a163c340 cert_verify_callback => 1
I/System.out( 7444): [OkHttp] sendRequest>>
I/System.out( 7444): [OkHttp] sendRequest<<
D/OpenGLRenderer( 7444): ~CanvasContext() 0x794d338100
D/NativeCrypto( 7444): ssl=0x79a17283c0 info_callback completed
D/NativeCrypto( 7444): ssl=0x79a163c340 info_callback completed
D/NativeCrypto( 7444): ssl=0x79a17283c0 NativeCrypto_SSL_interrupt
I/System.out( 7444): isEmailSend:GET
I/System.out( 7444): [OkHttp] sendRequest>>
I/System.out( 7444): [OkHttp] sendRequest<<
D/com.razorpay.checkout( 7444): Sending data to lumberjack
D/OpenGLRenderer( 7444): CanvasContext() 0x798b149980 initialize window=0x7947b4d000
D/Surface ( 7444): Surface::connect(this=0x7947b4d000,api=1)
D/mali_winsys( 7444): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
I/flutter ( 7444): Checkout Failure 1 {"code":"BAD_REQUEST_ERROR","description":"The id provided does not exist","source":"NA","step":"NA","reason":"NA","metadata":{}}
D/Surface ( 7444): Surface::connect(this=0x7947b4e000,api=1)
D/mali_winsys( 7444): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
D/Surface ( 7444): Surface::disconnect(this=0x7948e9e000,api=1)
I/System.out( 7444): isEmailSend:GET
I/System.out( 7444): [OkHttp] sendRequest>>
I/System.out( 7444): [OkHttp] sendRequest<<
W/System.err( 7444): java.lang.IllegalArgumentException: bad base-64
W/System.err( 7444): 	at android.util.Base64.decode(Base64.java:161)
W/System.err( 7444): 	at android.util.Base64.decode(Base64.java:136)
W/System.err( 7444): 	at com.razorpay.CryptLib.encryptDecrypt(:174)
W/System.err( 7444): 	at com.razorpay.CryptLib.decrypt(:269)
W/System.err( 7444): 	at com.razorpay.BaseUtils.decryptFile(:719)
W/System.err( 7444): 	at com.razorpay.OtpElfData$2.run(:55)
W/System.err( 7444): 	at com.razorpay.Owl.onPostExecute(:137)
W/System.err( 7444): 	at com.razorpay.Owl.onPostExecute(:23)
W/System.err( 7444): 	at android.os.AsyncTask.finish(AsyncTask.java:695)
W/System.err( 7444): 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
W/System.err( 7444): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
W/System.err( 7444): 	at android.os.Handler.dispatchMessage(Handler.java:108)
W/System.err( 7444): 	at android.os.Looper.loop(Looper.java:206)
W/System.err( 7444): 	at android.app.ActivityThread.main(ActivityThread.java:6784)
W/System.err( 7444): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7444): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err( 7444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
D/com.razorpay.checkout( 7444): Unable to decrypt file, bad base-64
D/Log     ( 7444): onActivityDestroyed
D/com.razorpay.checkout( 7444): CheckoutActivity onDestroy called
D/WebView ( 7444): loadUrl
W/System.err( 7444): java.util.ConcurrentModificationException
W/System.err( 7444): 	at java.util.ArrayList$Itr.next(ArrayList.java:860)
W/System.err( 7444): 	at com.razorpay.SmsAgent.sendSmsPermissionCallBack(:110)
W/System.err( 7444): 	at com.razorpay.SmsAgent.removeSMSBroadcastReceiver(:76)
W/System.err( 7444): 	at com.razorpay.RzpAssist.paymentFlowEnd(:202)
W/System.err( 7444): 	at com.razorpay.OtpElfCheckoutPresenterImpl.addOnFlowEnd(:130)
W/System.err( 7444): 	at com.razorpay.CheckoutPresenterImpl.cleanUpOnDestroy(:700)
W/System.err( 7444): 	at com.razorpay.BaseCheckoutActivity.onDestroy(:178)
W/System.err( 7444): 	at android.app.Activity.performDestroy(Activity.java:7186)
W/System.err( 7444): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1270)
W/System.err( 7444): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4620)
W/System.err( 7444): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4651)
W/System.err( 7444): 	at android.app.ActivityThread.-wrap5(Unknown Source:0)
W/System.err( 7444): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1732)
W/System.err( 7444): 	at android.os.Handler.dispatchMessage(Handler.java:108)
W/System.err( 7444): 	at android.os.Looper.loop(Looper.java:206)
W/System.err( 7444): 	at android.app.ActivityThread.main(ActivityThread.java:6784)
W/System.err( 7444): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7444): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err( 7444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
W/System.err( 7444): java.util.ConcurrentModificationException
W/System.err( 7444): 	at java.util.ArrayList$Itr.next(ArrayList.java:860)
W/System.err( 7444): 	at com.razorpay.SmsAgent.sendSmsPermissionCallBack(:110)
W/System.err( 7444): 	at com.razorpay.SmsAgent.removeSMSBroadcastReceiver(:76)
W/System.err( 7444): 	at com.razorpay.RzpAssist.paymentFlowEnd(:202)
W/System.err( 7444): 	at com.razorpay.OtpElfCheckoutPresenterImpl.addOnFlowEnd(:130)
W/System.err( 7444): 	at com.razorpay.CheckoutPresenterImpl.cleanUpOnDestroy(:700)
W/System.err( 7444): 	at com.razorpay.BaseCheckoutActivity.onDestroy(:178)
W/System.err( 7444): 	at android.app.Activity.performDestroy(Activity.java:7186)
W/System.err( 7444): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1270)
W/System.err( 7444): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4620)
W/System.err( 7444): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4651)
W/System.err( 7444): 	at android.app.ActivityThread.-wrap5(Unknown Source:0)
W/System.err( 7444): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1732)
W/System.err( 7444): 	at android.os.Handler.dispatchMessage(Handler.java:108)
W/System.err( 7444): 	at android.os.Looper.loop(Looper.java:206)
W/System.err( 7444): 	at android.app.ActivityThread.main(ActivityThread.java:6784)
W/System.err( 7444): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7444): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err( 7444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
D/WindowClient( 7444): Remove from mViews: DecorView@af69d8e[CheckoutActivity], this = android.view.WindowManagerGlobal@f71b260
E/com.razorpay.checkout( 7444): Webview JS Error: Uncaught ReferenceError: otpPermissionCallback is not defined
I/chromium( 7444): [INFO:CONSOLE(1)] "Uncaught ReferenceError: otpPermissionCallback is not defined", source: https://api.razorpay.com/v1/checkout/public?version=1.6.10&library=checkoutjs&platform=android&invoice_id=inv_HdvpqAyFjlt9kr (1)
E/ActivityThread( 7444): Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@8d052e3 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread( 7444): android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@8d052e3 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread( 7444): 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1377)
E/ActivityThread( 7444): 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1123)
E/ActivityThread( 7444): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1420)
E/ActivityThread( 7444): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1381)
E/ActivityThread( 7444): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1369)
E/ActivityThread( 7444): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:603)
E/ActivityThread( 7444): 	at com.razorpay.CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP(:827)
E/ActivityThread( 7444): 	at com.razorpay.CheckoutPresenterImpl.onLoad(:818)
E/ActivityThread( 7444): 	at com.razorpay.CheckoutBridge$1.secure(:27)
E/ActivityThread( 7444): 	at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(:1257)
E/ActivityThread( 7444): 	at com.razorpay.CheckoutPresenterImpl.access$700(:49)
E/ActivityThread( 7444): 	at com.razorpay.CheckoutPresenterImpl$17.run(:1243)
E/ActivityThread( 7444): 	at android.os.Handler.handleCallback(Handler.java:869)
E/ActivityThread( 7444): 	at android.os.Handler.dispatchMessage(Handler.java:101)
E/ActivityThread( 7444): 	at android.os.Looper.loop(Looper.java:206)
E/ActivityThread( 7444): 	at android.app.ActivityThread.main(ActivityThread.java:6784)
E/ActivityThread( 7444): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread( 7444): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/ActivityThread( 7444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
D/OpenGLRenderer( 7444): ~CanvasContext() 0x79759ecac0
W/System.err( 7444): java.lang.IllegalArgumentException: bad base-64
W/System.err( 7444): 	at android.util.Base64.decode(Base64.java:161)
W/System.err( 7444): 	at android.util.Base64.decode(Base64.java:136)
W/System.err( 7444): 	at com.razorpay.CryptLib.encryptDecrypt(:174)
W/System.err( 7444): 	at com.razorpay.CryptLib.decrypt(:269)
W/System.err( 7444): 	at com.razorpay.BaseUtils.decryptFile(:719)
W/System.err( 7444): 	at com.razorpay.OtpElfData$2.run(:55)
W/System.err( 7444): 	at com.razorpay.Owl.onPostExecute(:137)
W/System.err( 7444): 	at com.razorpay.Owl.onPostExecute(:23)
W/System.err( 7444): 	at android.os.AsyncTask.finish(AsyncTask.java:695)
W/System.err( 7444): 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
W/System.err( 7444): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
W/System.err( 7444): 	at android.os.Handler.dispatchMessage(Handler.java:108)
W/System.err( 7444): 	at android.os.Looper.loop(Looper.java:206)
I/System.out( 7444): isEmailSend:GET
W/System.err( 7444): 	at android.app.ActivityThread.main(ActivityThread.java:6784)
W/System.err( 7444): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7444): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err( 7444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
D/com.razorpay.checkout( 7444): Unable to decrypt file, bad base-64
I/System.out( 7444): [OkHttp] sendRequest>>
I/System.out( 7444): [OkHttp] sendRequest<<
D/WebView ( 7444): loadUrl
E/com.razorpay.checkout( 7444): Webview JS Error: Uncaught TypeError: window.getDeviceDetails is not a function
I/chromium( 7444): [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.6.10&library=checkoutjs&platform=android&invoice_id=inv_HdvpqAyFjlt9kr (1)
I/System.out( 7444): isEmailSend:POST
I/System.out( 7444): Check isMmsSendPdu
I/System.out( 7444): PDU read len:13848
I/System.out( 7444): MMS PDU Type:123:34
I/System.out( 7444): [OkHttp] sendRequest>>
W/System.err( 7444): java.lang.IllegalArgumentException: bad base-64
W/System.err( 7444): 	at android.util.Base64.decode(Base64.java:161)
W/System.err( 7444): 	at android.util.Base64.decode(Base64.java:136)
W/System.err( 7444): 	at com.razorpay.CryptLib.encryptDecrypt(:174)
W/System.err( 7444): 	at com.razorpay.CryptLib.decrypt(:269)
W/System.err( 7444): 	at com.razorpay.BaseUtils.decryptFile(:719)
W/System.err( 7444): 	at com.razorpay.MagicData$2.run(:41)
W/System.err( 7444): 	at com.razorpay.Owl.onPostExecute(:137)
W/System.err( 7444): 	at com.razorpay.Owl.onPostExecute(:23)
W/System.err( 7444): 	at android.os.AsyncTask.finish(AsyncTask.java:695)
W/System.err( 7444): 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
W/System.err( 7444): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
W/System.err( 7444): 	at android.os.Handler.dispatchMessage(Handler.java:108)
W/System.err( 7444): 	at android.os.Looper.loop(Looper.java:206)
W/System.err( 7444): 	at android.app.ActivityThread.main(ActivityThread.java:6784)
W/System.err( 7444): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7444): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err( 7444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
D/com.razorpay.checkout( 7444): Unable to decrypt file, bad base-64
I/System.out( 7444): [OkHttp] sendRequest<<
D/com.razorpay.checkout( 7444): Response from lumberjack:
W/WebEngage( 7444): Location Tracking is enabled but location permission is not granted to application
W/WebEngage( 7444): Location Tracking is enabled but location permission is not granted to application
I/System.out( 7444): isEmailSend:GET
I/System.out( 7444): [OkHttp] sendRequest>>
I/System.out( 7444): [OkHttp] sendRequest<<
W/WebEngage( 7444): Location Tracking is enabled but location permission is not granted to application
W/WebEngage( 7444): Location Tracking is enabled but location permission is not granted to application
I/System.out( 7444): isEmailSend:GET
I/System.out( 7444): [OkHttp] sendRequest>>
I/System.out( 7444): [OkHttp] sendRequest<<
W/WebEngage( 7444): Location Tracking is enabled but location permission is not granted to application
D/NativeCrypto( 7444): ssl=0x79a1729900 NativeCrypto_SSL_interrupt
W/WebEngage( 7444): Location Tracking is enabled but location permission is not granted to application
W/WebEngage( 7444): Location Tracking is enabled but location permission is not granted to application
I/System.out( 7444): isEmailSend:GET
I/System.out( 7444): [OkHttp] sendRequest>>
I/System.out( 7444): [OkHttp] sendRequest<<
W/WebEngage( 7444): Location Tracking is enabled but location permission is not granted to application

**Comment by sumedht** [comment]
@anup-geeky Wanted to know r u getting onError(..) callback with error code & description or fatal error?

**Comment by anup-geeky** [comment]
in  onError callback (   _razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, _handlePaymentError); )

**Comment by sumedht** [comment]
@anup-geeky Can u share a video of this.. where u Loggin & Logout? In save cards?

**Comment by sumedht** [comment]
@anup-geeky Closing this as there is no further communication. Feel free to open it if u still facing this issue.

**Comment by holy-dev** [comment]
@anup-geeky how did you solve this one?

**Comment by holy-dev** [comment]
@anup-geeky I solved it.

**Comment by holy-dev** [comment]
> @holy-dev : How did you solved?

Just remove the signature from razorpay response or you can use the new custom UI package.
