### ISSUE TITLE
No callbacks from gpay 

### ISSUE THREAD

**Issue by anasnaji25** [razorpay/razorpay-flutter#187]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
when i initiate a payment and when i select gpay its redirecting to gpay app and when i complete the payamnt its not returning any success callback or response and its not comming back to my app

## Flutter Version : 
Flutter 2.2.3 • channel stable

## Steps To Reproduce

1.entering to razorpay for payment 
2. selecting gpay to pay
3. its redirecting to gpay
4. completing transaction in gpay
5. thats its nothing is happening next
6. no callbacks or response
7. im using the live api

## Expected Results
im expecting after the transaction in gpay it should give me response or invoke the paymentSuccess callback

## Snack, code example, screenshot, or link to a repository:
this is the logs that are printing when im doing the payment in razorpay

`  D/com.razorpay.checkout(32424): Modified Url: https://api.razorpay.com/v1/checkout/public?version=1.6.10&library=checkoutjs&platform=android
W/System.err(32424): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
W/System.err(32424):    at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
W/System.err(32424):    at org.json.JSONTokener.nextValue(JSONTokener.java:98)
W/System.err(32424):    at org.json.JSONObject.<init>(JSONObject.java:164)
W/System.err(32424):    at org.json.JSONObject.<init>(JSONObject.java:181)
W/System.err(32424):    at com.razorpay.CheckoutPresenterImpl.setOptions(CheckoutPresenterImpl.java:196)
W/System.err(32424):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:106)
W/System.err(32424):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:26)
W/System.err(32424):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(32424):    at android.app.Activity.performCreate(Activity.java:8086)
W/System.err(32424):    at android.app.Activity.performCreate(Activity.java:8074)
W/System.err(32424):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
W/System.err(32424):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
W/System.err(32424):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
W/System.err(32424):    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
W/System.err(32424):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
W/System.err(32424):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
W/System.err(32424):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
W/System.err(32424):    at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(32424):    at android.os.Looper.loop(Looper.java:213)
W/System.err(32424):    at android.app.ActivityThread.main(ActivityThread.java:8178)
W/System.err(32424):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(32424):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(32424):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
W/System.err(32424): java.lang.Exception: No dash options defined
W/System.err(32424):    at com.razorpay.CheckoutPresenterImpl.getProgressBarColor(CheckoutPresenterImpl.java:650)
W/System.err(32424):    at com.razorpay.BaseCheckoutActivity.createContainer(BaseCheckoutActivity.java:227)
W/System.err(32424):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:113)
W/System.err(32424):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:26)
W/System.err(32424):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(32424):    at android.app.Activity.performCreate(Activity.java:8086)
W/System.err(32424):    at android.app.Activity.performCreate(Activity.java:8074)
W/System.err(32424):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
W/System.err(32424):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
W/System.err(32424):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
W/System.err(32424):    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
W/System.err(32424):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
W/System.err(32424):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
W/System.err(32424):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
W/System.err(32424):    at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(32424):    at android.os.Looper.loop(Looper.java:213)
W/System.err(32424):    at android.app.ActivityThread.main(ActivityThread.java:8178)
W/System.err(32424):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(32424):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(32424):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
W/System.err(32424): org.json.JSONException: No value for theme
W/System.err(32424):    at org.json.JSONObject.get(JSONObject.java:399)
W/System.err(32424):    at org.json.JSONObject.getJSONObject(JSONObject.java:619)
W/System.err(32424):    at com.razorpay.CheckoutPresenterImpl.getProgressBarColor(CheckoutPresenterImpl.java:635)
W/System.err(32424):    at com.razorpay.BaseCheckoutActivity.createContainer(BaseCheckoutActivity.java:227)
W/System.err(32424):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:113)
W/System.err(32424):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:26)
W/System.err(32424):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(32424):    at android.app.Activity.performCreate(Activity.java:8086)
W/System.err(32424):    at android.app.Activity.performCreate(Activity.java:8074)
W/System.err(32424):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
W/System.err(32424):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
W/System.err(32424):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
W/System.err(32424):    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
W/System.err(32424):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
W/System.err(32424):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
W/System.err(32424):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
W/System.err(32424):    at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(32424):    at android.os.Looper.loop(Looper.java:213)
W/System.err(32424):    at android.app.ActivityThread.main(ActivityThread.java:8178)
W/System.err(32424):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(32424):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(32424):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
D/com.razorpay.checkout(32424): OTPElf Constructor
D/com.razorpay.checkout(32424): No permission for reading SMS
D/com.razorpay.checkout(32424): OTPElf Constructor
D/com.razorpay.checkout(32424): No permission for reading SMS
W/ood_deliveryap(32424): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
V/AudioManager(32424): isWiredHeadsetOn...
D/com.razorpay.checkout(32424): NOT FULLSCREEN
W/cr_media(32424): Requires BLUETOOTH permission
W/System.err(32424): java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
W/System.err(32424):    at android.app.ContextImpl.checkMode(ContextImpl.java:2806)
W/System.err(32424):    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:480)
W/System.err(32424):    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:470)
W/System.err(32424):    at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
W/System.err(32424):    at com.razorpay.SharedPreferenceUtil.getPublicPrefs(SharedPreferenceUtil.java:63)
W/System.err(32424):    at com.razorpay.CardSaving.getDeviceToken(CardSaving.java:265)
W/System.err(32424):    at com.razorpay.CardSaving.fetchDeviceTokenFromOtherAppsIfRequired(CardSaving.java:167)
W/System.err(32424):    at com.razorpay.CheckoutPresenterImpl.handleCardSaving(CheckoutPresenterImpl.java:406)
W/System.err(32424):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:152)
W/System.err(32424):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:26)
W/System.err(32424):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(32424):    at android.app.Activity.performCreate(Activity.java:8086)
W/System.err(32424):    at android.app.Activity.performCreate(Activity.java:8074)
W/System.err(32424):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
W/System.err(32424):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
W/System.err(32424):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
W/System.err(32424):    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
W/System.err(32424):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
W/System.err(32424):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
W/System.err(32424):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
W/System.err(32424):    at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(32424):    at android.os.Looper.loop(Looper.java:213)
W/System.err(32424):    at android.app.ActivityThread.main(ActivityThread.java:8178)
W/System.err(32424):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(32424):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(32424):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
D/ActivityThread(32424): add activity client record, r= ActivityRecord{6b8ee21 token=android.os.BinderProxy@1436814 {com.foodizzoapp.food_deliveryapp/com.razorpay.CheckoutActivity}} token= android.os.BinderProxy@1436814
D/HiTouch_PressGestureDetector(32424): onAttached, package=com.foodizzoapp.food_deliveryapp, windowType=1, mHiTouchRestricted=false
D/mali_winsys(32424): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
W/VideoCapabilities(32424): Unrecognized profile/level 0/0 for video/mpeg2
W/VideoCapabilities(32424): Unrecognized profile/level 0/2 for video/mpeg2
W/VideoCapabilities(32424): Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities(32424): Unsupported profile 5 for video/mpeg2
I/chatty  (32424): uid=10295(com.foodizzoapp.food_deliveryapp) Chrome_InProcGp identical 2 lines
I/VideoCapabilities(32424): Unsupported profile 5 for video/mpeg2
W/VideoCapabilities(32424): Unrecognized profile/level 1/32 for video/mp4v-es
W/VideoCapabilities(32424): Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities(32424): Unrecognized profile/level 32768/64 for video/mp4v-es
W/cr_MediaCodecUtil(32424): HW encoder for video/avc is not available on this device.
I/HwViewRootImpl(32424): removeInvalidNode all the node in jank list is out of time
D/com.razorpay.checkout(32424): Updating OTPElf
W/libEGL  (32424): EGLNativeWindowType 0x7c8fb8e010 disconnect failed
W/libEGL  (32424): EGLNativeWindowType 0x7ceee23210 disconnect failed
D/com.razorpay.checkout(32424): Updating OTPElf
D/com.razorpay.checkout(32424): RzpAssist onPageStarted: https://api.razorpay.com/v1/checkout/public?version=1.6.10&library=checkoutjs&platform=android
D/HiTouch_PressGestureDetector(32424): onAttached, package=com.foodizzoapp.food_deliveryapp, windowType=2, mHiTouchRestricted=false
D/mali_winsys(32424): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
W/System.err(32424): java.lang.IllegalArgumentException: bad base-64
W/System.err(32424):    at android.util.Base64.decode(Base64.java:162)
W/System.err(32424):    at android.util.Base64.decode(Base64.java:137)
W/System.err(32424):    at com.razorpay.CryptLib.encryptDecrypt(CryptLib.java:174)
W/System.err(32424):    at com.razorpay.CryptLib.decrypt(CryptLib.java:269)
W/System.err(32424):    at com.razorpay.BaseUtils.decryptFile(BaseUtils.java:719)
W/System.err(32424):    at com.razorpay.OtpElfData$2.run(OtpElfData.java:55)
W/System.err(32424):    at com.razorpay.Owl.onPostExecute(Owl.java:137)
W/System.err(32424):    at com.razorpay.Owl.onPostExecute(Owl.java:23)
W/System.err(32424):    at android.os.AsyncTask.finish(AsyncTask.java:755)
W/System.err(32424):    at android.os.AsyncTask.access$900(AsyncTask.java:192)
W/System.err(32424):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
W/System.err(32424):    at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(32424):    at android.os.Looper.loop(Looper.java:213)
W/System.err(32424):    at android.app.ActivityThread.main(ActivityThread.java:8178)
W/System.err(32424):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(32424):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(32424):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
D/com.razorpay.checkout(32424): Unable to decrypt file, bad base-64
W/System.err(32424): java.lang.IllegalArgumentException: bad base-64
W/System.err(32424):    at android.util.Base64.decode(Base64.java:162)
W/System.err(32424):    at android.util.Base64.decode(Base64.java:137)
W/System.err(32424):    at com.razorpay.CryptLib.encryptDecrypt(CryptLib.java:174)
W/System.err(32424):    at com.razorpay.CryptLib.decrypt(CryptLib.java:269)
W/System.err(32424):    at com.razorpay.BaseUtils.decryptFile(BaseUtils.java:719)
W/System.err(32424):    at com.razorpay.OtpElfData$2.run(OtpElfData.java:55)
W/System.err(32424):    at com.razorpay.Owl.onPostExecute(Owl.java:137)
W/System.err(32424):    at com.razorpay.Owl.onPostExecute(Owl.java:23)
W/System.err(32424):    at android.os.AsyncTask.finish(AsyncTask.java:755)
W/System.err(32424):    at android.os.AsyncTask.access$900(AsyncTask.java:192)
W/System.err(32424):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
W/System.err(32424):    at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(32424):    at android.os.Looper.loop(Looper.java:213)
W/System.err(32424):    at android.app.ActivityThread.main(ActivityThread.java:8178)
W/System.err(32424):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(32424):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(32424):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
D/com.razorpay.checkout(32424): Unable to decrypt file, bad base-64
I/ood_deliveryap(32424): Background concurrent copying GC freed 88927(5342KB) AllocSpace objects, 67(4412KB) LOS objects, 52% free, 5578KB/11MB, paused 350us total 112.413ms
W/ood_deliveryap(32424): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, linking, allowed)
W/System.err(32424): java.lang.IllegalArgumentException: bad base-64
W/System.err(32424):    at android.util.Base64.decode(Base64.java:162)
W/System.err(32424):    at android.util.Base64.decode(Base64.java:137)
W/System.err(32424):    at com.razorpay.CryptLib.encryptDecrypt(CryptLib.java:174)
W/System.err(32424):    at com.razorpay.CryptLib.decrypt(CryptLib.java:269)
W/System.err(32424):    at com.razorpay.BaseUtils.decryptFile(BaseUtils.java:719)
W/System.err(32424):    at com.razorpay.MagicData$2.run(MagicData.java:41)
W/System.err(32424):    at com.razorpay.Owl.onPostExecute(Owl.java:137)
W/System.err(32424):    at com.razorpay.Owl.onPostExecute(Owl.java:23)
W/System.err(32424):    at android.os.AsyncTask.finish(AsyncTask.java:755)
W/System.err(32424):    at android.os.AsyncTask.access$900(AsyncTask.java:192)
W/System.err(32424):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
W/System.err(32424):    at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(32424):    at android.os.Looper.loop(Looper.java:213)
W/System.err(32424):    at android.app.ActivityThread.main(ActivityThread.java:8178)
W/System.err(32424):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(32424):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(32424):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
D/com.razorpay.checkout(32424): Unable to decrypt file, bad base-64
D/HwGalleryCacheManagerImpl(32424): mIsEffect:false
D/BitmapFactory(32424): sampleSize 1, isHardware 0, isMutable 0, prefColorType 4, requireUnpremultiplied 0
D/skia    (32424): --- Failed to create image decoder with message 'unimplemented'
D/BitmapFactory(32424): sampleSize 1, isHardware 0, isMutable 0, prefColorType 4, requireUnpremultiplied 0
D/skia    (32424): --- Failed to create image decoder with message 'unimplemented'
W/libEGL  (32424): EGLNativeWindowType 0x7ce0901bd0 disconnect failed
D/com.razorpay.checkout(32424): Checkout loaded in 3.58 sec.
D/com.razorpay.checkout(32424): not magic
E/com.razorpay.checkout(32424): Webview JS Error: Uncaught SyntaxError: Invalid or unexpected token
I/chromium(32424): [INFO:CONSOLE(1)] "Uncaught SyntaxError: Invalid or unexpected token", source: https://api.razorpay.com/v1/checkout/public?version=1.6.10&library=checkoutjs&platform=android (1)
E/com.razorpay.checkout(32424): Webview JS Error: Uncaught TypeError: window.getDeviceDetails is not a function
I/chromium(32424): [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.6.10&library=checkoutjs&platform=android (1)
W/ood_deliveryap(32424): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)
I/OpenGLRenderer(32424): Davey! duration=1168ms; Flags=0, IntendedVsync=49267241744164, Vsync=49267241744164, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=49267242430502, AnimationStart=49267242519044, PerformTraversalsStart=49267245319044, DrawStart=49267245632065, SyncQueued=49267246679982, SyncStart=49267249288836, IssueDrawCommandsStart=49267249459669, SwapBuffers=49268410858106, FrameCompleted=49268412683627, DequeueBufferDuration=423000, QueueBufferDuration=1339000, 
I/Choreographer(32424): Skipped 68 frames!  The application may be doing too much work on its main thread.
I/HwViewRootImpl(32424): removeInvalidNode jank list is null
I/OpenGLRenderer(32424): Davey! duration=1185ms; Flags=0, IntendedVsync=49267275057986, Vsync=49268408391274, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=49268417926336, AnimationStart=49268418016440, PerformTraversalsStart=49268425517481, DrawStart=49268425924252, SyncQueued=49268427633106, SyncStart=49268620765398, IssueDrawCommandsStart=49268620931023, SwapBuffers=49268651457586, FrameCompleted=49268653638836, DequeueBufferDuration=134000, QueueBufferDuration=903000, 
W/Settings(32424): Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
V/HiTouch_HiTouchSensor(32424): User setup is finished.
W/System.err(32424): org.json.JSONException: No value for order_id
W/System.err(32424):    at org.json.JSONObject.get(JSONObject.java:399)
W/System.err(32424):    at com.razorpay.Lumberjack.getValueFromJsonObject(Lumberjack.java:423)
W/System.err(32424):    at com.razorpay.Lumberjack.addPropertyFromJSONObject(Lumberjack.java:407)
W/System.err(32424):    at com.razorpay.Lumberjack.addFilteredPropertiesFromPayload(Lumberjack.java:463)
W/System.err(32424):    at com.razorpay.AnalyticsUtil.addFilteredPropertiesFromPayload(AnalyticsUtil.java:108)
W/System.err(32424):    at com.razorpay.CheckoutPresenterImpl.addAnalyticsData(CheckoutPresenterImpl.java:923)
W/System.err(32424):    at com.razorpay.OtpElfCheckoutPresenterImpl.addAnalyticsData(OtpElfCheckoutPresenterImpl.java:171)
W/System.err(32424):    at com.razorpay.CheckoutPresenterImpl.onSubmit(CheckoutPresenterImpl.java:946)
W/System.err(32424):    at com.razorpay.CheckoutBridge$10.secure(CheckoutBridge.java:158)
W/System.err(32424):    at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1257)
W/System.err(32424):    at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:49)
W/System.err(32424):    at com.razorpay.CheckoutPresenterImpl$17.run(CheckoutPresenterImpl.java:1243)
W/System.err(32424):    at android.os.Handler.handleCallback(Handler.java:888)
W/System.err(32424):    at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err(32424):    at android.os.Looper.loop(Looper.java:213)
W/System.err(32424):    at android.app.ActivityThread.main(ActivityThread.java:8178)
W/System.err(32424):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(32424):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(32424):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)`

and when i click on gpay this will print and the device is getting dissconected 
`D/com.razorpay.checkout(32424): Sending data to lumberjack
D/com.razorpay.checkout(32424): Response from lumberjack: 
W/libEGL  (32424): EGLNativeWindowType 0x7ceee20650 disconnect failed
Lost connection to device.
`

**Comment by wishnuprathikantam** [comment]
I've a similar issue using GPay or PhonePe. The api seems to be returning payment as success even when I've cancelled it after opening the Gpay app. Any help is appreciated.

The SDK seems to be returning success for wallet payments even when there is a failure. Here is the log output 
D/com.razorpay.checkout( 9162)
..."payment_id":"pay_HggmAmUvBCMyf6","payment_status":"success","flow":"intent","destroy_resultCode":"1","payment_attempt":1,"amount":16000,"framework":"flutter","OTPElf Version":"",...

**Comment by sumedht** [comment]
@anasnaji25 Wanted to know more on this. Is this with GPay only & working fine with other payment methods?

**Comment by harshmsomani** [comment]
Were you able to solve this issue?

**Comment by dishank-betaflux** [comment]
@anasnaji25 did you found any resolution for this? can you update the status of this ticket?

**Comment by anasnaji25** [comment]
didn't found any solutions , so we changed the payment gateway

**Comment by anasnaji25** [comment]
didn't found any solutions , so we changed the payment gateway

**Comment by Soorya-S** [comment]
+1
