### ISSUE TITLE
Payment Failed - Unexpected Error

### ISSUE THREAD

**Issue by rkumar1904** [razorpay/razorpay-flutter#188]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay Flutter plugin release to make sure your issue has not already been fixed: 

## Flutter Version : Flutter 2.0.1
Run `flutter version` in your terminal and copy the results here.

## Xcode Version : Version 12.5.1
Open Xcode > Go to `About Xcode` > copy the Xcode version here.

## Cocoapod Version : razorpay-pod (1.1.14) and razorpay_flutter (1.1.10)
Go to iOS folder > open `podfile.lock` > copy the `razorpay-pod version` and `razorpay_flutter`a version.

Issue:: after calling  _razorpay.open(options);

Error: "**Payment Failed - Unexpected Error**"

**Comment by Imgkl** [comment]
@rkumar1904 what fixed it?
