### ISSUE TITLE
Rozar pay not working well with android 11 

### ISSUE THREAD

**Issue by sanjay12340** [razorpay/razorpay-flutter#189]
It work fine up to android 10 , but in android 11 not show app installed in system and generate request via UPI id and then as request generated by app go to phonepe , google pay , paytm or there based on request generated. 

This is wearied thing no one go this long stap method please provide for android 11

**Comment by sumedht** [comment]
@sanjay12340 U need to add some extra lines in Manifest file as given below
https://razorpay.com/docs/payment-gateway/android-integration/custom/payment-methods/#intent-flow
