### ISSUE TITLE
Production mode is not working after adding progaurd rule 

### ISSUE THREAD

**Issue by rohan220217** [razorpay/razorpay-flutter#190]
## Description
Whenever I build my flutter app using flutter build apk it is showing 
Mypath\FlutterFolder\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

I have downloaded the demo project from razorpay repo and still showing the same error.

## Flutter Version :
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1110], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.59.0)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. I run build command-  flutter build apk 
2. App crashes if somehow I able to get the build apk

## Expected Results
I want razorpay to build properly when I run the production command

## Snack, code example, screenshot, or link to a repository:

![image](https://user-images.githubusercontent.com/51409281/128814818-6f31c111-90fa-48aa-8877-a654ecfe0e10.png)

**Comment by rohan220217** [comment]
![image](https://user-images.githubusercontent.com/51409281/128816752-1d1425bf-0d95-4b67-b4c5-49612a805b01.png)

**Comment by rohan220217** [comment]
I fix this issue by changing my build.gradle but after building my apk my razorpay page is blank

**Comment by sumedht** [comment]
@rohan220217 Trying on an emulator or real device?

**Comment by rohan220217** [comment]
real device the button is not working

**Comment by rohan220217** [comment]
I solved my issue using debugging I got an error on my page that's why in production mode it is showing a grey screen
