### ISSUE TITLE
module 'Razorpay' was created for incompatible target arm64-apple-ios10.0

### ISSUE THREAD

**Issue by sajanyamaha** [razorpay/razorpay-flutter#197]
## Description
The ios build fais with this error ,
```
/Users/xxx/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.7/ios/Classes/RazorpayDelegate.swift:2:8: error: module 'Razorpay' was created for incompatible target arm64-apple-ios10.0: /Users/xxx/StudioProjects/xxx/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/arm64.swiftmodule
    import Razorpay
           ^
    /Users/xxx/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.7/ios/Classes/RazorpayDelegate.swift:2:8: error: module 'Razorpay' was created for incompatible target arm64-apple-ios10.0: /Users/xxx/StudioProjects/inhouse/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/arm64.swiftmodule
    import Razorpay
           ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
```

## Flutter Version :
 version 2.5.0

## Xcode Version :
Version 12.5.1 (12E507)

## Cocoapod Version :
razorpay-pod (1.1.16)
- razorpay_flutter (1.1.10):
    - Flutter
    - razorpay-pod

**Comment by amitkhairnar44** [comment]
@sajanyamaha Add this in the project's Podfile:
```
installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
end
```

Just before this line: `installer.pods_project.targets.each do |target|`

**Comment by venkata-reddy-boya** [comment]
@amitkhairnar44  i had tried your solution. but  it didn't worked .

**Comment by amitkhairnar44** [comment]
@venkata-reddy-boya Have you configured build flavours in your project?

**Comment by venkata-reddy-boya** [comment]
@amitkhairnar44  no

**Comment by sajanyamaha** [comment]
for me this worked , change these settings in Xcode ,

1. Delete DerivedData folder from Xcode-->Preferences 

<img width="567" alt="Screenshot 2021-09-18 at 7 25 38 PM" src="https://user-images.githubusercontent.com/6435237/133891297-73372c75-9ead-49e6-a488-774e91f2d5a5.png">

2. Change these to arm64
<img width="570" alt="Screenshot 2021-09-18 at 7 20 50 PM" src="https://user-images.githubusercontent.com/6435237/133891165-db1f59a4-14fc-42a0-ac08-791fb31e614e.png">

**Comment by amitkhairnar44** [comment]
> for me this worked , change these settings in Xcode ,
> 
> 
> 
> 1. Delete DerivedData folder from Xcode-->Preferences 
> 
> 
> 
> <img width="567" alt="Screenshot 2021-09-18 at 7 25 38 PM" src="https://user-images.githubusercontent.com/6435237/133891297-73372c75-9ead-49e6-a488-774e91f2d5a5.png">
> 
> 
> 
> 2. Change these to arm64
> 
> <img width="570" alt="Screenshot 2021-09-18 at 7 20 50 PM" src="https://user-images.githubusercontent.com/6435237/133891165-db1f59a4-14fc-42a0-ac08-791fb31e614e.png">
> 
> 
> 
> 

@sajanyamaha Yes, I forgot to mention the 2nd part 😅

You can close this issue now.

**Comment by LOG-TAG** [comment]
https://www.youtube.com/watch?v=leni4BsbfHs still were getting this error after doing this also, if run via xcode it application runs, android studio it fails with above mentioned error

**Comment by satishsoni777** [comment]
Thanks  @amitkhairnar44 worked for me,
