### ISSUE TITLE
No appropriate payment method found

### ISSUE THREAD

**Issue by ib-8** [razorpay/razorpay-flutter#207]
Payment Failed
Error message is "No appropriate payment method found"

Here's the Checkout options

var options = {
      'key': 'razr_test_key',
      'amount': 50000,
      'name': 'Acme Corp.',
      'description': 'Fine T-Shirt',
      'order_id': result['id'],
      "currency": "INR",
      'timeout': 60,
      'prefill': {
        'contact': '8888888888',
        'email': 'test@razorpay.com',
      },
    };

    try {
      _razorpay.open(options);
    } catch (e) {
      debugPrint('Error: e');
    }

If I add 

 'external': {
        'wallets': ['paytm']
      }

to the checkout option it shows only paytm wallet option 

Don't know what's causing the issue.

**Comment by SanketPrograms** [comment]
> Payment Failed Error message is "No appropriate payment method found"
> 
> Here's the Checkout options
> 
> var options = { 'key': 'razr_test_key', 'amount': 50000, 'name': 'Acme Corp.', 'description': 'Fine T-Shirt', 'order_id': result['id'], "currency": "INR", 'timeout': 60, 'prefill': { 'contact': '8888888888', 'email': '[test@razorpay.com](mailto:test@razorpay.com)', }, };
> 
> ```
> try {
>   _razorpay.open(options);
> } catch (e) {
>   debugPrint('Error: e');
> }
> ```
> 
> If I add
> 
> 'external': { 'wallets': ['paytm'] }
> 
> to the checkout option it shows only paytm wallet option
> 
> Don't know what's causing the issue.

Bro Just use the proper razorpay test key, you will get all wallets options

**Comment by AnmolkumarShah** [comment]
Even I am facing the same issue, bro please tell me whether you find the answer or not

**Comment by ib-8** [comment]
I got the error because of the wrong keys. It got solved when I used the right keys

**Comment by Kumarsatwik** [comment]
> I got the error because of the wrong keys. It got solved when I used the right keys.

i didn't get it
.Could you tell me briefly how you solved?

**Comment by SanketPrograms** [comment]
For the integration of razorpay we use the key, which is generated when we
create a razorpay account soo use that key it solve this issue

**Comment by vidhanshu** [comment]
I have give the appropriate key, even I'm getting 200 response 
![image](https://github.com/razorpay/razorpay-flutter/assets/84308141/9f4c2dfc-225a-4864-9f89-6147e159934d)

But post that, I'm receiving an alert saying
![image](https://github.com/razorpay/razorpay-flutter/assets/84308141/5beb6ded-6a70-458b-a139-3e9f221b8a95)

**Comment by sumitdigiflux** [comment]
hey did you find the solution to this issue?? 

I am facing the same issue
