### ISSUE TITLE
Failed to build module : compiler version issue

### ISSUE THREAD

**Issue by setu-dev** [razorpay/razorpay-flutter#209]
Getting this error after Moving to Null safety with latest version of Razorpay. 

## Description
Failed to build module 'Razorpay' from its module interface; the compiler that produced it, 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)'

## Flutter Version :
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (8 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

## Xcode Version :
Version 12.5 (12E262)

## Cocoapod Version :
  - razorpay-pod (1.1.17)
  - razorpay_flutter (1.1.10)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. upgraded to null safety 
2. upgraded Razorpay version

## Note
I'm skeptical about upgrading my Xcode & swift version as it may break other working libraries/code.

**Comment by sanjaymajoka** [comment]
Facing Same Issue 


Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (8 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

razorpay_flutter: ^1.2.7

**Comment by setu-dev** [comment]
upgraded to xcode 13.1 and it got resolved
