### ISSUE TITLE
RazorPay Screen hangs

### ISSUE THREAD

**Issue by adarshahd** [razorpay/razorpay-flutter#21]
Dear Team,

Congratulations and thank you very much for the much needed library for flutter. We are currently integrating this library with our application, which we are soon planning to take it to production.

However we are facing an issue where the RazorPay activity hangs (screenshot attached) with below workflow.

Tested on Emulator (Google Pixel 3, API 28)

1. Open RazoryPay payment screen
2. Select Netbanking -> HDFC bank -> Pay
3. In the success/failure screen, press **back button**
4. Close the RazorPay payment screen.
5. Reopen the RazorPay payment screen.
6. Payment screen hangs and do not even close with back button.

Log:
```
I/chromium(  777): [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'track' of undefined", source: https://checkout.razorpay.com/v1/checkout-frame.js (1)
I/chromium(  777): [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'r' of undefined", source: https://checkout.razorpay.com/v1/checkout-frame.js (1)
```

Please note I tested the same on a real device, it works neatly. However I still wanted to bring this to your attention, so that if anything wrong, it could be fixed.

Please let me know if you need any more details.

Regards,
Adarsha HD

**Comment by adarshahd** [comment]
![RazorPay_hang](https://user-images.githubusercontent.com/722143/60360664-d9b5fd80-99f9-11e9-9c47-ea901a45c992.png)

**Comment by ChintanAcharya** [comment]
Thanks for reporting! We are looking into the issue and will get back to you as soon as we have an update.

**Comment by bihanikeshav** [comment]
I am facing a similar issue but in my case, it freezes sometimes after pressing the backbutton. Same grey screen and slightly different log

> `I/chromium(32064): [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'tab' of undefined", source: https://checkout.razorpay.com/v1/checkout-frame.js (1)
I/chromium(32064): [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'r' of undefined", source: https://checkout.razorpay.com/v1/checkout-frame.js (1)`

**Comment by rahuldange09** [comment]
Same issue here.
Started facing today.
I never faced this before.

`I/chromium(13723): [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'tab' of undefined", source: https://checkout.razorpay.com/v1/checkout-frame.js (1)`

**Comment by sendtomitesh** [comment]
same we are also facing.

**Comment by sumedht** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by venn710** [comment]
Having the same issue for a while now anyone got it?

**Comment by venn710** [comment]
I don't think it was solved.

**Comment by Abhijit-007a** [comment]
Facing the same issue with Razorpay

Logs:

E/com.razorpay.checkout(15392): Webview JS Error: Uncaught TypeError: Cannot read property 'r' of undefined
I/chromium(15392): [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'r' of undefined", source: https://checkout.razorpay.com/v1/checkout-frame.js 

1.Open RazoryPay payment screen
2.Select Netbanking -> HDFC bank -> Pay
3.In the success/failure screen, press back button
4.Close the RazorPay payment screen.
5.Reopen the RazorPay payment screen.
6.Payment screen hangs and do not even close with back button.

This is the exact thing that is happening @ChintanAcharya
