### ISSUE TITLE
How to disable Pay-Later payment method?

### ISSUE THREAD

**Issue by bharat8** [razorpay/razorpay-flutter#210]
## Description
I am trying to disable the Pay-Later in RazorPay Payment Screen but haven't succeeded yet.

## Flutter Version :
Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (3 months ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0

## Steps To Reproduce
Tried to disable it by following the steps in the link :-
[https://razorpay.com/docs/payment-links/api/new/advanced-options/customize/payment-methods/](https://razorpay.com/docs/payment-links/api/new/advanced-options/customize/payment-methods/)

## Expected Results
Pay-Later should not be visible when redirecting to payment

## Snack, code example, screenshot, or link to a repository:
Please refer to this sample code :-

```
var options = {
          'key': razorPayKey,
          'amount': amount.
          'name': 'Deposit',
          'description': 'Payment',
          'currency': currency,
          'prefill': {'contact': phone ?? '', 'email': email ?? ''},
          "method": {
            "netbanking": true,
            "card": true,
            "upi": true,
            "wallet": false,
            "emi": false,
            "paylater": false
          }
        }
_razorpay.open(options);
```

**Comment by abbas2501** [comment]
facing the same issue, any help ?
