### ISSUE TITLE
error: failed to build module 'Razorpay' from its module interface; the compiler that produced it, 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)'

### ISSUE THREAD

**Issue by sanjaymajoka** [razorpay/razorpay-flutter#211]
Facing issue to build my app for iOS only.

## Description
I am facing error while building iOS App. Issue is realted to razorpay flutter SDK because if I remove this SDK from my pubspec.yaml then my App build successfully.

## Flutter Version :
razorpay_flutter: ^1.2.7

## Xcode Version :
Xcode: 13.1

## Mac
M1 Chip

## Cocoapod Version :
razorpay-pod (1.1.17)
razorpay_flutter (1.1.10):
    - Flutter
    - razorpay-pod

## Steps To Reproduce
Comes If we use razorpay_flutter:1.2.7 sdk

## Logs
Xcode build done.                                            3.2s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[12583]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x21e7c3130) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1109e02c8). One of the two will be used. Which one is undefined.
    objc[12583]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x21e7c3180) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1109e0318). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/a/Desktop/workspace/mobile/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:12:8: error: no such module '_Concurrency'
    import _Concurrency
           ^
    /Users/a/Desktop/softwares/flutter2/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.7/ios/Classes/RazorpayDelegate.swift:2:8: error: failed to build module 'Razorpay' from its module interface; the compiler that produced it, 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)'
    import Razorpay
           ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

**Comment by prathmeshbijjargi** [comment]
Hi Sanjay,

Our SDK is compiled at swift 5.5, this is the cause of the issue.
Swift 5.5 has more advanced features like _Concurrency as you are using a lower version of Swift version 5.4.2.
Kindly request you to update the swift version and clean build and run the application.

**Comment by sanjaymajoka** [comment]
Hi Prathmesh,

Thanks for reply. But we already using this in our pod file. 

below is the code in my pod file:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      # config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',

            ## dart: PermissionGroup.calendar
            # 'PERMISSION_EVENTS=1',

            ## dart: PermissionGroup.reminders
            # 'PERMISSION_REMINDERS=1',

            ## dart: PermissionGroup.contacts
            # 'PERMISSION_CONTACTS=1',

            ## dart: PermissionGroup.camera
             'PERMISSION_CAMERA=1',

            ## dart: PermissionGroup.microphone
             'PERMISSION_MICROPHONE=1',

            ## dart: PermissionGroup.speech
            # 'PERMISSION_SPEECH_RECOGNIZER=1',

            ## dart: PermissionGroup.photos
            # 'PERMISSION_PHOTOS=1',

            ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
             'PERMISSION_LOCATION=1',

            ## dart: PermissionGroup.notification
            # 'PERMISSION_NOTIFICATIONS=1',

            ## dart: PermissionGroup.mediaLibrary
            # 'PERMISSION_MEDIA_LIBRARY=1',

            ## dart: PermissionGroup.sensors
            # 'PERMISSION_SENSORS=1',

            ## dart: PermissionGroup.bluetooth
            # 'PERMISSION_BLUETOOTH=1',

            ## dart: PermissionGroup.appTrackingTransparency
            # 'PERMISSION_APP_TRACKING_TRANSPARENCY=1',

            ## dart: PermissionGroup.criticalAlerts
            # 'PERMISSION_CRITICAL_ALERTS=1'
        ]
    end
  end
end
```

I also tried with 
```
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
config.build_settings['SWIFT_VERSION'] = '5.5.1'
```
But result is same with error.

**Note** : If I check swift version in my mac using `swift --version` then it show `5.4.2`.

**Comment by sanjaymajoka** [comment]
Hi Issue is Fixed Now.

As I already installed xcode 13.1 (direct download , Not form App Store) and Update Mac OS. But I didn't removed my old xcode from application which had swift 5.4. After removing old xcode from my mac Every thing worked successfully.

Note: xcode 13.1 comes with swift version 5.5.1
