### ISSUE TITLE
Payment SDK crashes on Android

### ISSUE THREAD

**Issue by RishabhDhiman** [razorpay/razorpay-flutter#215]
While opening the Razorpay SDK from Android the SDK crases for the first time and subsequent SDK calls are successful. I'm getting "java.lang.NullPointerException: println needs a message" this exception.

**Comment by vivekshindhe** [comment]
@RishabhDhiman that points that the key isn't being set properly. Could you please send the payload that you are using? Redact the key value.

**Comment by RishabhDhiman** [comment]
For failed case

{"name":"Pustakey","description":"985431950099555","order_id":"order_IXHcmHdJPY9Qks","currency":"INR","amount":850000,"prefill.email":"testingdemon123@gmail.com","prefill.contact":"testingdem"}

Foe success case

{"name":"Pustakey","description":"851063258661703","order_id":"order_IXHdXGQ87WKjpp","currency":"INR","amount":850000,"prefill.email":"testingdemon123@gmail.com","prefill.contact":"testingdem"}

**Comment by RishabhDhiman** [comment]
The issue is fixed there was some problem with the checkout object initialization.

**Comment by RishabhDhiman** [comment]
The issue is fixed there was some problem with the checkout object initialization.
