### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 160905** [razorpay/razorpay-flutter#22]
![企业微信20190710055141](https://user-images.githubusercontent.com/22002759/60959829-7736f880-a33b-11e9-9ddb-90cfaf33717d.png)

I had these problems

**Comment by ChintanAcharya** [comment]
@160905 We export a class `Razorpay` from `package:razorpay_flutter/razorpay_flutter.dart`. Are you redeclaring the `Razorpay` class in your code?

**Comment by 160905** [comment]
I solved this problem, thank you

**Comment by umanghome** [comment]
@160905 How did you solve this?
