### ISSUE TITLE
Provide support for latest xcode 13 & flutter 2.8

### ISSUE THREAD

**Issue by graphionic** [razorpay/razorpay-flutter#220]
Please provide support for the new xcode 13. My working app is stopped 
Because of updating xcode and flutter please make it compatible with latest versions.

**Comment by ramprasadAnand** [comment]
Hi @graphionic, we apologise for the inconvenience. We are not facing any problem on Xcode 13,  can you please share the the latest **flutter** version and **razorpay_flutter** SDK version you are using ?

**Comment by graphionic** [comment]
@ramprasadAnand 

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-IN)
    • Flutter version 2.8.1 at /Users/graphionic/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (2 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/graphionic/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • 5D6C8782-C616-43CF-8EED-F043769C05F8 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.

############
Dependency 

  razorpay_flutter: ^1.1.2

##########
Please let me know what i am doing wrong with configurations. it will be very helpful.

<img width="1475" alt="Screenshot 2021-12-30 at 11 35 36 AM" src="https://user-images.githubusercontent.com/38457965/147726079-db22e83b-184e-4701-b18d-07844e68afe0.png">

**Comment by ramprasadAnand** [comment]
Hi @graphionic, our latest **razorpay_flutter** version is `1.2.7`, Can you please upgrade to this version and check ?

**Comment by graphionic** [comment]
@ramprasadAnand 
Done,
But Still No Luck.
Got Same Error As Above

<img width="1146" alt="Screenshot 2021-12-30 at 1 15 39 PM" src="https://user-images.githubusercontent.com/38457965/147731753-0c6f1ff0-23ca-4f6f-82a7-591bd089ddb0.png">

**Comment by ramprasadAnand** [comment]
If you are running on simulator, can you add below lines of code in Podfile and do the pod install and run ?

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
```

**Comment by graphionic** [comment]
@ramprasadAnand 

It Worked !! Thanks Alot !!

Before This Code In Podfile My Code Was As Below

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # solves flutter The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0,
    # but the range of supported deployment target versions is 9.0
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    flutter_additional_ios_build_settings(target)
  end
end

Please Let Me know What was the issue in my previous code ?

**Comment by ramprasadAnand** [comment]
In the old code the pod config was not getting set. Closing this issue as it got resolved.
