### ISSUE TITLE
Razorpay integration issue both android and iOS in razorpay_flutter 1.2.7

### ISSUE THREAD

**Issue by SuseeRaja** [razorpay/razorpay-flutter#228]
AndroidManifest.xml Error:
	Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by pr-1** [comment]
Facing same issue And I checked theMerged Generated manifest file. Razorpay is missing the `android:exported`  value.

```
<activity
            android:name="com.razorpay.CheckoutActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:label="Razorpay Checkout"
            android:theme="@style/CheckoutTheme" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <data
                    android:host="rzp.io"
                    android:scheme="io.rzp" />
            </intent-filter>
        </activity>
```

**Comment by pr-1** [comment]
@sumedht Please have a look at this and the pr i created. Let me know if it needs any change.
