### ISSUE TITLE
Success or Failure Screen after payment barely shows for 200 milliseconds

### ISSUE THREAD

**Issue by adityar224** [razorpay/razorpay-flutter#238]
## Description
The Screen after payment indicating whether it's a success or a failure does not stay for more than 200 milliseconds. Kinda looks janky and too quick.

## Flutter Version :
Flutter 2.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5f105a6ca7 (13 days ago) • 2022-02-01 14:15:42 -0800
Engine • revision 776efd2034
Tools • Dart 2.16.0 • DevTools 2.9.2

## Android Studio Details :
Android Studio Bumblebee | 2021.1.1 Patch 1
Build #AI-211.7628.21.2111.8139111, built on February 2, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 16
Registry: external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (36.0), Dart (211.7798), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), io.flutter (64.1.2), com.chrisrm.idea.MaterialThemeUI (6.7.2), org.intellij.plugins.markdown (211.7142.37)

## Steps To Reproduce
Following the basic example from your documentation reproduces this issue.

## Expected Results
The ability to control (for eg using the Duration() class) the time for which the success or failure screen is displayed. The default time for which it is displayed should be longer. Right now it is too quick and janky.

**Comment by vivekshindhe** [comment]
@adityar224 We will consider this as an improvement. The whole reason for the janky movement is confirmation for the user, plus the same can be shown by the application after getting the response in either onPaymentSuccess or onPaymentFailure
