### ISSUE TITLE
Crash : Fatal Exception: java.lang.RuntimeException Unable to start activity ComponentInfo{com.joveemart.demostore.apps.buyer/com.razorpay.CheckoutActivity}: java.lang.NullPointerException

### ISSUE THREAD

**Issue by VigneshkumarM** [razorpay/razorpay-flutter#245]
I used razorpay_flutter 1.3.0, When I try to call open() method app crashes with below error :

android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3835)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4011)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:85)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2325)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:246)
android.app.ActivityThread.main (ActivityThread.java:8633)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

## Flutter doctor
[✓] Flutter (Channel stable, 2.10.1, on Ubuntu 18.04.4 LTS 4.15.0-162-generic, locale en_IN)
    • Flutter version 2.10.1 at /home/prandex-and-05/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (8 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /home/prandex-and-05/Android/Sdk
    • Platform android-32, build-tools 33.0.0-rc2
    • Java binary at: /home/prandex-and-05/android-studio-2021.1.1.22/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/prandex-and-05/android-studio-2021.1.1.22/android-studio
    • Flutter plugin version 66.0.1
    • Dart plugin version 211.7811
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (3 available)
    • SM M215F (mobile) • adb-RZ8N70Z1S1T-2wu7qc._adb-tls-connect._tcp • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux                                        • linux-x64      • Ubuntu 18.04.4 LTS 4.15.0-162-generic
    • Chrome (web)      • chrome                                       • web-javascript • Google Chrome 81.0.4044.138

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by vivekshindhe** [comment]
Hey @VigneshkumarM. I just tested this. And seems to be working fine for me. Could you please send the payload that you are sending to the SDK?

**Comment by VigneshkumarM** [comment]
@vivekshindhe Below payload i sent in SDK

{"key":"RAZOR_PAY_KEY","amount":1000,"name":"demo store","order_id":"ORDER_ID","description":"Fine T-Shirt","prefill":{"contact":"1212121212","email":"customer@demostore.in"}}

**Comment by vivekshindhe** [comment]
@VigneshkumarM I'm assuming you have added the correct proguard rules for release build?

**Comment by VigneshkumarM** [comment]
Thanks @vivekshindhe. I missed that proguard file. Now its working fine.
