### ISSUE TITLE
Facing this issue, the same issue has been addressed for android, Proposed solution was to make the maximum app icon size to be 512 * 512 ,How it is related to this error and how do i impliment this for flutter

### ISSUE THREAD

**Issue by omkarChend1kar** [razorpay/razorpay-flutter#246]
E/com.razorpay.checkout(31190): Webview JS Error: Uncaught SyntaxError: Invalid or unexpected token
I/chromium(31190): [INFO:CONSOLE(1)] "Uncaught SyntaxError: Invalid or unexpected token", source: [https://api.razorpay.com/v1/checkout/public?version=1.6.19&library=checkoutjs&platform=android]() (1)

**Comment by vivekshindhe** [comment]
This error is an internal warning that should not affect payments. Are payment blocked for you?

**Comment by vivekshindhe** [comment]
@omkarChend1kar Closing this issue. Please feel free to comment to reopen the issue if you have any other issues.

**Comment by omkarChend1kar** [comment]
Actually I have list of items to buy, I found that the internal warning is shown for all the items, But for one particular item when I proceed to buy the razorpay gateway crashes and returns back to catalogue screen, And I am using coupon codes on all the items ,When I don't use coupon code on that particular item gateway doesn't crash.

**Comment by xuala69** [comment]
Getting this error when setting currency to USD, the payment page(razorpay window) is closed right after opening...any solution yet?

**Comment by adbuth4christ** [comment]
> Getting this error now. When setting currency to USD, the payment page(razorpay window) is closed right after opening..The error gives the reason for it saying value passed to razorpay should be integer and i was giving double. Fixed it after passing an integer..hope it helps someone

Can you please explain in detail
