### ISSUE TITLE
No Payment Methods available

### ISSUE THREAD

**Issue by preteambuy** [razorpay/razorpay-flutter#249]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
We did the integration with RazorPay and on checkout, there is no payment methods present. We have added PayTM as an external wallet in config and only that shows up. Any idea why credit cards or UPI payments aren't showing up?

## Flutter Version :
Run `flutter version` in your terminal and copy the results here.

Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c860cba910 (8 weeks ago) • 2022-03-25 00:23:12 -0500
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

## Xcode Version :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.

Version 13.3.1 (13E500a)

## Cocoapod Version :
Go to iOS folder > open `podfile.lock` > copy the `razorpay-pod version` and `razorpay_flutter`a version.

  - razorpay-pod (1.2.4)
  - razorpay_flutter (1.1.10):
  
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Add RazorPay dependencies, added the example code and on checkout not able to see any payment methods
2.

## Expected Results
Describe what you expected to happen.

Expecting to see some credit cards and UPI banking options

## Snack, code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

This is the config we have

    {
          'key': RAZORPAY_KEY_ID,
          'amount': (total * 100).toInt(),
          'currency' : 'INR',
          'name': ENTITY_NAME,
          'order_id': orderId,
          'retry': {'enabled': true, 'max_count': 1},
          'external': {
            'wallets': ['paytm']
          }
    };

**Comment by parthvirani-oceanmtech** [comment]
did you found any solution, if so please guide me same because i am also facing similar issue.

**Comment by sanketArhamLabs** [comment]
did you found any solution, if so please guide me same because i am also facing similar issue.

**Comment by piyush1726** [comment]
We are also facing the same issue, actually earlier we are on native android and ios, and everything was working fine but after moving our app to flutter, facing this same issue... anyone from razorpay..??

**Comment by preteambuy** [comment]
@parthvirani-oceanmtech @sanketArhamLabs @piyush1726 -Razor pay has to approve ur account to see other payment types. Please call the customer service
