### ISSUE TITLE
Undefined symbols for architecture armv7: / arm64  : In IOS 

### ISSUE THREAD

**Issue by vivekkujur** [razorpay/razorpay-flutter#25]
hi,
I am  using flutter v1.5.4-hotfix.2, and   razorpay_flutter: ^1.1.1
getting error when create ios release build. its working fine on ios simulator on debug mode. In Android its working fine .

Error is produce after add razorpay_flutter: ^1.1.1 plugin .

Error:-

**ld: warning: Could not find auto-linked framework 'Flutter'
Undefined symbols for architecture armv7:
  "_FlutterMethodNotImplemented", referenced from:
      -[FLTAndroidIntentPlugin handleMethodCall:result:] in AndroidIntentPlugin.o
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in AndroidIntentPlugin.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

Podfile:-

target 'Runner' do
  use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end

flutter doctor summary:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by bhanuc** [comment]
Facing same problem. Changing ios deployement target to 11 didn't work. Cleaning also didn't work.

**Comment by JayakumarB** [comment]
Facing same issue, any fix would be helpful

**Comment by JayakumarB** [comment]
Fixed it!!

In my case, earlier I was using XCode 10 and SWIFT 4.0. 
But Razorpay Flutter plugin supports SWIFT 5.0 so i updated Xcode and Swift. 

Actually my project was under TFS Source control so **ios** folder in flutter project and Runner Project and Workspace settings were referring to old version of SWIFT and XCode. Even though we update XCode and Swift, some reference was there. 

**Solution**

Just create new project after upgrading SWIFT and XCode. Add the flutter packages that you use in your old project and follow configurations mentioned in each packages you used.

Now replace **ios** folder from your new Flutter project with the old project.

Now you are all set to go!

Thanks,
Jayakumar B.

**Comment by umanghome** [comment]
@vivekkujur @bhanuc - Does @JayakumarB's solution work for you?

**Comment by Nautiyalsachin** [comment]
Closing this issue due to the inactivity. Please feel free to either re-open the issue or create a new ticket if you have any additional issues.
