### ISSUE TITLE
Razorpay is not initialising in release mode in android only

### ISSUE THREAD

**Issue by jagmohanJelly** [razorpay/razorpay-flutter#260]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I have recently upgraded the Razorpay plugin to 1.3.2 and after upgrading Razorpay is not initializing in the release mode it is showing the grey screen at the time of initialization but in debug mode, it works fine.

Note: I have researched about it and found that Razorpay is depending on a plugin called Device info plus package which has received a breaking change update so I think it is related to that 

## Flutter Version :
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (3 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

## Xcode Version :
this issue is only in android.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. initialize the latest Razorpay flutter plugin(1.3.2) in android 
2. try to run it in release mode, it works fine in debug mode

## Expected Results
razorpay is not initializing in android

**Comment by vivekshindhe** [comment]
@jagmohanJelly not able to reproduce this. Are you getting any error in the logs? put 
debuggable true in release block in build.gradle(:app). This should help you get it.

**Comment by jagmohanJelly** [comment]
fixed by added progaurd
