### ISSUE TITLE
Unable to load Maven meta-data from https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml.

### ISSUE THREAD

**Issue by swarup13** [razorpay/razorpay-flutter#280]
## Description
 What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.razorpay:checkout:1.6.+.
     Required by:
         project :app > project :razorpay_flutter
      > Failed to list versions for com.razorpay:checkout.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml'.
               > Read timed out

Flutter (Channel stable, 3.3.6, on macOS 13.0 22A380 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 14.0.1)
  razorpay_flutter: ^1.3.3
![Screenshot 2022-10-30 at 10 29 25 PM](https://user-images.githubusercontent.com/55395995/198891433-56723678-a4cc-4cd2-843f-cbb6d44152b3.png)

**Comment by webtamizhan** [comment]
![Screenshot 2022-10-30 at 10 45 31 PM](https://user-images.githubusercontent.com/13689740/198892027-8226b4d0-6de8-4b97-b994-3a6380b517d3.png)

Same issue

**Comment by swarup13** [comment]
jcenter.bintray.com is permanently down

**Comment by vijayvaghela72** [comment]
hello , 

i am getting same issue recently ,

![image](https://user-images.githubusercontent.com/61325761/198927248-31e51e92-a46e-4cac-a971-087537466ef6.png)

Waiting for solution ,
Thank You in advance ...! :)

**Comment by vijayvaghela72** [comment]
@swarup13 sir , 

have you find any solution for this issue ?

**Comment by mrinaljain** [comment]
![Screenshot 2022-10-31 at 10 16 55 AM](https://user-images.githubusercontent.com/7473761/198933121-042ca570-e779-42f7-a927-2e4ad1e5bfdd.png)

Is there a workaround for this?
Our major release is pending due to this.

**Comment by Subrataporwal** [comment]
![Screenshot 2022-10-31 at 10 58 18 AM](https://user-images.githubusercontent.com/68791598/198937749-fcfbc6b4-3d47-4339-a6dd-52c2143beaf0.png)
getting the same issue on Razorpay pub

**Comment by vijayvaghela72** [comment]
doe to this issue my work is stopped. please let me know if find any solution .

**Comment by akj-anu** [comment]
razorpay_flutter: 1.3.2   <== remove the up arrow  then try it will work

**Comment by AjnasAskar** [comment]
> razorpay_flutter: 1.3.2 <== remove the up arrow then try it will work

Its only a temp solution.

**Comment by vijayvaghela72** [comment]
i found this solution for now until the not solve you can use this , 


add this lines , 

in app/build.gradle 

     constraints {
        implementation('com.razorpay:checkout') {
            version {
                strictly '1.5.0'
                
            }
        }
    }
    
    
    in src/main/AndroidMenifest.xml file 
         
     <activity
            android:name="com.razorpay.CheckoutActivity"
            android:exported="true"
            />
    <receiver android:name="com.razorpay.RzpTokenReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="rzp.device_token.share"/>
            </intent-filter>
        </receiver>

**Comment by sreejithmg123** [comment]
> razorpay_flutter: 1.3.2 <== remove the up arrow then try it will work

It's not a good practice

**Comment by swarup13** [comment]
@vivekshindhe can you please look into this issue?

**Comment by vijayvaghela72** [comment]
in app/build.gradle

 constraints {
    implementation('com.razorpay:checkout') {
        version {
            strictly '1.5.0'
            
        }
    }
}



best solution for now

**Comment by omkartecx** [comment]
> <activity
>         android:name="com.razorpay.CheckoutActivity"
>         android:exported="true"
>         />
> <receiver android:name="com.razorpay.RzpTokenReceiver"
>         android:exported="false">
>         <intent-filter>
>             <action android:name="rzp.device_token.share"/>
>         </intent-filter>
>     </receiver>

Works for ME

**Comment by omkartecx** [comment]
> i found this solution for now until the not solve you can use this ,
> 
> add this lines ,
> 
> in app/build.gradle
> 
> ```
>  constraints {
>     implementation('com.razorpay:checkout') {
>         version {
>             strictly '1.5.0'
>             
>         }
>     }
> }
> 
> 
> in src/main/AndroidMenifest.xml file 
>      
>  <activity
>         android:name="com.razorpay.CheckoutActivity"
>         android:exported="true"
>         />
> <receiver android:name="com.razorpay.RzpTokenReceiver"
>         android:exported="false">
>         <intent-filter>
>             <action android:name="rzp.device_token.share"/>
>         </intent-filter>
>     </receiver>
> ```
> 
> this one working fine for me .

Working fine on this
But add the constraints inside android->app->build.grade-> then inside dependencies 
{`
dependencies {
    //implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation 'com.android.support:multidex:2.0.1'

    implementation 'com.google.mlkit:object-detection:16.2.7'


    apply plugin: 'com.google.firebase.crashlytics'

    constraints {   
        implementation('com.razorpay:checkout') {
            version {
                strictly '1.5.0'
            }
        }
    }`

**Comment by sagnik-sanyal** [comment]
guys in your android/build.gradle can you try out :- 

allprojects {
      repositories {
          all { ArtifactRepository repo ->
              println repo.url.toString()
              if (repo.url.toString().startsWith("https://jcenter.bintray.com/")) {
                  project.logger.warn "Repository ${repo.url} removed."
                  remove repo
                  mavenCentral()
              }
          }
          gradlePluginPortal() // add this if you get further errors 
          ....others
      }
    }

All credits to -->> https://stackoverflow.com/a/74261483/19295870

**Comment by mohitleo03** [comment]
I was just figuring out the solution and found this on official razorpay_flutter git directory, the temp solution is to set the razorpay_flutter version to 1.3.2 without ^ this symbol.
for more solution refer to this link - [https://github.com/razorpay/razorpay-flutter/issues/280](https://github.com/razorpay/razorpay-flutter/issues/280)

**Comment by Subrataporwal** [comment]
> guys in your android/build.gradle can you try out , i tried this and it worked out for me :-
> 
> allprojects { repositories { all { ArtifactRepository repo -> println repo.url.toString() if (repo.url.toString().startsWith("https://jcenter.bintray.com/")) { project.logger.warn "Repository ${repo.url} removed." remove repo mavenCentral() } } gradlePluginPortal() // add this if you get further errors ....others } }
> 
> All credits to -->> https://stackoverflow.com/a/74261483/19295870

This Solution Works for me too, Thanks @sagnik-sanyal for sharing.
![razorpay](https://user-images.githubusercontent.com/68791598/199056671-ac30b0df-a222-4919-ae09-8920e37fb095.png)

**Comment by vivekshindhe** [comment]
Removed the jcenter inclusion in build.gradle file. Issue fixed on v1.3.4. Thank you for your patience.
