### ISSUE TITLE
Pure Dart implementation using Restful APIs

### ISSUE THREAD

**Issue by amitkhairnar44** [razorpay/razorpay-flutter#29]
Hello,
You guys can write a pure dart implementation using the Restful API. It would be great and easy to debug.

**Comment by umanghome** [comment]
The Checkout Flutter SDK needs more than just a REST API (UI and stuff). This is perhaps more suited for a Dart SDK just like our [Node SDK](https://github.com/razorpay/razorpay-node).

**Comment by amitkhairnar44** [comment]
A Dart SDK would be a great alternative to this plugin

**Comment by sumedht** [comment]
Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
