### ISSUE TITLE
Intent Redirection Vulnerability

### ISSUE THREAD

**Issue by preteambuy** [razorpay/razorpay-flutter#292]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Getting the below error after submitting the app to the android app store & after upgrading to flutter 3.7.0. 

Intent Redirection
Your app(s) are vulnerable to Intent Redirection.

To address this issue, follow the steps in this [Google Help Center article](https://notifications.google.com/g/p/APdRdFxS7SfPsO8xHF3GsppzV6I1BpD_3_u-u-IP0JPsSSiiaMj6tojI_ppMnfs_Old06ISmIjJF8OwHk5VVH7z1njacmcIPwVdSbztgC1tPoUDi30AZp5Lg1ByUpdKmBN87r5tKcKgY_nuBxeOTWACgfIRyy0fIo5uTIHplf4fag-5jf36XE6tNdravUFWk8LhibOmV4CUJss-hX3g8).

com.razorpay.b__J_.onReceive

## Flutter Version :
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (4 days ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1

## Xcode Version :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.
14.2

## Cocoapod Version :
Go to iOS folder > open `podfile.lock` > copy the `razorpay-pod version` and `razorpay_flutter`a version.
razorpay-pod (1.3.0)
razorpay_flutter (1.1.10)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Upgraded flutter to the above version 3.7.0
2. After uploading to android store got the above error message.

## Expected Results
Describe what you expected to happen.
Fix the vulnerability

## Snack, code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by sagarmahobia** [comment]
Same Issue.

**Comment by sagarmahobia** [comment]
Found any solution?

**Comment by nikb7** [comment]
Yes, we also got the same warning mail for our app.

**Comment by ashwinterminator** [comment]
Same issue on our app as well.

**Comment by vivekshindhe** [comment]
Hey folks, we are currently looking into this. The fix will be made live by Monday morning. Will update here once done. Thank you for your patience.

**Comment by tusharbhambere** [comment]
Same Issue we also facing

**Comment by prateek601** [comment]
Any updates here? We are also facing same issue.

**Comment by Lokendra16** [comment]
I got the mail from google play store after uploading app "Intent redirection vulnerability",
If any one of you got the solution please share so.

**Comment by vivekshindhe** [comment]
Hey folks, apologies for the delay on this. A new version has been pushed to maven for android SDK. Please ensure the older version isn't cached and reinstall again. When uploading to play store please ensure that the version which was throwing this error from google is out of the track so this issue doesn't crop up again. Thank you for your support.

Will keep this thread open in case any of you weren't able to resolve this issue with Google.

**Comment by preteambuy** [comment]
@vivekshindhe should we do flutter clean n do an android build?

**Comment by vivekshindhe** [comment]
@preteambuy for flutter just sync it once with gradle. And in external libraries cross verify the version of com.razorpay.checkout to be 1.6.28.

**Comment by agrvaibhav** [comment]
@vivekshindhe Please point to the native android SDK fix.

**Comment by Jigar-zest** [comment]
How can we make this change? Do you want us to add com.razorpay.checkout:1.6.28. external library to gradle file or something else?
I have checked there is no new version available for this on a pub.dev.

**Comment by Jigar-zest** [comment]
you mean just add com.razorpay.checkout:1.6.28 and gradle will do the rest of the work Right?

**Comment by vivekshindhe** [comment]
@Jigar-zest Not necessarily. Since the flutter package adds it internally

**Comment by Tranminator** [comment]
> @Jigar-zest Not necessarily. Since the flutter package adds it internally

@vivekshindhe I'm using RazorPay version 1.3.4 on pub.dev so it's will be auto add com.razorpay.checkout:1.6.28 or I must wait newer version on pub.dev?

**Comment by vivekshindhe** [comment]
@Tranminator it will automatically add it

**Comment by ashwinterminator** [comment]
Here's what I did -

dart pub cache clean
Sync Project with Grade Files
To be doubly sure, I also did -  ./gradlew --refresh-dependencies from terminal inside the android folder of my Flutter project
The external libraries version on Android Studio did say 1.6.28
I uploaded it to the Play Store but still got the intent redirection vulnerability warning.

Anyone else who managed to fix this issue?

**Comment by agrvaibhav** [comment]
@vivekshindhe We did a clean build through Jenkins yesterday evening and uploaded it to the play store and got the warning immediately after uploading from the play store.
There is something amiss here. Would you be able to confirm if the `com.razorpay.checkout:1.6.28` indeed fixes the issue.

I can also see, this issue was fixed long time back as per below release notes, so why are we still on it?
<img width="1181" alt="Screenshot 2023-01-31 at 11 28 18 AM" src="https://user-images.githubusercontent.com/2479919/215678285-5bc1ef07-24cb-48cb-bfe0-319533a5d471.png">

**Comment by vivekshindhe** [comment]
Yes @agrvaibhav it does fixes the issue. The issue is with the broadcast receiver sent by SMS_RETREIVER_API which leads to vulnerability. The above was a different one. While the above issue is related to the android code is flutter, the issue you are currently facing on Play Console relates to the android SDK which has been updated.

**Comment by vinayak-idc** [comment]
hi everyone, i have tried updating the version and made sure the Gradle version says  1.6.28. but i haves still received this issue stating
Your app(s) are vulnerable to Intent Redirection.

To address this issue, follow the steps in this [Google Help Center article](https://notifications.google.com/g/p/APdRdFxFjEfnOpEDDwsYTNKtJlo3NVq5xgwT5s1yhGX6AYekyVVXjn8YoO-5hjZQoqUtMtnV0mOfzeOlPxQMA9i3rcbvoOKY2rrbMf2lHnsEZkGCUtw45meQXWemBREOJCkg3NzwibvzMR_vJ_oTh1HH5K-qM8gGt7Rtwcp0W-opuDVPkjWHS_5uxC70vrv11uU1yBIAIeddUAH2wqI).

com.razorpay.x2.onReceive

please check.

**Comment by joeydash** [comment]
Hi Please push a flutter update too

**Comment by vinayak-idc** [comment]
hi @joeydash are you asking to update flutter version to 3.7.0 ?

**Comment by jerrypaulsam** [comment]
Has anyone got a fix? I just received the same warning from google play now!

**Comment by vivekshindhe** [comment]
Hey guys, apologies for the delay. Had to combine two of the remedies together for it to work. Please reinstall the razorpay package and try uploading. I'm gonna attach a screenshot of the working sample as well.
![Screenshot 2023-01-31 at 7 05 03 PM](https://user-images.githubusercontent.com/57621906/215775076-dc127753-b974-4e2a-94e4-a64559818c16.png)

**Comment by preteambuy** [comment]
i was able to successfully submit to android without the issue.

Run
 
flutter clean
flutter pub cache clean

**Comment by ashwinterminator** [comment]
This appears to be solved.

1. Synced gradle on Android Studio
2. dart pub cache clean
3. flutter clean
4. Ran the build
5. Uploaded to Play Store
6. No warning email after about 12 hours.

Thank you, @vivekshindhe! :)

**Comment by ibhavikmakwana** [comment]
> This appears to be solved.
> 
>     1. Synced gradle on Android Studio
> 
>     2. dart pub cache clean
> 
>     3. flutter clean
> 
>     4. Ran the build
> 
>     5. Uploaded to Play Store
> 
>     6. No warning email after about 12 hours.
> 
> 
> Thank you, @vivekshindhe! :)

We have followed all these steps for our app but it is still giving us the same error.

**Comment by vivekshindhe** [comment]
@ibhavikmakwana Hey, do make sure to deactivate the bundle who's version was throwing this error.

**Comment by ashwinterminator** [comment]
> @ibhavikmakwana Hey, do make sure to deactivate the bundle who's version was throwing this error.

@vivekshindhe - can you provide a consolidated list of steps to do this? The instructions are spread out across multiple messages right now. For instance, I did not do this deactivation that you're referring to.

**Comment by vivekshindhe** [comment]
@ashwinterminator To be fair, it's a bit muddled for me as well. While in the app I tried to pushed to playstore, I did not have to do this. Seeing this is being resolved for other people, it would be best to reach out to google as well to know exactly what works for you.

**Comment by jerrypaulsam** [comment]
I did everything mentioned above, but still getting the same email from Google. Isn't there a proper approach to this particular issue? This is the 3rd attempt in 24 hours.

**Comment by vivekshindhe** [comment]
@jerrypaulsam In the retained bundles, if you see a version that gets affected by this, that can also cause this error to pop up. Please ensure to remove it from the retained bundle list. I'd also suggest talking with google directly regarding this because this did not happen in the app I pushed.

**Comment by preteambuy** [comment]
@jerrypaulsam is it the same exact error as before?

**Comment by psyirius** [comment]
Same error over and over again after 3 uploads and trying all the above steps.
Got any quick remedy to resolve this?

**Comment by jerrypaulsam** [comment]
This is the same error before and after updating the app.

![IMG_2FCC719B3717-1](https://user-images.githubusercontent.com/62291043/215984445-48db62f5-2eb7-4a75-99ba-bfe6c936a124.jpeg)

**Comment by jerrypaulsam** [comment]
> @jerrypaulsam is it the same exact error as before?

Yes it is. We did everything mentioned above multiple times and getting the same error over and over again.

**Comment by vivekshindhe** [comment]
For the folks who are still facing the issue, please raise a support ticket on the Razorpay Dashboard. Our support team will help you sort out the issue the best we can.

Closing the ticket with this.

**Comment by nikb7** [comment]
1. dart pub cache clean
2. flutter clean
3. flutter pub get
4. cd android && ./gradlew clean (make sure this is done)
5. flutter pub get

This has fixed the issue for us.
Thanks @vivekshindhe @ashwinterminator
