### ISSUE TITLE
Package uses outdated dependencies

### ISSUE THREAD

**Issue by OutdatedGuy** [razorpay/razorpay-flutter#296]
Please upgrade dependencies to the latest versions.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/74326345/218342247-68833d90-7d9a-4ef4-a035-96ebe2b9cb78.png">

**Comment by rajeshzmoke** [comment]
yes creates issues with other packages

**Comment by Biswajit1729** [comment]
please update this dependency we are not able to use with appwrite: ^8.2.2

**Comment by venky9885** [comment]
please update all dependencies ,its create=ing conflict with other packages

**Comment by venky9885** [comment]
ct.add(Cart(
                                  number: dlg.split(",,")[0],
                                  debt: debt,
                                  depamt: (int.parse(dlg
                                              .split(",,")[2]
                                              .split(",")
                                              .join("")) *
                                          debt)
                                      .toString()));
