### ISSUE TITLE
that was originally registered here. Are you missing a call to unregisterReceiver()

### ISSUE THREAD

**Issue by inamhusain** [razorpay/razorpay-flutter#309]
Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.b__J_@458d454 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(12409): android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.b__J_@458d454 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(12409): 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1754)
E/ActivityThread(12409): 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1525)
E/ActivityThread(12409): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1768)
E/ActivityThread(12409): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1734)
E/ActivityThread(12409): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1722)
E/ActivityThread(12409): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:736)
E/ActivityThread(12409): 	at com.razorpay.CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP(CheckoutPresenterImpl.java:919)
E/ActivityThread(12409): 	at com.razorpay.CheckoutPresenterImpl.onLoad(CheckoutPresenterImpl.java:910)
E/ActivityThread(12409): 	at com.razorpay.O__Y_.secure(CheckoutBridge.java:27)
E/ActivityThread(12409): 	at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1374)
E/ActivityThread(12409): 	at com.razorpay.CheckoutPresenterImpl.access$400(CheckoutPresenterImpl.java:57)
E/ActivityThread(12409): 	at com.razorpay.b$_f_.run(CheckoutPresenterImpl.java:1359)
E/ActivityThread(12409): 	at android.os.Handler.handleCallback(Handler.java:938)
E/ActivityThread(12409): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/ActivityThread(12409): 	at android.os.Looper.loopOnce(Looper.java:210)
E/ActivityThread(12409): 	at android.os.Looper.loop(Looper.java:299)
E/ActivityThread(12409): 	at android.app.ActivityThread.main(ActivityThread.java:8298)
E/ActivityThread(12409): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(12409): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
E/ActivityThread(12409): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

Getting issue : payment done but not getting success call back

![carbon (1)](https://user-images.githubusercontent.com/70013058/231108062-c5c1793f-6254-4b2a-9062-230637270be4.png)

**Comment by dharambudh1** [comment]
Hi @inamhusain, What is the solution?
