### ISSUE TITLE
Error while running the example

### ISSUE THREAD

**Issue by KevinPatel04** [razorpay/razorpay-flutter#31]
I am getting a toast regarding Your onPaymentError method is throwing an error. Wrap the entire code of the method in try and catch while running this example mentioned here.

I have already set the minSdkVersion to 20.

**Comment by ChintanAcharya** [comment]
@KevinPatel04 Can you please share logcat logs?

**Comment by shikharvaish28** [comment]
@KevinPatel04  Can you please share how did you fix the issue?

**Comment by KevinPatel04** [comment]
> @KevinPatel04 Can you please share how did you fix the issue?
@shikharvaish28 you can refer [Payment Module](https://github.com/KevinPatel04/FarFromHome/blob/master/lib/ui/page_payment.dart)

Please verify you are entering your api-key in the "key"  LINE NUMBER 335

I think this would help...
