### ISSUE TITLE
 Could not find method useProguard() for arguments [true]

### ISSUE THREAD

**Issue by Pradeepa651** [razorpay/razorpay-flutter#315]
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method useProguard() for arguments [true] on BuildType$AgpDecorated_Decorated{name=release, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=true, zipAlignEnabled=true, signingConfig=SigningConfig$AgpDecorated_Decorated{name=debug, storeFile=C:\Users\PRADEEPA G\.android\debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=pkcs12, v1SigningEnabled=true, v2SigningEnabled=true, enableV1Signing=null, enableV2Signing=null, enableV3Signing=null, enableV4Signing=null}, embedMicroApp=true, mBuildConfigFields={}, mResValues={}, mProguardFiles=[C:\fine_art_shop\build\app\intermediates\default_proguard_files\global\proguard-android.txt-7.2.2, C:\src\flutter\packages\flutter_tools\gradle\flutter_proguard_rules.pro, C:\fine_art_shop\android\app\proguard-rules.pro], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType$AgpDecorated.

**Comment by vivekshindhe** [comment]
@Pradeepa651 I believe this is not related to the Razorpay flutter package. [Here's](https://github.com/flutter-webrtc/flutter-webrtc/issues/1183) a link to folks finding the same issue. If that doesn't work, please replace useProguard with minifyEnabled in your build.gradle file. 

Closing this ticket.
