### ISSUE TITLE
The plugin `razorpay_flutter` uses a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by Pradeepa651** [razorpay/razorpay-flutter#316]
The plugin `razorpay_flutter` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by vivekshindhe** [comment]
@Pradeepa651 I believe you are seeing this error on the sample application. Razorpay-flutter doesn't use deprecated Android embedding anymore. We will update the sample app. Until then, please create a sample app to understand the integration process better using [this](https://razorpay.com/docs/payments/payment-gateway/flutter-integration/standard?search-string=flutter) guide. Thank you.
