### ISSUE TITLE
App crashes with Segmentation fault on iOS devices. Works fine on Android.

### ISSUE THREAD

**Issue by akasantony** [razorpay/razorpay-flutter#33]
App crashes on launch with the following error. 
`com.apple.CoreSimulator.SimDevice.00824A43-86CE-47F2-BE72-E409EF4D1018[46735] (UIKitApplication:in.wup.ios[0xde7b][46756][80689]): Service exited due to Segmentation fault: 11`

If I remove user_frameworks! I get the following error.

` error: module map file '/Users/akasantony/Library/Developer/Xcode/DerivedData/Runner-fkvindakxlzttigznzvgapmpievl/Build/Products/Debug-iphonesimulator/razorpay_flutter/razorpay_flutter.modulemap' not found`

**Comment by Nautiyalsachin** [comment]
Hey @akasantony, try to update the razorpay-pod to the latest version and also update your Xcode, this will help you to get our module stabilised SDK, which solve this `.modulemap` error.
