### ISSUE TITLE
App Terminated when Open Payment Gateway on release mode.  Work Perfect on debug mode 

### ISSUE THREAD

**Issue by SandyAra** [razorpay/razorpay-flutter#34]

**Comment by LOG-TAG** [comment]
https://github.com/razorpay/razorpay-android-sample-app/issues/84

**Comment by ChintanAcharya** [comment]
@SandyAra Can you share more details, like the platform (iOS/Android) and log output?

**Comment by hiteshgarg002** [comment]
#42

**Comment by sumedht** [comment]
Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
