### ISSUE TITLE
Issue while building app because of razorpay-flutter 

### ISSUE THREAD

**Issue by MohsinP07** [razorpay/razorpay-flutter#345]
In my project i have used razorpay-flutter package, it was working fine but suddenly whle building the project i am getting error as 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.razorpay:checkout:1.6.+.
     Required by:
         project :app > project :razorpay_flutter
      > Failed to list versions for com.razorpay:checkout.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml'. Received status code 502 from server: Bad Gateway 
I have not made any changes in the project still i am encountering this issue.

**Comment by vivekshindhe** [comment]
Hey @MohsinP07, looks like flutter is trying to get the dependency from JCenter. Can you check if jcenter is present in the (root-level) build.gradle file/buildscript/repositories? If it is present, you can try removing it or adding mavenCentral() at the top of the list as the search for dependencies goes one by one.

**Comment by MohsinP07** [comment]
Hey @vivekshindhe this worked for me. Thanks a lot!
