### ISSUE TITLE
SDK on iOS is not able to download pod files on v1.1.2

### ISSUE THREAD

**Issue by raghav39** [razorpay/razorpay-flutter#37]
I am getting the following error on pod install
```
[!] CocoaPods could not find compatible versions for pod "razorpay-pod":
  In snapshot (Podfile.lock):
    razorpay-pod (= 1.1.2)

  In Podfile:
    razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`) was resolved to 1.1.1, which depends on
      razorpay-pod (~> 1.1.4)
```

**Comment by ChintanAcharya** [comment]
@raghav39 Try running `pod update` in the ios directory and let us know if it works.

**Comment by Nautiyalsachin** [comment]
Closing this issue due to the inactivity. Please feel free to either re-open the issue or create a new ticket if you have any additional issues.

**Comment by wirelessbhai** [comment]
### **Error Launching The Application**

[!] CocoaPods could not find compatible versions for pod "razorpay_flutter":
      In Podfile:
        razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`)

 Specs satisfying the `razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by winterprogram** [comment]
Error Launching The Application on Ios Device
[!] CocoaPods could not find compatible versions for pod "razorpay_flutter":
In Podfile:
razorpay_flutter (from .symlinks/plugins/razorpay_flutter/ios)

Specs satisfying the razorpay_flutter (from .symlinks/plugins/razorpay_flutter/ios) dependency were found, but they required a higher minimum deployment target.

**Comment by ravipromact2306** [comment]
@winterprogram Any luck with this?

**Comment by vashisth00** [comment]
[!] CocoaPods could not find compatible versions for pod "razorpay_flutter":
  In Podfile:
    razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`)

Specs satisfying the `razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by Nautiyalsachin** [comment]
Hi @mohammadjawedahmadansari Go to the ios folder and run `pod update` for updating the pods, also check the dependency mentioned on the pod file. It should be iOS 10 and above. I would also suggest you remove the current plugin and try adding it again.
