### ISSUE TITLE
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by devsigofficial** [razorpay/razorpay-flutter#374]
ava.lang.SecurityException: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/AndroidRuntime(19226): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3182)
E/AndroidRuntime(19226): 	at android.os.Parcel.createException(Parcel.java:3166)
E/AndroidRuntime(19226): 	at android.os.Parcel.readException(Parcel.java:3149)
E/AndroidRuntime(19226): 	at android.os.Parcel.readException(Parcel.java:3091)
E/AndroidRuntime(19226): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5784)
E/AndroidRuntime(19226): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1853)
E/AndroidRuntime(19226): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1793)
E/AndroidRuntime(19226): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1781)
E/AndroidRuntime(19226): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:756)
E/AndroidRuntime(19226): 	at com.razorpay.CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP(CheckoutPresenterImpl.java:884)
E/AndroidRuntime(19226): 	at com.razorpay.CheckoutPresenterImpl.access$600(CheckoutPresenterImpl.java:59)
E/AndroidRuntime(19226): 	at com.razorpay.G$_X_.onFinish(CheckoutPresenterImpl.java:863)
E/AndroidRuntime(19226): 	at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:142)
E/AndroidRuntime(19226): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(19226): 	at android.os.Looper.loopOnce(Looper.java:232)
E/AndroidRuntime(19226): 	at android.os.Looper.loop(Looper.java:317)
E/AndroidRuntime(19226): 	at android.app.ActivityThread.main(ActivityThread.java:8501)
E/AndroidRuntime(19226): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19226): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(19226): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by devsigofficial** [comment]
`  void rechargeWallet() {
    try {
      Razorpay razorpay = Razorpay();
      var options = {
        'key': 'rzp_test_1DP5mmOlF5G5ag',
        'amount': 100,
        'name': 'Acme Corp.',
        'description': 'Fine T-Shirt',
        'retry': {'enabled': true, 'max_count': 1},
        'send_sms_hash': true,
        'prefill': {'contact': '8888888888', 'email': 'test@razorpay.com'},
        'external': {
          'wallets': ['paytm']
        }
      };
      razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, handlePaymentErrorResponse);
      razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS, handlePaymentSuccessResponse);
      razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET, handleExternalWalletSelected);
      razorpay.open(options);
    } catch (ex) {
      AppLog(ex);
    }
  }`

**Comment by vivekshindhe** [comment]
@devsigofficial Can you share the targetSdkVersion used by your project?

**Comment by bholendraofficial** [comment]
@vivekshindhe targetSdK 34

**Comment by vivekshindhe** [comment]
@bholderaofficial @devsigofficial Unable to reporduce the issue. Is this is a fatal error? Can you please post the reproduction steps?

**Comment by devsigofficial** [comment]
Dear Razorpay/Razorpay-Flutter,

You can check on Android Target SDK 34 and compile SDK 34 and check on
Android 14 device

**Comment by vivekshindhe** [comment]
yes, @devsigofficial, we did try that. With both targetSDK and compileSDK version 34 and on android 14 device. Want more details of the error because it's not reproducible to us. 
Queries: 
1. Is it a fatal error? 
2. please share the reproduction steps.

**Comment by devsigofficial** [comment]
V/FA      (27118): Connecting to remote service
E/com.razorpay.checkout(27118): GooglePay library not included
V/FA      (27118): Activity paused, time: 42821015
V/FA      (27118): onActivityCreated
W/ziparchive(27118): Unable to open '/data/app/~~dCT-KJM0ckLnJAktxxQx_w==/com.google.android.trichromelibrary_631209933-1fzAYWS_Dpxe-7rLbY80-A==/base.dm': No such file or directory
W/ziparchive(27118): Unable to open '/data/app/~~dCT-KJM0ckLnJAktxxQx_w==/com.google.android.trichromelibrary_631209933-1fzAYWS_Dpxe-7rLbY80-A==/base.dm': No such file or directory
W/evsig.trustride(27118): Entry not found
D/nativeloader(27118): Configuring clns-10 for other apk /data/app/~~dCT-KJM0ckLnJAktxxQx_w==/com.google.android.trichromelibrary_631209933-1fzAYWS_Dpxe-7rLbY80-A==/base.apk. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~-AWETc72yyHSAkSJoPiduw==/com.google.android.webview-23CWnGHGM_k8uWPaoRvS7Q==/lib/arm64:/data/app/~~-AWETc72yyHSAkSJoPiduw==/com.google.android.webview-23CWnGHGM_k8uWPaoRvS7Q==/base.apk!/lib/arm64-v8a:/data/app/~~dCT-KJM0ckLnJAktxxQx_w==/com.google.android.trichromelibrary_631209933-1fzAYWS_Dpxe-7rLbY80-A==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
D/nativeloader(27118): Extending system_exposed_libraries: libedgetpu_dba.google.so
D/nativeloader(27118): Configuring clns-11 for other apk /data/app/~~-AWETc72yyHSAkSJoPiduw==/com.google.android.webview-23CWnGHGM_k8uWPaoRvS7Q==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~-AWETc72yyHSAkSJoPiduw==/com.google.android.webview-23CWnGHGM_k8uWPaoRvS7Q==/lib/arm64:/data/app/~~-AWETc72yyHSAkSJoPiduw==/com.google.android.webview-23CWnGHGM_k8uWPaoRvS7Q==/base.apk!/lib/arm64-v8a:/data/app/~~dCT-KJM0ckLnJAktxxQx_w==/com.google.android.trichromelibrary_631209933-1fzAYWS_Dpxe-7rLbY80-A==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
I/WebViewFactory(27118): Loading com.google.android.webview version 123.0.6312.99 (code 631209933)
I/cr_WVCFactoryProvider(27118): Loaded version=123.0.6312.99 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
E/chromium(27118): [0418/225645.183461:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
I/cr_LibraryLoader(27118): Successfully loaded native library
I/cr_CachingUmaRecorder(27118): Flushed 6 samples from 6 histograms, 0 samples were dropped.
I/cr_CombinedPProvider(27118): #registerProvider() provider:WV.f7@62ffe81 isPolicyCacheEnabled:false policyProvidersSize:0
I/cr_PolicyProvider(27118): #setManagerAndSource() 0
I/cr_CombinedPProvider(27118): #linkNativeInternal() 1
I/cr_AppResProvider(27118): #getApplicationRestrictionsFromUserManager() Bundle[EMPTY_PARCEL]
I/cr_PolicyProvider(27118): #notifySettingsAvailable() 0
I/cr_CombinedPProvider(27118): #onSettingsAvailable() 0
I/cr_CombinedPProvider(27118): #flushPolicies()
D/CompatibilityChangeReporter(27118): Compat change id reported: 214741472; UID 10057; state: ENABLED
D/CompatibilityChangeReporter(27118): Compat change id reported: 171228096; UID 10057; state: ENABLED
D/TrafficStats(27118): tagSocket(240) with statsTag=0xffffffff, statsUid=-1
W/cr_media(27118): BLUETOOTH_CONNECT permission is missing.
W/cr_media(27118): registerBluetoothIntentsIfNeeded: Requires BLUETOOTH permission
I/ContentCaptureHelper(27118): Setting logging level to OFF
V/FA      (27118): Activity resumed, time: 42821465
D/SessionLifecycleClient(27118): Sending lifecycle 1 to service
D/SessionLifecycleService(27118): Activity foregrounding at 13711065.
D/SessionLifecycleService(27118): Cold start detected.
D/SessionLifecycleService(27118): Generated new session 2e140bdcfda3487aa8266db500254bae
D/SessionLifecycleService(27118): Broadcasting new session: SessionDetails(sessionId=2e140bdcfda3487aa8266db500254bae, firstSessionId=2e140bdcfda3487aa8266db500254bae, sessionIndex=0, sessionStartTimestampUs=1713461205519000)
D/SessionFirelogPublisher(27118): Data Collection is enabled for at least one Subscriber
V/FA      (27118): Connection attempt already in progress
D/EventGDTLogger(27118): Session Event: {"eventType":1,"sessionData":{"sessionId":"2e140bdcfda3487aa8266db500254bae","firstSessionId":"2e140bdcfda3487aa8266db500254bae","sessionIndex":0,"eventTimestampUs":1713461205519000,"dataCollectionStatus":{"performance":1,"crashlytics":2,"sessionSamplingRate":1.0},"firebaseInstallationId":"e8HLFY8CRBWvXKt-unrqCC","firebaseAuthenticationToken":"eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6IjE6MTg0MzEwOTMyNzIxOmFuZHJvaWQ6ZWQ4YzU4MmRlYjliN2M5ZTljZjU1MCIsImV4cCI6MTcxMzkzODAyOCwiZmlkIjoiZThITEZZOENSQld2WEt0LXVucnFDQyIsInByb2plY3ROdW1iZXIiOjE4NDMxMDkzMjcyMX0.AB2LPV8wRAIgKoE39mGLjGp70PGfA97PiWROWvJaP5kQPHDwedBiL_0CIG5FiWgmzM2gm_cspLZeZPC6czDSOS6Lcoz3d5PFTIFH"},"applicationInfo":{"appId":"1:184310932721:android:ed8c582deb9b7c9e9cf550","deviceModel":"Pixel 6a","sessionSdkVersion":"1.2.4","osVersion":"14","logEnvironment":3,"androidAppInfo":{"packageName":"com.devsig.trustride","versionName":"1.0.0","appBuildVersion":"1","deviceManufacturer":"Google","currentProcessDetails":{"processName":"com.devsig.trustride","pid":27118,"importance":100,"defaultProcess":true},"appProcessDetails":[{"processName":"com.devsig.trustride","pid":27118,"importance":100,"defaultProcess":true}]}}}
D/SessionFirelogPublisher(27118): Successfully logged Session Start event: 2e140bdcfda3487aa8266db500254bae
D/CompatibilityChangeReporter(27118): Compat change id reported: 193247900; UID 10057; state: ENABLED
D/CompatibilityChangeReporter(27118): Compat change id reported: 194532703; UID 10057; state: ENABLED
D/CompatibilityChangeReporter(27118): Compat change id reported: 253665015; UID 10057; state: ENABLED
D/CompatibilityChangeReporter(27118): Compat change id reported: 311402873; UID 10057; state: DISABLED
I/ContentCaptureHelper(27118): Setting logging level to OFF
W/evsig.trustride(27118): Accessing hidden field Landroid/content/pm/ApplicationInfo;->primaryCpuAbi:Ljava/lang/String; (unsupported, reflection, allowed)
D/SessionLifecycleClient(27118): Session update received: 2e140bdcfda3487aa8266db500254bae
D/SessionLifecycleClient(27118): Notified CRASHLYTICS of new session 2e140bdcfda3487aa8266db500254bae
D/FA      (27118): Analytics Storage consent is not granted
D/FA      (27118): Resetting session stitching token to null
V/FA      (27118): Connection attempt already in progress
D/FA      (27118): Connected to remote service
V/FA      (27118): Processing queued up service tasks: 3
D/FA      (27118): Analytics Storage consent is not granted
D/FA      (27118): Resetting session stitching token to null
D/TrafficStats(27118): tagSocket(277) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats(27118): tagSocket(353) with statsTag=0xffffffff, statsUid=-1
D/CompatibilityChangeReporter(27118): Compat change id reported: 210923482; UID 10057; state: ENABLED
D/CompatibilityChangeReporter(27118): Compat change id reported: 63938206; UID 10057; state: DISABLED
D/TrafficStats(27118): tagSocket(338) with statsTag=0xffffffff, statsUid=-1
D/VRI[MainActivity](27118): visibilityChanged oldVisibility=true newVisibility=false
D/VRI[MainActivity](27118): applyTransactionOnDraw applyImmediately
D/VRI[MainActivity](27118): Not drawing due to not visible
D/AppSignatureHelper(27118): pkg: com.devsig.trustride -- hash: 0zO/7IzQNJc
E/com.razorpay.checkout(27118): Webview JS Error: Uncaught TypeError: CheckoutBridge.sendAnalyticsData is not a function
I/chromium(27118): [INFO:CONSOLE(1)] "Uncaught TypeError: CheckoutBridge.sendAnalyticsData is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.6.19&library=checkoutjs&platform=android&session_token=6119830A4DAE9CD7ADEE6B1E50B06C27469BACBBD1D8740B01110BED157CC07A7CB4AB8CF8697BE6E138A53649A0713D5543A183F933B553625AE3F0876F12111AFC3EC3D93500D4508F009E2114DC90A467A7C1FE6DBA60E237BF88B28642709F5D65F5D65762FD4BEEE86270569EE8826DADCE31517F61223962A8F356A6F0F0A2D9A1A01593071390531371A048427CC90B&traffic_env=production (1)
D/TrafficStats(27118): tagSocket(139) with statsTag=0xffffffff, statsUid=-1
D/AppSignatureHelper(27118): pkg: com.devsig.trustride -- hash: 0zO/7IzQNJc
W/WindowOnBackDispatcher(27118): sendCancelIfRunning: isInProgress=falsecallback=android.app.Dialog$$ExternalSyntheticLambda2@c1a13fe
D/TrafficStats(27118): tagSocket(182) with statsTag=0xffffffff, statsUid=-1
I/chromium(27118): [INFO:CONSOLE(1)] "Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently", source: https://checkout-static-next.razorpay.com/build/e011af9ce9d609b5ba0de0a2e727307dcc47e708/checkout-frame.modern.js (1)
E/com.razorpay.checkout(27118): Webview JS Error: Uncaught TypeError: window.getDeviceDetails is not a function
I/chromium(27118): [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.6.19&library=checkoutjs&platform=android&session_token=6119830A4DAE9CD7ADEE6B1E50B06C27469BACBBD1D8740B01110BED157CC07A7CB4AB8CF8697BE6E138A53649A0713D5543A183F933B553625AE3F0876F12111AFC3EC3D93500D4508F009E2114DC90A467A7C1FE6DBA60E237BF88B28642709F5D65F5D65762FD4BEEE86270569EE8826DADCE31517F61223962A8F356A6F0F0A2D9A1A01593071390531371A048427CC90B&traffic_env=production (1)
E/com.razorpay.checkout(27118): Webview JS Error: Error: <svg> attribute width: Unexpected end of attribute. Expected length, "".
I/chromium(27118): [INFO:CONSOLE(1)] "Error: <svg> attribute width: Unexpected end of attribute. Expected length, "".", source: https://checkout-static-next.razorpay.com/build/e011af9ce9d609b5ba0de0a2e727307dcc47e708/checkout-frame.modern.js (1)
E/com.razorpay.checkout(27118): Webview JS Error: Error: <svg> attribute height: Unexpected end of attribute. Expected length, "".
I/chromium(27118): [INFO:CONSOLE(1)] "Error: <svg> attribute height: Unexpected end of attribute. Expected length, "".", source: https://checkout-static-next.razorpay.com/build/e011af9ce9d609b5ba0de0a2e727307dcc47e708/checkout-frame.modern.js (1)
E/com.razorpay.checkout(27118): Webview JS Error: Error: <svg> attribute width: Unexpected end of attribute. Expected length, "".
I/chromium(27118): [INFO:CONSOLE(1)] "Error: <svg> attribute width: Unexpected end of attribute. Expected length, "".", source: https://checkout-static-next.razorpay.com/build/e011af9ce9d609b5ba0de0a2e727307dcc47e708/checkout-frame.modern.js (1)
E/com.razorpay.checkout(27118): Webview JS Error: Error: <svg> attribute height: Unexpected end of attribute. Expected length, "".
I/chromium(27118): [INFO:CONSOLE(1)] "Error: <svg> attribute height: Unexpected end of attribute. Expected length, "".", source: https://checkout-static-next.razorpay.com/build/e011af9ce9d609b5ba0de0a2e727307dcc47e708/checkout-frame.modern.js (1)
E/com.razorpay.checkout(27118): Webview JS Error: Error: <svg> attribute width: Unexpected end of attribute. Expected length, "".
I/chromium(27118): [INFO:CONSOLE(1)] "Error: <svg> attribute width: Unexpected end of attribute. Expected length, "".", source: https://checkout-static-next.razorpay.com/build/e011af9ce9d609b5ba0de0a2e727307dcc47e708/checkout-frame.modern.js (1)
E/com.razorpay.checkout(27118): Webview JS Error: Error: <svg> attribute height: Unexpected end of attribute. Expected length, "".
I/chromium(27118): [INFO:CONSOLE(1)] "Error: <svg> attribute height: Unexpected end of attribute. Expected length, "".", source: https://checkout-static-next.razorpay.com/build/e011af9ce9d609b5ba0de0a2e727307dcc47e708/checkout-frame.modern.js (1)
E/com.razorpay.checkout(27118): Webview JS Error: Error: <svg> attribute width: Unexpected end of attribute. Expected length, "".
I/chromium(27118): [INFO:CONSOLE(1)] "Error: <svg> attribute width: Unexpected end of attribute. Expected length, "".", source: https://checkout-static-next.razorpay.com/build/e011af9ce9d609b5ba0de0a2e727307dcc47e708/checkout-frame.modern.js (1)
E/com.razorpay.checkout(27118): Webview JS Error: Error: <svg> attribute height: Unexpected end of attribute. Expected length, "".
I/chromium(27118): [INFO:CONSOLE(1)] "Error: <svg> attribute height: Unexpected end of attribute. Expected length, "".", source: https://checkout-static-next.razorpay.com/build/e011af9ce9d609b5ba0de0a2e727307dcc47e708/checkout-frame.modern.js (1)
E/com.razorpay.checkout(27118): Webview JS Error: Error: <svg> attribute width: Unexpected end of attribute. Expected length, "".
I/chromium(27118): [INFO:CONSOLE(1)] "Error: <svg> attribute width: Unexpected end of attribute. Expected length, "".", source: https://checkout-static-next.razorpay.com/build/e011af9ce9d609b5ba0de0a2e727307dcc47e708/checkout-frame.modern.js (1)
E/com.razorpay.checkout(27118): Webview JS Error: Error: <svg> attribute height: Unexpected end of attribute. Expected length, "".
I/chromium(27118): [INFO:CONSOLE(1)] "Error: <svg> attribute height: Unexpected end of attribute. Expected length, "".", source: https://checkout-static-next.razorpay.com/build/e011af9ce9d609b5ba0de0a2e727307dcc47e708/checkout-frame.modern.js (1)
E/com.razorpay.checkout(27118): Webview JS Error: Error: <svg> attribute width: Unexpected end of attribute. Expected length, "".
I/chromium(27118): [INFO:CONSOLE(1)] "Error: <svg> attribute width: Unexpected end of attribute. Expected length, "".", source: https://checkout-static-next.razorpay.com/build/e011af9ce9d609b5ba0de0a2e727307dcc47e708/checkout-frame.modern.js (1)
E/com.razorpay.checkout(27118): Webview JS Error: Error: <svg> attribute height: Unexpected end of attribute. Expected length, "".
I/chromium(27118): [INFO:CONSOLE(1)] "Error: <svg> attribute height: Unexpected end of attribute. Expected length, "".", source: https://checkout-static-next.razorpay.com/build/e011af9ce9d609b5ba0de0a2e727307dcc47e708/checkout-frame.modern.js (1)
D/AndroidRuntime(27118): Shutting down VM
E/AndroidRuntime(27118): FATAL EXCEPTION: main
E/AndroidRuntime(27118): Process: com.devsig.trustride, PID: 27118
E/AndroidRuntime(27118): java.lang.SecurityException: com.devsig.trustride: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/AndroidRuntime(27118): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3182)
E/AndroidRuntime(27118): 	at android.os.Parcel.createException(Parcel.java:3166)
E/AndroidRuntime(27118): 	at android.os.Parcel.readException(Parcel.java:3149)
E/AndroidRuntime(27118): 	at android.os.Parcel.readException(Parcel.java:3091)
E/AndroidRuntime(27118): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5784)
E/AndroidRuntime(27118): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1853)
E/AndroidRuntime(27118): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1793)
E/AndroidRuntime(27118): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1781)
E/AndroidRuntime(27118): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:756)
E/AndroidRuntime(27118): 	at com.razorpay.CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP(CheckoutPresenterImpl.java:884)
E/AndroidRuntime(27118): 	at com.razorpay.CheckoutPresenterImpl.access$600(CheckoutPresenterImpl.java:59)
E/AndroidRuntime(27118): 	at com.razorpay.G$_X_.onFinish(CheckoutPresenterImpl.java:863)
E/AndroidRuntime(27118): 	at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:142)
E/AndroidRuntime(27118): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(27118): 	at android.os.Looper.loopOnce(Looper.java:232)
E/AndroidRuntime(27118): 	at android.os.Looper.loop(Looper.java:317)
E/AndroidRuntime(27118): 	at android.app.ActivityThread.main(ActivityThread.java:8501)
E/AndroidRuntime(27118): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27118): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(27118): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
W/Sensors (27118): Cannot get virtualdevice_native service
E/FA      (27118): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
W/FirebaseCrashlytics(27118): Timeout exceeded while awaiting app exception callback from Analytics listener.
I/Process (27118): Sending signal. PID: 27118 SIG: 9
Lost connection to device.
the Dart compiler exited unexpectedly.

**Comment by devsigofficial** [comment]
Device Google Pixel 6A

**Comment by vivekshindhe** [comment]
@devsigofficial this issue is resolved from our end a bit ago. If you are still seeing the issue, please reinstall the razorpay-flutter package. This will ensure the latest internal libraries are downloaded. I am closing this ticket. Please feel free to reply to this if the issue is not fixed or create another issue if you are facing any issues. Thank you.
