### ISSUE TITLE
update new dependencies package info plus

### ISSUE THREAD

**Issue by this-sunil** [razorpay/razorpay-flutter#379]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay Flutter plugin release to make sure your issue has not already been fixed: 

## Flutter Version :
Run `flutter version` in your terminal and copy the results here.

## Xcode Version :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.

## Cocoapod Version :
Go to iOS folder > open `podfile.lock` > copy the `razorpay-pod version` and `razorpay_flutter`a version.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by vivekshindhe** [comment]
Hey @this-sunil , [version 1.3.7](https://github.com/razorpay/razorpay-flutter/releases/tag/v1.3.7) was released in razorpay-flutter. We have removed package_info_plus as a dependency so this shouldn't be a blocker anymore. 

Please try with this version. I'll be keeping this ticket open for a while. Please let me know if you are facing any issues with the upgrade.

**Comment by vivekshindhe** [comment]
Closing this ticket. Please reply or raise a new one for any issues faced.

**Comment by this-sunil** [comment]
K
