### ISSUE TITLE
[API Design][No Orders API] Review from a first test

### ISSUE THREAD

**Issue by raveesh-me** [razorpay/razorpay-flutter#4]
Hi! I reviewed the plugin live, as I was trying to implement a client project,
Here are my key findings:

1. Current API surface does not have any way to deal with the orders API
-> PaymentSuccessResponse has only payment_id, not the best way to deal with this
2. Callbacks are good, but we could have designed the API in a little better way(promises / async / await)

I have archived the video, but if interested can make it available.
At the same time, am open to discuss a better API surface.

Bests,
Raveesh.

**Comment by raveesh-me** [comment]
Also using callbacks does not allow you to enforce function signatures either.

**Comment by ChintanAcharya** [comment]
@raveesh-me We'll be adding support for Orders API soon.

**Comment by raveesh-me** [comment]
Thank you, will check out in the next project.

**Comment by ChintanAcharya** [comment]
@raveesh-me Did you get a chance to try it out?
