### ISSUE TITLE
currency is not supported

### ISSUE THREAD

**Issue by haneensaadeh1994** [razorpay/razorpay-flutter#40]
currency is not supported 

`  var options = {
      'key': 'my_key',
      'amount': 399 * 100,
      'name': 'kastana',
      'description': 'test payment',
      'currency': 'USD',
      'prefill': {'contact': '', 'email': ''},
      'external': {
        'wallets': ['']
      }
    };
`

**Comment by haneensaadeh1994** [comment]
![WhatsApp Image 2019-10-25 at 12 53 06 PM-3](https://user-images.githubusercontent.com/41123514/67565827-9e68d880-f726-11e9-8a35-5ed44df44cf5.jpeg)
![WhatsApp Image 2019-10-25 at 12 53 06 PM-2](https://user-images.githubusercontent.com/41123514/67565831-a0cb3280-f726-11e9-94de-c123815bd4d8.jpeg)
![WhatsApp Image 2019-10-25 at 12 53 06 PM](https://user-images.githubusercontent.com/41123514/67565835-a294f600-f726-11e9-8fea-0547aa7431af.jpeg)

Is the test mode related to this error ?

**Comment by ChintanAcharya** [comment]
@haneensaadeh1994 This happens when you are not activated for international payments. Could you head over to https://razorpay.com/support/#request and file a support request for the same?

**Comment by Nautiyalsachin** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a new ticket if you have any additional issues.

**Comment by ansarimhtqms** [comment]
I am getting Error: Invalid currency (The provided currency is not currently supported) only in live site with test credentials for testing.. its working fine in my local system..
