### ISSUE TITLE
 Failed to list versions for com.razorpay:checkout.          > Unable to load Maven meta-data from https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml.             > Could not HEAD 'https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml'. Received status code 500 from server: Internal Server Error

### ISSUE THREAD

**Issue by krishnamadugu** [razorpay/razorpay-flutter#402]
My app is getting blocked with the above mentioned issue it is working fine yestarday but not any more. 

flutter version : 3.22
plugin version : 1.3.7

**Comment by error404sushant** [comment]
Same with my project.
Why Razorpay does not use mavenCentral() ?

**Comment by abhijit-hl** [comment]
Same Issue, Unable to build a project from today morning. It was working fine yesterday.

**Comment by Jeel8120** [comment]
Same Issue **`Could not resolve com.razorpay:checkout:1.6.+.`**

**Comment by krazzylazy** [comment]
Facing same issue!

**Comment by nimesh-devloper** [comment]
Facing the same issue !!!!!

**Comment by murali-cse** [comment]
Facing same issue

**Comment by Jeel8120** [comment]
Manually change `build.gradle` of `razorpay_flutter` 
Change this **`api 'com.razorpay:checkout:1.6.41'`**  instand of **`api 'com.razorpay:checkout:1.6.+'`**

**Comment by vivekshindhe** [comment]
Hey folks, the issue is not with the razorpay-checkout SDK but with mavenCentral. The razorpay-flutter package does not use jcenter. You can verify this [here](https://github.com/razorpay/razorpay-flutter/blob/b/namespace-fix-flutter/android/build.gradle). Also attaching the [link](https://status.maven.org/) to the site which states the outage in OSSRH (mavenCentral) which is why we are seeing this issue. The issue is also different for each because using a specific version has been working for some folks, while it hasn’t for others. You can try to use https://github.com/razorpay/razorpay-flutter/issues/400#issuecomment-2285365867 (Thank you @niladri-raychaudhuri for explaining the steps) fix temporarily to see if that would resolve it for you, while we look into resolving this from our end.

**Comment by krishnamadugu** [comment]
As a temporary fix, could try updating the pub-cache file, till the fix is available
.pub-cache/hosted/pub.dev/razorpay_flutter-1.3.7/android/build.gradle

Under dependencies, change
api 'com.razorpay:checkout:1.6.+'
api 'com.razorpay:checkout:1.6.41'

This has worked for me

android {
    compileSdkVersion 34
   namespace 'com.razorpay.razorpay_flutter'
    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 34
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    dependencies {
        implementation fileTree(dir: 'libs', include: ['*.jar'])
        api 'com.razorpay:checkout:1.6.41'
    }
}
Remember to run flutter clean and rebuild after the change.

**Comment by krishnamadugu** [comment]
> Hey folks, the issue is not with the razorpay-checkout SDK but with mavenCentral. The razorpay-flutter package does not use jcenter. You can verify this [here](https://github.com/razorpay/razorpay-flutter/blob/b/namespace-fix-flutter/android/build.gradle). Also attaching the [link](https://status.maven.org/) to the site which states the outage in OSSRH (mavenCentral) which is why we are seeing this issue. The issue is also different for each because using a specific version has been working for some folks, while it hasn’t for others. You can try to use [#400 (comment)](https://github.com/razorpay/razorpay-flutter/issues/400#issuecomment-2285365867) (Thank you @niladri-raychaudhuri for explaining the steps) fix temporarily to see if that would resolve it for you, while we look into resolving this from our end.

Thank You i guess it will be a temporary fix only till the maven fixes it and let me know if any proper fix found closing this issue for now

**Comment by vivekshindhe** [comment]
Hey folks, seems like the issue on mavenCentral is resolved. You can check the latest status [here](https://status.maven.org/). Please try to run ./gradlew --refresh-dependencies or ./gradle --refresh-dependencies or run Sync project with Gradle files in Android studio when the android project is opened.

**Comment by Sobitandra** [comment]
> As a temporary fix, could try updating the pub-cache file, till the fix is available .pub-cache/hosted/pub.dev/razorpay_flutter-1.3.7/android/build.gradle
> 
> Under dependencies, change api 'com.razorpay:checkout:1.6.+' api 'com.razorpay:checkout:1.6.41'
> 
> This has worked for me
> 
> android { compileSdkVersion 34 namespace 'com.razorpay.razorpay_flutter' defaultConfig { minSdkVersion 19 targetSdkVersion 34 testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner" } lintOptions { disable 'InvalidPackage' } dependencies { implementation fileTree(dir: 'libs', include: ['*.jar']) api 'com.razorpay:checkout:1.6.41' } } Remember to run flutter clean and rebuild after the change.

It works for me as well
