### ISSUE TITLE
Paying via upi does not open the googlepay app instead ask for upi id in the razorpay app

### ISSUE THREAD

**Issue by neeluagrawal04** [razorpay/razorpay-flutter#407]
## Description
Paying via upi does not open the googlepay app instead ask for upi id in the razorpay app while running app in ios application.

After integrating the Razorpay flutter sdk, it will ask for the available payment options, once I am selecting UPi, the user will be re-directed to upi page where it will ask for upi id for the user instead of re-directing to the google pay application which is the feature in android or ios native sdk

## Flutter Version :
 razorpay version: razorpay_flutter: ^1.3.7

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. integrate razorPay sdk> click on purchase cta > it will redirect user to payment options
2. select google pay UPI
3. user will be redirected to UPi asking for upi id

## Expected Results
User should be re-directed to particular google pay application instead of asking user to open upi id

## Snack, code example, screenshot, or link to a repository:
![IMG_0311](https://github.com/user-attachments/assets/46af9914-0b53-4f2c-af12-900eff67cdf4)
![IMG_0312](https://github.com/user-attachments/assets/3a671fe9-8fb3-4157-ba47-85fb71fb7ea2)

**Comment by vivekshindhe** [comment]
@neeluagrawal04 For using UPI Intent flow in iOS, you will need to add the applications in the info.plist file. You can find the details for this, [here](https://razorpay.com/docs/payments/payment-methods/upi/upi-intent#ios-standard-checkout)

**Comment by neeluagrawal04** [comment]
Hi @vivekshindhe since we have already added the details in info.plist like below, but still the razorpay is giving us option to add the upi id instead of moving to the google pay app, and we are using razorPay flutter sdk for ios.
Kindly help here!

<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>tez</string>
		<string>phonepe</string>
		<string>paytmmp</string>
	</array>

**Comment by vishnuprasad0** [comment]
Hi @neeluagrawal04 🙂, hope you’re doing well! I noticed [my issue here](https://github.com/razorpay/razorpay-flutter/issues/407)
 looks quite similar to the one you had raised earlier. Since you closed yours, I was wondering if you found a solution or workaround? Would really appreciate if you could share your experience. Thanks in advance 🙏
