### ISSUE TITLE
Uploading failed to App store and getting this issue.

### ISSUE THREAD

**Issue by shahinnawas** [razorpay/razorpay-flutter#413]
The build completed, but uploading to Transporter the uploading is failed and showed the issue.

Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (4 months ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

Xcode Version :
Version 16.0 (16A242d)

 Cocoapod Version :
  - razorpay-pod (1.3.4)
  - razorpay_flutter (1.1.10):
    - Flutter
    - razorpay-pod

Steps To Reproduce
1. Run flutter build ipa
2. upload the ipa to Transporter Software
3. Deliver the App

## Expected Results
getting this error
Asset validation failed (90482)
Invalid Executable. The executable 'Runner.app/Frameworks/Razorpay.framework/Razorpay' contains bitcode. (ID: 458b08fa-03a6-42ed-9aee-66597110e484)
<img width="632" alt="Screenshot 2024-09-30 at 20 03 45" src="https://github.com/user-attachments/assets/5147b98d-aa0e-4695-a334-108b027cc1c5">

**Comment by Shiba-Kar** [comment]
Change according to Razor pay file location 
```xcrun bitcode_strip /Users/shibaprasadkar/Desktop/Programming/OFFICE/FLUTTER/totempole_vm_flutter/ios/Pods/Mapbox-iOS-SDK/dynamic/Mapbox.framework/Mapbox -r -o /Users/shibaprasadkar/Desktop/Programming/OFFICE/FLUTTER/totempole_vm_flutter/ios/Pods/Mapbox-iOS-SDK/dynamic/Mapbox.framework/Mapbox```

**Comment by shahinnawas** [comment]
This one is worked for me
[https://stackoverflow.com/questions/78993520/invalid-executable-the-executable-appname-app-frameworks-hermes-framework-herm/79000179#79000179](url)

**Comment by wolfxpertlab** [comment]
any solution? above error

**Comment by shahinnawas** [comment]
Yes, paste the code below into handle_bitcode.sh and run the script after ./handle_bitcode.sh

#!/bin/bash

# Function to check if a binary contains bitcode
check_bitcode() {
  local binary_path=$1
  if otool -l "$binary_path" | grep -q __LLVM; then
    echo "$binary_path contains bitcode."
    echo "$binary_path" >> bitcode_frameworks.txt
  else
    echo "$binary_path does not contain bitcode."
  fi
}

# Function to strip bitcode from a binary
strip_bitcode() {
  local binary_path=$1
  local output_path="${binary_path}_stripped"
  xcrun bitcode_strip "$binary_path" -r -o "$output_path"
  echo "Stripped bitcode from $binary_path and saved to $output_path"
}

# Function to replace original binary with the stripped version
replace_framework() {
  local original_path=$1
  local stripped_path="${original_path}_stripped"

  if [ -f "$stripped_path" ]; then
    echo "Replacing $original_path with $stripped_path..."
    rm "$original_path"
    mv "$stripped_path" "$original_path"
    echo "Replaced $original_path successfully."
  else
    echo "Stripped binary $stripped_path not found. Skipping."
  fi
}

# Function to disable Bitcode in the Xcode project
disable_bitcode_in_project() {
  # Automatically detect the Xcode project file
  local xcodeproj_file=$(find . -name "*.xcodeproj" | head -n 1)
  if [ -z "$xcodeproj_file" ]; then
    echo "Xcode project not found. Exiting."
    exit 1
  fi
  local xcodeproj_name=$(basename "$xcodeproj_file" .xcodeproj)

  echo "Disabling Bitcode in Xcode project $xcodeproj_name..."
  /usr/libexec/PlistBuddy -c "Set :buildSettings:ENABLE_BITCODE NO" "$xcodeproj_file/project.pbxproj"

  # Clean and rebuild the Xcode project
  echo "Cleaning the build folder..."
  xcodebuild clean -workspace "$xcodeproj_name.xcworkspace" -scheme "$xcodeproj_name" -configuration Debug

  echo "Building the project..."
  xcodebuild -workspace "$xcodeproj_name.xcworkspace" -scheme "$xcodeproj_name" -configuration Debug

  echo "Process completed successfully!"
}

# Step 1: Check frameworks for Bitcode
echo "Checking frameworks for Bitcode..."

# Remove old bitcode_frameworks.txt if it exists
rm -f bitcode_frameworks.txt

# Check frameworks in Pods and the ios directory
if [ -d "Pods" ]; then
  echo "Checking frameworks in Pods..."
  find Pods -name '*.framework' -type d | while read -r framework; do
    binary_name=$(basename "$framework" .framework)
    binary_path="$framework/$binary_name"
    if [ -f "$binary_path" ]; then
      check_bitcode "$binary_path"
    fi
  done
fi

echo "Checking frameworks in the ios directory..."
find . -name '*.framework' -type d | while read -r framework; do
  binary_name=$(basename "$framework" .framework)
  binary_path="$framework/$binary_name"
  if [ -f "$binary_path" ]; then
    check_bitcode "$binary_path"
  fi
done

echo "Bitcode check completed. Frameworks containing bitcode are listed in bitcode_frameworks.txt."

# Step 2: Strip Bitcode from all frameworks that contain it
if [ -f bitcode_frameworks.txt ]; then
  echo "Stripping bitcode from frameworks..."
  while read -r binary_path; do
    strip_bitcode "$binary_path"
  done < bitcode_frameworks.txt
else
  echo "No frameworks found containing bitcode. Exiting."
  exit 1
fi

# Step 3: Replace original frameworks with stripped versions
echo "Replacing original frameworks with stripped versions..."
while read -r binary_path; do
  replace_framework "$binary_path"
done < bitcode_frameworks.txt

# Step 4: Disable Bitcode in the Xcode project and rebuild
disable_bitcode_in_project

**Comment by shahinnawas** [comment]
Refer this [link]([https://stackoverflow.com/questions/78993520/invalid-executable-the-executable-appname-app-frameworks-hermes-framework-herm/79000179#79000179](https://github.com/razorpay/razorpay-flutter/issues/url))
