### ISSUE TITLE
 Issue with Missing Classes During R8 Minification (ProGuard Annotations)  #android build

### ISSUE THREAD

**Issue by shamnad-sherief** [razorpay/razorpay-flutter#415]
After switching to flutter 3.24, I am experiencing an issue with the Razorpay SDK while building my project with R8 minification enabled. The build fails with the following error related to missing ProGuard annotations:

```
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /<project_location>/build/app/outputs/mapping/release/missing_rules.txt.
ERROR: R8: Missing class proguard.annotation.Keep (referenced from: com.razorpay.AnalyticsEvent and 8 other contexts)
Missing class proguard.annotation.KeepClassMembers (referenced from: com.razorpay.AnalyticsEvent and 8 other contexts)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete
```

It seems that the `com.razorpay.AnalyticsEvent` and other classes are referencing `proguard.annotation.Keep` and `proguard.annotation.KeepClassMembers`, but these classes are not available during the R8 minification process. I have already tried adding ProGuard rules to retain these classes, but the issue persists.

### Steps to Reproduce:
1. Integrate Razorpay SDK into an Android project.
2. Enable R8 minification in the `release` build configuration.
3. Attempt to build the project.

### Environment Details:
- Razorpay SDK version: 1.3.5
- Android Studio version: 2024.1.1 | koala
- Android SDK version: 34
- Gradle  Plugin version: 8.0.2
- Gradle version: 8.1.1
- Kotlin version: 1.8.22

### Additional Information:

Workaround:

To work around the issue, I added additional keep rules that were generated in the following file:
/<project_location>/build/app/outputs/mapping/release/missing_rules.txt

Here are the rules I added to proguard-rules.pro:

```pro

-dontwarn androidx.window.extensions.WindowExtensions
-dontwarn androidx.window.extensions.WindowExtensionsProvider
-dontwarn androidx.window.extensions.area.ExtensionWindowAreaPresentation
-dontwarn androidx.window.extensions.layout.DisplayFeature
-dontwarn androidx.window.extensions.layout.FoldingFeature
-dontwarn androidx.window.extensions.layout.WindowLayoutComponent
-dontwarn androidx.window.extensions.layout.WindowLayoutInfo
-dontwarn androidx.window.sidecar.SidecarDeviceState
-dontwarn androidx.window.sidecar.SidecarDisplayFeature
-dontwarn androidx.window.sidecar.SidecarInterface$SidecarCallback
-dontwarn androidx.window.sidecar.SidecarInterface
-dontwarn androidx.window.sidecar.SidecarProvider
-dontwarn androidx.window.sidecar.SidecarWindowLayoutInfo
-dontwarn proguard.annotation.Keep
-dontwarn proguard.annotation.KeepClassMembers
```

#### Result:

While this workaround allows me to build the project without minification, the app size has significantly increased, **which is not ideal for production.**

**Comment by vivekshindhe** [comment]
@shamnad-sherief Have you added the proguard rules for the Razorpay SDK? 
 You can find these [here](https://razorpay.com/docs/payments/payment-gateway/flutter-integration/standard/build-integration#add-proguard-rules-android-only).

**Comment by shamnad-sherief** [comment]
> @shamnad-sherief Have you added the proguard rules for the Razorpay SDK? You can find these [here](https://razorpay.com/docs/payments/payment-gateway/flutter-integration/standard/build-integration#add-proguard-rules-android-only).


I followed the ProGuard rules provided in the Razorpay documentation, but unfortunately, I didn't see any reduction in the app size. The APK size remains at 82MB, whereas it was only 30MB approx before. It seems like the rules suggested by Razorpay (like -dontwarn com.razorpay.** and -keep class com.razorpay.** {*;}) are functionally similar to the ones I was already using, which came from the missing_rules.txt file generated by R8.

The provided rules ensure that the necessary Razorpay classes and methods are retained, and suppress any warnings, but they don't seem to address the increase in size. Could it be that something else in the SDK or project is contributing to the large APK size? Any further insights or recommendations would be greatly appreciated.

**Comment by sgjesse** [comment]
Using a rule like `-keep class com.razorpay.** {*;}` is not a good solution but more a workaround. The Razorpay team should spend some time to find more precise rules instead of just keeping everything.

The `-dontwarn` rules are not relevant to size but only to suppress warnings for using APIs which are not present in any dependencies.

**Comment by gujjar1988** [comment]
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /development/project/build/app/outputs/mapping/release/missing_rules.txt.
ERROR: R8: Missing class proguard.annotation.Keep (referenced from: com.razorpay.AnalyticsEvent and 8 other contexts)
Missing class proguard.annotation.KeepClassMembers (referenced from: com.razorpay.AnalyticsEvent and 8 other contexts)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 9s
Running Gradle task 'assembleRelease'...                           10.4s
Gradle task assembleRelease failed with exit code 1




I also have same issue

**Comment by gujjar1988** [comment]
Create a file in app folder proguard-rules.pro
in this file write some code below-

 ## Flutter wrapper
 -keep class io.flutter.app.** { *; }
 -keep class io.flutter.plugin.** { *; }
 -keep class io.flutter.util.** { *; }
 -keep class io.flutter.view.** { *; }
 -keep class io.flutter.** { *; }
 -keep class io.flutter.plugins.** { *; }
 -keep class com.google.firebase.** { *; }
 -dontwarn io.flutter.embedding.**
 -ignorewarnings





it's working for me. Thanks

**Comment by shamnad-sherief** [comment]
I am going to close this issue as it can be solved by adding some Android ProGuard rules.
Solution:

Create the file  **android/app/proguard-rules.pro**  if you don't already have one, and add the following rules into it:



```
-keepattributes *Annotation*
-dontwarn com.razorpay.**
-keep class com.razorpay.** {*;}
-optimizations !method/inlining/
-keepclasseswithmembers class * {
  public void onPayment*(...);
}
```


This will solve your issue but may cause an increase in your app size because you are keeping more classes and methods that are not being minified. This happens because these ProGuard rules prevent certain optimizations and class removals that would normally reduce the size of the APK.

You don't need to worry about the app size, as it will reduce after you publish to the Play Store. The Play Store applies additional compression techniques and delivers optimized versions of your app to users based on their device configurations.

**Comment by vivekshindhe** [comment]
> I think it is important for the Razorpay team to find some more targeted rules than blindly keeping all classes with -keep class com.razorpay.** {*;}. Razorpay developers should be able to find the exact places in their code where reflection is used.

Hey @sgjesse ,
We apply proguard to our SDK before deployment. It's not that we are keeping all classes. When the application is building an APK, it'll try to apply proguard to our SDK again. At this point, to let the application's proguard to know to not touch the SDK, these rules are required.

**Comment by sgjesse** [comment]
Just to follow up. Even of the library has been optimized before shipping the client can still benefit from additional shrinking as most clients will not use all features of a library leaving dead code in the app. Please note that a library can include "consumer keep rules", see https://developer.android.com/build/shrink-code#targeted-shrink-rules, so if library users are required to have specific rules you can include these in the AAR/JAR you ship and avoid having to document this additional step to developers using you library. If building with Android Studio there is built in support for `consumerProguardFiles`, see https://developer.android.com/studio/projects/android-library.

**Comment by evocreo70** [comment]
This worked for me adding toandroid\app\proguard-rules.pro

`` Flutter specific rules
-keep class io.flutter.app.** { }
-keep class io.flutter.plugin.* { }
-keep class io.flutter.util.* { }
-keep class io.flutter.view.* { }
-keep class io.flutter.* { }
-keep class io.flutter.plugins.* { }

# Firebase specific rules
-keep class com.google.firebase.* { }

# Razorpay specific rules to prevent ProGuard from removing necessary classes
-keep class com.razorpay.** { *; }
-keep class com.razorpay.**$* { *; }

# Prevent warnings related to Flutter embedding (useful for new Flutter versions)
-dontwarn io.flutter.embedding.*

# Ignore all warnings
-ignorewarnings
``

**Comment by homes-asbl** [comment]
`ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/test/Documents/test/test-mobile-app/build/app/outputs/mapping/devRelease/missing_rules.txt.
ERROR: R8: Missing class java.beans.ConstructorProperties (referenced from: void com.fasterxml.jackson.databind.ext.Java7SupportImpl.<init>() and 2 other contexts)
Missing class java.beans.Transient (referenced from: void com.fasterxml.jackson.databind.ext.Java7SupportImpl.<init>() and 1 other context)
Missing class org.w3c.dom.bootstrap.DOMImplementationRegistry (referenced from: void com.fasterxml.jackson.databind.ext.DOMSerializer.<init>())
Missing class proguard.annotation.Keep (referenced from: com.razorpay.AnalyticsEvent and 8 other contexts)
Missing class proguard.annotation.KeepClassMembers (referenced from: com.razorpay.AnalyticsEvent and 8 other contexts)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyDevReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 11s
Running Gradle task 'assembleDevRelease'...                        11.3s
Gradle task assembleDevRelease failed with exit code 1`

getting this error while trying to build for release

**Comment by shamnad-sherief** [comment]
@homes-asbl  try to read the old comments. The above issue can be solved adding some pro-guard rules

**Comment by TarunPal3551** [comment]
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/tarunpal/StudioProjects/webxpos-flutter-app/build/app/outputs/mapping/release/missing_rules.txt.
ERROR: R8: Missing class proguard.annotation.Keep (referenced from: com.razorpay.AnalyticsEvent and 8 other contexts)
Missing class proguard.annotation.KeepClassMembers (referenced from: com.razorpay.AnalyticsEvent and 8 other contexts)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete

**Flutter Version:**  [✓] Flutter (Channel stable, 3.29.1, on macOS 15.4 24E248 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.3)
[✓] VS Code (version 1.98.2)
[✓] Connected device (4 available)
[✓] Network resources

Razorpay Plugin Version razorpay_flutter: ^1.4.0

Android SDK version: 35
Gradle Plugin version: 8.0.2
Gradle version: 8.9.1
Kotlin version: 2.1.0

I tried adding ProGuard rules and updating dependencies, but the issue persists. Can you please provide any guidance?  
Running Gradle task 'assembleRelease'...    
                    


Thanks!

**Comment by shamnad-sherief** [comment]
> ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/tarunpal/StudioProjects/webxpos-flutter-app/build/app/outputs/mapping/release/missing_rules.txt. ERROR: R8: Missing class proguard.annotation.Keep (referenced from: com.razorpay.AnalyticsEvent and 8 other contexts) Missing class proguard.annotation.KeepClassMembers (referenced from: com.razorpay.AnalyticsEvent and 8 other contexts)
> 
> FAILURE: Build failed with an exception.
> 
>     * What went wrong:
>       Execution failed for task ':app:minifyReleaseWithR8'.
> 
> 
> > A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
> > Compilation failed to complete
> 
> **Flutter Version:** [✓] Flutter (Channel stable, 3.29.1, on macOS 15.4 24E248 darwin-arm64, locale en-IN) [✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [✓] Xcode - develop for iOS and macOS (Xcode 16.2) [✓] Chrome - develop for the web [✓] Android Studio (version 2024.3) [✓] VS Code (version 1.98.2) [✓] Connected device (4 available) [✓] Network resources
> 
> Razorpay Plugin Version razorpay_flutter: ^1.4.0
> 
> Android SDK version: 35 Gradle Plugin version: 8.0.2 Gradle version: 8.9.1 Kotlin version: 2.1.0
> 
> I tried adding ProGuard rules and updating dependencies, but the issue persists. Can you please provide any guidance? Running Gradle task 'assembleRelease'...
> 
> Thanks!

share the rule you have updated and the location.

**Comment by Kevin8160** [comment]
i have tried all but still that will not resolved
