### ISSUE TITLE
App crashes instead of open razorpay payment page in flutter

### ISSUE THREAD

**Issue by yashdabi** [razorpay/razorpay-flutter#42]
`flutter run` is working fine in the emulator and real device.
but after `flutter build apk`, the app **Crashed** on ` _razorpay.open(options);` 
and the plugin is not showing a crash report or any error in the visual studio code terminal.

```
  final _razorpay = Razorpay();
 _razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS, _handlePaymentSuccess);
  _razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, _handlePaymentError);
 _razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET, _handleExternalWallet);

  var options = {
      'key': 'rzp_test_xxxxxxx',
      'amount': 100, //in the smallest currency sub-unit.
      'name': 'Acme Corp.',
      'description': 'Fine T-Shirt',
      'prefill': {'contact': '9123456789', 'email': 'test.kumar@example.com'}
    };

    print('0');
 try {
      print('1');
      _razorpay.open(options);
      print('2');
    } catch (e) {
      print('error');
      debugPrint(e);
    }
```
in the visual studio code terminal

```
11-05 00:22:29.197 21170 21209 I flutter : 0
11-05 00:22:29.197 21170 21209 I flutter : 1
11-05 00:22:29.197 21170 21209 I flutter : 2
```
In the Andoid studio logcat
**java.lang.ClassNotFoundException: Didn't find class "com.razorpay.d__1_"**
```
2019-11-05 11:59:49.168 30159-30159/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.my_task, PID: 30159
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.my_task/com.razorpay.CheckoutActivity}: 
java.lang.ClassNotFoundException: Didn't find class "com.razorpay.d__1_" on path: DexPathList[[zip file "/data/app/com.example.my_task-OX9pWhAo1dl4QP0DQBF58w==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.my_task-OX9pWhAo1dl4QP0DQBF58w==/lib/arm64, /data/app/com.example.my_task-OX9pWhAo1dl4QP0DQBF58w==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.razorpay.d__1_" on path: DexPathList[[zip file "/data/app/com.example.my_task-OX9pWhAo1dl4QP0DQBF58w==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.my_task-OX9pWhAo1dl4QP0DQBF58w==/lib/arm64, /data/app/com.example.my_task-OX9pWhAo1dl4QP0DQBF58w==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.razorpay.Y_$B$.Q_$2$(:1112)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.razorpay.A.<clinit>(:204)
        at com.razorpay.A.a(Unknown Source:0)
        at com.razorpay.c.b(:189)
        at com.razorpay.h.b(:412)
        at com.razorpay.ja.onCreate(:82)
        at com.razorpay.u.onCreate(:23)
        at com.razorpay.CheckoutActivity.onCreate(:8)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
```

**Comment by idkashutosh** [comment]
Same issue with my implementation

**Comment by sharad-paghadal** [comment]
@idkashutosh  try this - https://pub.dev/packages/razorpay_plugin

**Comment by idkashutosh** [comment]
Fixed it by adding the proguard rules in android

**Comment by idkashutosh** [comment]
@yashdabi Try adding proguard rules as shown in razorpay [docs.](https://razorpay.com/docs/payment-gateway/android-integration/standard/) Also if you are doing release build, do sign the apk by following the flutter release build guide [.](https://flutter.dev/docs/deployment/android)

**Comment by yashdabi** [comment]
> @yashdabi Try adding proguard rules as shown in razorpay docs. https://razorpay.com/docs/payment-gateway/android-integration/standard/ Also if you are doing release build, do sign the apk by following the flutter release build guide. https://flutter.dev/docs/deployment/android

@idkashutosh thanks, it's working 
I just following below steps for this solution.

**1 step**
make a file name of **proguard-rules.pro** inside  android>app
that should be : **android/app/proguard-rules.pro**
then paste below code inside proguard-rules.pro file

```
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

-keepattributes JavascriptInterface
-keepattributes *Annotation*

-dontwarn com.razorpay.**
-keep class com.razorpay.** {*;}

-optimizations !method/inlining/*

-keepclasseswithmembers class * {
  public void onPayment*(...);
}
```

**2 step**
go to android>app>build.gradle and find **buildTypes**
inside buildTypes>release add some lines

```
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            minifyEnabled true
            useProguard true 
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```
now Razorpay is working.

**Comment by Vickycp** [comment]
thanks bro

**Comment by yashpaneliya** [comment]
Thank you so much @yashdabi 🚀🚀

**Comment by Sagar6133** [comment]
i m aslo facing same problem and i ahve added proguard rules ... did not worked ..the api key is test key ... it is woring with debug version, not working with release version

can anyone guide please

**Comment by Sagar6133** [comment]
can anyone help please , how it will be fixed

**Comment by sumedht** [comment]
Closing this issue due to no further response. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by adamshamsudeen** [comment]
This issue is still persisting. I think we need to add this to the documentation.

**Comment by adamshamsudeen** [comment]
In the documentation, it says "If you are using proguard for your builds" use the following. But looks like progaurd is necessary, without which I'm getting this error. Can we mention it that way in the documentaion?

**Comment by vijaypareek13** [comment]
I have integrated razorpay in flutter web but facing the same problem. Please anyone here to help me

**Comment by rohan220217** [comment]
I have done everything like I have added progaurd rule and also mentioned in gradle file but still, in production mode, the checkout button becomes an infinite white screen. I am using the test key. Please help!

**Comment by yashdabi** [comment]
@rohan220217 what error is showing in Logcat after opening the Razorpay

**try this to see Logcat messages**
https://stackoverflow.com/questions/58693539/how-to-see-debug-console-when-app-installed-through-apk-in-flutter

**Comment by rohan220217** [comment]
> @rohan220217 what error is showing in Logcat after opening the Razorpay
> 
> **try this to see Logcat messages**
> https://stackoverflow.com/questions/58693539/how-to-see-debug-console-when-app-installed-through-apk-in-flutter

Thank you very much @yashdabi  but I fixed my error while debugging. The checkout button becomes grey infinite screen because I have used incorrect parent widget

**Comment by TusharKhari** [comment]
As I used razor pay plugin today and it showed me some this  signature error  :
* What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_1qfv6up9v4rgk8kbzjky2agc8.android() is applicable for argument types: (build_1qfv6up9v4rgk8kbzjky2agc8$_run_closure2) values: [build_1qfv6up9v4rgk8kbzjky2agc8$_run_closure2@4b270c5a]

so fixed this error by commenting "useProguard true"  in android/app/build.gradle and it worked for me

**Comment by ameenulislam** [comment]
If you tried everything and nothing worked!

Accrording to razorpay docs, you should create an order in the server (probably using an API) before calling payment geteway.
It is important that the **_order_id_** you are sending should match with one you get in response while you created an order earlier

This only applies if you are sending an order_id in your razorpay options

**Comment by sai-phaneesh** [comment]
> > @yashdabi Try adding proguard rules as shown in razorpay docs. https://razorpay.com/docs/payment-gateway/android-integration/standard/ Also if you are doing release build, do sign the apk by following the flutter release build guide. https://flutter.dev/docs/deployment/android
> 
> @idkashutosh thanks, it's working I just following below steps for this solution.
> 
> **1 step** make a file name of **proguard-rules.pro** inside android>app that should be : **android/app/proguard-rules.pro** then paste below code inside proguard-rules.pro file
> 
> ```
> -keepclassmembers class * {
>     @android.webkit.JavascriptInterface <methods>;
> }
> 
> -keepattributes JavascriptInterface
> -keepattributes *Annotation*
> 
> -dontwarn com.razorpay.**
> -keep class com.razorpay.** {*;}
> 
> -optimizations !method/inlining/*
> 
> -keepclasseswithmembers class * {
>   public void onPayment*(...);
> }
> ```
> 
> **2 step** go to android>app>build.gradle and find **buildTypes** inside buildTypes>release add some lines
> 
> ```
>     buildTypes {
>         release {
>             // TODO: Add your own signing config for the release build.
>             // Signing with the debug keys for now, so `flutter run --release` works.
>             signingConfig signingConfigs.debug
>             minifyEnabled true
>             useProguard true 
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
> ```
> 
> now Razorpay is working.

For me removing the useProguard in build.gradle worked properly.
```
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

**Comment by chhand2808** [comment]
> > > @yashdabi Try adding proguard rules as shown in razorpay docs. https://razorpay.com/docs/payment-gateway/android-integration/standard/ Also if you are doing release build, do sign the apk by following the flutter release build guide. https://flutter.dev/docs/deployment/android
> > 
> > 
> > @idkashutosh thanks, it's working I just following below steps for this solution.
> > **1 step** make a file name of **proguard-rules.pro** inside android>app that should be : **android/app/proguard-rules.pro** then paste below code inside proguard-rules.pro file
> > ```
> > -keepclassmembers class * {
> >     @android.webkit.JavascriptInterface <methods>;
> > }
> > 
> > -keepattributes JavascriptInterface
> > -keepattributes *Annotation*
> > 
> > -dontwarn com.razorpay.**
> > -keep class com.razorpay.** {*;}
> > 
> > -optimizations !method/inlining/*
> > 
> > -keepclasseswithmembers class * {
> >   public void onPayment*(...);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **2 step** go to android>app>build.gradle and find **buildTypes** inside buildTypes>release add some lines
> > ```
> >     buildTypes {
> >         release {
> >             // TODO: Add your own signing config for the release build.
> >             // Signing with the debug keys for now, so `flutter run --release` works.
> >             signingConfig signingConfigs.debug
> >             minifyEnabled true
> >             useProguard true 
> >             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > now Razorpay is working.
> 
> For me removing the useProguard in build.gradle worked properly.
> 
> ```
>     buildTypes {
>         release {
>             // TODO: Add your own signing config for the release build.
>             // Signing with the debug keys for now, so `flutter run --release` works.
>             signingConfig signingConfigs.debug
>             minifyEnabled true
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
> ```


This worked for me, great, thanks 👍

**Comment by RushikeshShind** [comment]
i facing app crash in android 16version , but its working in 15version of android 
 razorpay gateway pulgin im, using 1.4.0 flutter_razorpay plugin can anyone have solutioon on this ?
