### ISSUE TITLE
Flutter web support.

### ISSUE THREAD

**Issue by VrajGohil** [razorpay/razorpay-flutter#43]
Is there any possibility to make this available for flutter web?

**Comment by umanghome** [comment]
Have you tried using the regular web integration? https://razorpay.com/docs/payment-gateway/web-integration/

If there are issues with this^, we can look into solving and documenting them.

**Comment by VrajGohil** [comment]
Haven't tried with web integrations, but i think it would be difficult to manage code for web as well as flutter. I'll try and post here if it's possible.

**Comment by max201920** [comment]
How to integrate .js file provided by razorpay into flutter web project?

**Comment by dhimant1990** [comment]
Is this plugin support for **flutter web**? because I had added in my flutter web project, but it's not working for web, but it's running fine in Android. So let me **how to integrate Razorpay for my fluter web project**.

**Comment by jogiji** [comment]
I have done some initial work on this integration using checkout.js I am stuck with one issue where I am not able to bubble up the response to main.dart.

Please have a look at this repo. FYI its a very dirty Implementation but works except for above issue.
https://github.com/getparking/razorpay_web_flutter

**Comment by ayush97123** [comment]
I am also having issue with flutter web. I have implemented everything. But the razorpay pop up screen is not coming on this line razorpay.open(options); 

And also there is no error also.

**Comment by withdurrani** [comment]
Even I am not able to use the razor pay to the flutter web. Is there any fix coming up for this?

**Comment by ayush97123** [comment]
> Even I am not able to use the razor pay to the flutter web. Is there any fix coming up for this?

I have written to razorpay team but no response yet.

**Comment by jogiji** [comment]
I have done an implementation using web. I have just one problem of passing dart function through platform channel.

**Comment by abhinavsingh** [comment]
Wondering if this is on the radar?  Gave it a try, works well for Android but fails on web.

```
Overflow on channel: razorpay_flutter.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
error @ html_dart2js.dart:39900
_printDebugString @ natives.dart:23
_printDebug @ natives.dart:15
push @ channel_buffers.dart:145
handlePlatformMessage @ plugin_registry.dart:84
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
handlePlatformMessage @ plugin_registry.dart:76
[_sendPlatformMessage] @ window.dart:629
sendPlatformMessage @ window.dart:458
[_sendPlatformMessage] @ binding.dart:246
send @ binding.dart:284
_invokeMethod @ platform_channel.dart:151
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
[_invokeMethod] @ platform_channel.dart:149
invokeMethod @ platform_channel.dart:334
open @ razorpay_flutter.dart:48
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
open @ razorpay_flutter.dart:34
(anonymous) @ pay.dart:56
[_handleTap] @ ink_well.dart:992
(anonymous) @ ink_well.dart:1083
invokeCallback @ recognizer.dart:184
handleTapUp @ tap.dart:523
[_checkUp] @ tap.dart:284
handlePrimaryPointer @ tap.dart:219
handleEvent @ recognizer.dart:477
[_dispatch] @ pointer_router.dart:78
(anonymous) @ pointer_router.dart:124
forEach @ linked_hash_map.dart:21
[_dispatchEventToRoutes] @ pointer_router.dart:126
route @ pointer_router.dart:112
handleEvent @ binding.dart:220
dispatchEvent @ binding.dart:200
[_handlePointerEvent] @ binding.dart:158
[_flushPointerEventQueue] @ binding.dart:104
[_handlePointerDataPacket] @ binding.dart:87
_invoke1 @ window.dart:771
invokeOnPointerDataPacket @ window.dart:373
[_onPointerData] @ pointer_binding.dart:129
(anonymous) @ pointer_binding.dart:479
(anonymous) @ pointer_binding.dart:440
(anonymous) @ pointer_binding.dart:210
Show 15 more frames
errors.dart:164 Uncaught (in promise) Error: MissingPluginException(No implementation found for method open on channel razorpay_flutter)
```

**Comment by subhendupsingh** [comment]
Integrated this using iFrameElement as view factory and JavaScript interop. Wrote an article on this

https://medium.com/@sps.1431990/flutter-web-razorpay-payment-gateway-integration-792d6e015409

**Comment by appventor** [comment]
+1 for this. Can you give us a timeline on when this plugin will support flutter web, I've a requirement with integration for flutter web.

**Comment by ayush97123** [comment]
> +1 for this. Can you give us a timeline on when this plugin will support flutter web, I've a requirement with integration for flutter web.

I have implemented it using razorpay web integration and using js interop library to call javascript function from dart. It works quite well.

**Comment by raveesh-me** [comment]
+1 on this. I'd also like to see the repo to have some federation for stability purposes. Our company is willing to post a PR with enhancements to this plugin if needed.

**Comment by Adityavns** [comment]
+1

**Comment by sumedht** [comment]
Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by vijaypareek13** [comment]
@subhendupsingh 
I have tested your integration, it is working in debug mode but failed in release mode. I have contacted the same Razorpay team but they also unable to solve this problem.

**Comment by fahadahmadansari111** [comment]
Are we getting the web support anytime?

**Comment by KartikShrivastava** [comment]
This medium article explains whole razorpay web-integration with flutter-web https://vermahitesh.medium.com/razorpay-integration-in-flutter-web-a00dbc56bd17.
I've tested it in release as well and it's working well so far.

**Comment by GauravCalidig** [comment]
https://pub.dev/packages/razorpay_web You Can use this till the official one starts supporting
