### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.2 compiler: /Users/sailaja/Desktop/Eemos/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/arm64.swiftmodule

### ISSUE THREAD

**Issue by kingglov** [razorpay/razorpay-flutter#44]
error while importing 

Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.2 compiler: /Users/sailaja/Desktop/Eemos/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/arm64.swiftmodule

**Comment by sharad-paghadal** [comment]
try this - https://pub.dev/packages/razorpay_plugin

**Comment by kingglov** [comment]
> https://pub.dev/packages/razorpay_plugin

thanks for reply . But i am facing issue with xcode. is there any solution for that please let me know bro. thanks in advance

**Comment by nimi0112** [comment]
@kingglov  Did you resolved this issue ?

**Comment by Nautiyalsachin** [comment]
@kingglov, @nimi0112: Can you guys try to reinstall the Razorpay package.
