### ISSUE TITLE
razorpay_flutter issue

### ISSUE THREAD

**Issue by Mallika-Tung** [razorpay/razorpay-flutter#45]
I have implemented razorpay_flutter.It is working fine in android .But in ios ,when i making bitcode enable then other libraries are effecting.How to fix these one?

**Comment by LOG-TAG** [comment]
got any solution ?

**Comment by Nautiyalsachin** [comment]
@Mallika-Tung , @LOG-TAG : We are only supporting bitcode enabled projects now. You can ask other merchants to make it in enabled bitcode format. As it is highly recommended by Apple for iOS apps. for more info - https://help.apple.com/xcode/mac/current/#/devbbdc5ce4f.

**Comment by Nautiyalsachin** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a
new issue if you have any additional queries

**Comment by Renatinaveen** [comment]
When i enable bitcode it doesn't build. Any solution?

**Comment by Nautiyalsachin** [comment]
@Renatinaveen: What is the error you are seeing, any screenshot will help.  Thanks.

**Comment by Renatinaveen** [comment]
@Nautiyalsachin 
The process mentioned in razorpay documentation on how to enable the bitcode is by changing to YES when i do that the other plugins are getting i guess. so what i have done was in podfile it's NO only  but i have followed this https://github.com/flutter/flutter/wiki/Creating-an-iOS-Bitcode-enabled-app will this be okay?

**Comment by Nautiyalsachin** [comment]
@Renatinaveen: Yes, the process mention is correct 🙂. If you are getting an error from other plugins that don't support Bitcode then please ask them to share a Bitcode enabled plugin.
