### ISSUE TITLE
[BUG] contact and email fields are cached

### ISSUE THREAD

**Issue by shashikantshaale** [razorpay/razorpay-flutter#50]
Razorpay caches contact and email fields, calling Razorpay.open with different contact or email  in options does not reflect in the checkout screen. It shows the one called in previous request.

I've been passing like below:
```
      'prefill': {
        'name': user.name,
        'email': user.email,
        'contact': user.phone
      },
      'readonly': {'email': true, 'contact': true},
```

**Comment by ashutoshsingh05** [comment]
Disposing of the instance of `Razorpay` might help. You can try `_razorpay.clear()` in your dispose method when you want it to reset.

**Comment by sumedht** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
