### ISSUE TITLE
Currency not supported error

### ISSUE THREAD

**Issue by VickySalunkhe** [razorpay/razorpay-flutter#53]
When I switched the option for **currency** to **USD**
and when I proceed to pay.
**payment fails** and then **error pops up** as **`currency not supported`**

refer the image
![image](https://user-images.githubusercontent.com/37410248/76309570-0cd3bf00-62f3-11ea-866a-606f16b60b9c.png)

I am using **test version** of razor pay
My options looks like shown below
```
options = {
      'key': ConstantValues.getGatewayTestKey(),
      'amount': 100,
      'currency': 'USD', // INR
      'name': 'XXXX',
      'description': 'XXXX',
      'prefill': {'contact': _phone, 'email': _email},
      'external': {
        'wallets': ['paytm']
      }
```

I have used all test cards numbers mentioned for international payments.

have no issue with Domestic payment (in testing phase)

plz have a look and help me resolve the issue.

Thank you :)

**Comment by sumedht** [comment]
We are not supporting other currency than INR for SDK right now. Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by devSajan** [comment]
getting test env error for INR as well
