### ISSUE TITLE
PlatformException after implementing firebase messaging in app

### ISSUE THREAD

**Issue by kpss01** [razorpay/razorpay-flutter#54]
StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 6264): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 6264): <asynchronous suspension>
E/flutter ( 6264): #2      Razorpay.open (package:nemar_app/RazorPay.dart:48:35)
E/flutter ( 6264): #3      _CheckRazorState.payData (package:nemar_app/checkRazor.dart:17:17)
E/flutter ( 6264): #4      _CheckRazorState.build (package:nemar_app/checkRazor.dart:92:19)
E/flutter ( 6264): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
E/flutter ( 6264): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
E/flutter ( 6264): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 6264): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 6264): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter ( 6264): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 6264): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 6264): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 6264): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 6264): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 6264): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 6264): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 6264): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 6264): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 6264): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 6264): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 6264): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 6264): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 6264): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 6264): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 6264): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 6264): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 6264): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 6264): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 6264): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 6264): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 6264): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter ( 6264): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 6264): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 6264): #34     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551:32)
E/flutter ( 6264): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 6264): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 6264): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 6264): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 6264): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 6264): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter ( 6264): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 6264): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 6264): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 6264): #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets

**Comment by sumedht** [comment]
We have updated flutter framework in our new SDK version. please update to the latest version of SDK. Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
