### ISSUE TITLE
Loader does not show before opening razorpay checkout

### ISSUE THREAD

**Issue by PoojaB26** [razorpay/razorpay-flutter#55]
Currently it is stuck on a complete blank screen before opening the razorpay checkout page and there is no loader. User might think the screen is frozen. 

Any way to implement the loader?

**Comment by Nautiyalsachin** [comment]
Hi @PoojaB26, please update to the latest version of Razorpay flutter plugin v1.1.3. We have resolved this error in the latest release. Closing this issue for now, feel free to reopen it. Thanks!

**Comment by PoojaB26** [comment]
@Nautiyalsachin Do we need to add something to make this work? Still can't see the loader, only a blank screen before checkout page opens.
