### ISSUE TITLE
Paytm Wallet Integration

### ISSUE THREAD

**Issue by HardikkMadaan** [razorpay/razorpay-flutter#56]
How do i make the app open Paytm to complete the Payment and come back to RazorPay after Successful Payment. In Nutshell, how do i integrate Paytm Wallet ?
Thank You

**Comment by Nautiyalsachin** [comment]
Hi @HardikkMadaan, I would suggest you to refer [this Documentation](https://razorpay.com/docs/payment-methods/wallets/external-wallets/), also for more details please send a mail to support@razorpay.com for more details.
