### ISSUE TITLE
react native flipperkitnetwork plugin not found for architecture arm7

### ISSUE THREAD

**Issue by akashjacob** [razorpay/razorpay-flutter#58]
I am working on 0.62 version. Not able to archive. It gives the Flipper error.

![Screenshot 2020-04-03 at 12 42 48 PM](https://user-images.githubusercontent.com/20949239/78334086-bf243c80-75a8-11ea-8029-9d8642a1f33a.png)

**Comment by Nautiyalsachin** [comment]
Hi @akashjacob, you have raised this issue in wrong repository, closing this issue for now. 

Feel free to connect with us on support@razorpay.com. 

Thanks!
