### ISSUE TITLE
RazorPay 1.1.3 -  Build Failing Yet Again on Xcode 11.4

### ISSUE THREAD

**Issue by superhumang** [razorpay/razorpay-flutter#62]
** BUILD FAILED **
Xcode's output:
↳
Command CompileSwift failed with a nonzero exit code
/Users/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.1.3/ios/Classes/RazorpayDelegate.swift:4:42: error:
'RazorpayPaymentCompletionProtocolWithData' is unavailable: cannot find Swift declaration for this protocol
public class RazorpayDelegate: NSObject, RazorpayPaymentCompletionProtocolWithData, ExternalWalletSelectionProtocol {
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Razorpay.RazorpayPaymentCompletionProtocolWithData:2:17: note: 'RazorpayPaymentCompletionProtocolWithData' has been explicitly marked unavailable here
public protocol RazorpayPaymentCompletionProtocolWithData {
^
/Users/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.1.3/ios/Classes/RazorpayDelegate.swift:4:85: error:
'ExternalWalletSelectionProtocol' is unavailable: cannot find Swift declaration for this protocol
public class RazorpayDelegate: NSObject, RazorpayPaymentCompletionProtocolWithData, ExternalWalletSelectionProtocol {
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Razorpay.ExternalWalletSelectionProtocol:2:17: note: 'ExternalWalletSelectionProtocol' has been explicitly marked unavailable here
public protocol ExternalWalletSelectionProtocol {
^
/Users/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.1.3/ios/Classes/RazorpayDelegate.swift:57:24: error: use of
unresolved identifier 'RazorpayCheckout'
let razorpay = RazorpayCheckout.initWithKey(key ?? "", andDelegateWithData: self)
^~~~~~~~~~~~~~~~
note: Using new build system
note: Building targets in parallel
note: Planning build

**Comment by Nautiyalsachin** [comment]
Hi @superhumang, can you tell me the razorpay-pod version from podfile.lock? If that is **1.1.4** then please run a `pod update` from your **ios** folder. It should be **1.1.5**.

**Comment by superhumang** [comment]
Successfully able to build now, thanks
