### ISSUE TITLE
_razorpay.open(options); gives an error

### ISSUE THREAD

**Issue by sandippilake** [razorpay/razorpay-flutter#64]
I am getting following error @ _razorpay.open(options);

Exception has occurred.
PlatformException (PlatformException(error, Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference, null))

I tried few other tutorials of razorpay plugin and I am facing the same issue everywhere
Can someone please help?

**Comment by sumedht** [comment]
@sandippilake working on fixing this issue. Will update u once we fixed this issue.

**Comment by sandippilake** [comment]
Thanks a lot

**Comment by spiderwebsatara** [comment]
Any update ?

**Comment by prashantspandey** [comment]
Hi any updates on this? Please fix it quickly.

**Comment by bihanikeshav** [comment]
Hey, facing the same issue any solutions yet? When I clone this repo everything works fine, but when I try to integrate it this same error.

**Comment by prashantspandey** [comment]
Hi I found the cause of this error:
In my MainActivity.java
GeneratedPluginRegistrant.registerWith(flutterEngine); 
is commented out  because one of the other packages requires me to do so.
But when I am un-commenting the above line . options works properly.
Can you please fix this because un-commenting will make my other plugin not work.

**Comment by harshsoni1110** [comment]
Facing same issue, anyone has a workaround?

**Comment by harshsoni1110** [comment]
Flutter sdk upgrade to 1.17.0 solves the issue.

**Comment by pinkeshAubergine** [comment]
> Flutter sdk upgrade to 1.17.0 solves the issue.

@sandippilake @ChinmayaRazorpay @ChintanAcharya

**Comment by sumedht** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
