### ISSUE TITLE
Support for Razorpay Subscriptions

### ISSUE THREAD

**Issue by ravipiplani** [razorpay/razorpay-flutter#65]
I am not able to find any support for Razorpay subscriptions in this plugin. Is is planned for any future update or is there any workaround available for the same in the current plugin which I might have missed. Please guide. Thanks

**Comment by DeveloperWaybee** [comment]
Anyone please reply on this issue because subscriptions are also a great feature of Razorpay. It would be great if we have that feature as well.

**Comment by Anmol92verma** [comment]
don't we have subscriptions ?

**Comment by sumedht** [comment]
@razorpay/techpgintegrations

**Comment by sumedht** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by Jai05-techie** [comment]
Facing same issue not able to do Subscriptions payment ? 

Any workaround found for this ? plz update here.
