### ISSUE TITLE
iOS App not building - module 'Razorpay' has no member named 'initWithKey'

### ISSUE THREAD

**Issue by githubaamod** [razorpay/razorpay-flutter#66]
Hello All,

Yesterday i run pod update in my flutter project , after which it has started giving me this below error, if i remove razor-pay plugin then App is building properly for iOS.
I am using  razorpay_flutter: 1.1.2
Thankfully my app was submitted to App Store before updating. App was building successfully till i run pod update.

Please help.

Developer/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.1.2/ios/Classes/RazorpayDelegate.swift:57:24: error: module 'Razorpay' has no member named 'initWithKey'
            let razorpay = Razorpay.initWithKey(key ?? "", andDelegateWithData: self)
                           ^~~~~~~~ ~~~~~~~~~~~
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description

Thanks in advance.

**Comment by Nautiyalsachin** [comment]
@githubaamod, I can see you are using `razorpay_flutter: 1.1.2`, we have updated our flutter package version to `razorpay_flutter: 1.1.3` as it's mentioned on Readme. 

Also, can you point me from where you have picked it 1.1.2? As I will be updating it there too.

**Comment by githubaamod** [comment]
Hello ,

Thanks for reply. If i update version in yaml file to 1.1.3 then my build is stopping at pod install.
below is the error.

  - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `razorpay_flutter` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute
    set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_validator.rb:125:in `verify_swift_pods_swift_version'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_validator.rb:39:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:590:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:158:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Just now i build APK for android. My APK was built successfully but app crashing when i open page which uses RazorPay.

Thanks.

**Comment by githubaamod** [comment]
hello ,

Android working fine. Issue was solved by adding proguard-rules.pro file.
Now only iOS issue pending.

Thanks

**Comment by githubaamod** [comment]
Hello ,

My issue is solved by doing below step.
https://github.com/kiwi-bop/flutter_crashlytics/issues/22#issuecomment-508930744

i added ENV['SWIFT_VERSION'] = '5' at the start of my podfile. After this i did pod update and the my iOS code is building successfully.

Thank you
Closing this issue now.
