### ISSUE TITLE
Module 'razorpay_flutter' not found 

### ISSUE THREAD

**Issue by AkshayNG** [razorpay/razorpay-flutter#67]
I've just added RazorPay to my flutter module (add-to-app) in pubspec.yaml file:
> razorpay_flutter: ^1.1.3

When I run the iOS app from Xcode, I'm getting `Module 'razorpay_flutter' not found` in GeneratedPluginRegistrant.h file. I'm not sure whats going wrong,  guess there is an issue when we add flutter as module to the existing native app.

 ![Screenshot 2020-04-25 at 9 04 14 PM](https://user-images.githubusercontent.com/15035623/80283853-7a6b6b80-8738-11ea-97fb-f94674ebc5e6.png)

**Comment by Nautiyalsachin** [comment]
Can you share your XCode version here, also please share the steps you followed, so that I can re-create the same issue here.

**Comment by AkshayNG** [comment]
@Nautiyalsachin Sorry for the late.

Xcode version I'm using : 11.4 (but issue is there on older versions as well such as v11.3 and v10.3)

One more thing: When I run the `package get` from pubspec.yaml file, caught the following warning in android studio console:

```
Running "flutter pub get" in lib_smazing...                         
The plugin `razorpay_flutter` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. 
It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.
```

Flutter Doctor O/P:

![Screenshot 2020-05-04 at 3 32 29 PM](https://user-images.githubusercontent.com/15035623/80955208-8633ed80-8e1c-11ea-86b0-ef1701e8722c.png)

**Comment by AkshayNG** [comment]
This is not razorpay specific issue as I was getting the same error with few other packages too, such as url_launcher and  webview_flutter.

After few trial and error I found simply running `pod install` on iOS project (to which flutter module is added) fixed the issue.

**Comment by iamdipanshusingh** [comment]
Hey @Nautiyalsachin, could you please reopen this issue getting the same issue in razorpay 1.1.5

have attached the screenshot for the issue and flutter doctor as well... I'm using vscode and xcode only for the ios build... so, android sdk can be ignored... LMK if any further input is required

![](https://files.slack.com/files-pri/TD54N3MQA-F01CPLQB7A8/screenshot_2020-10-13_at_9.29.39_am.png)
![](https://files.slack.com/files-pri/TD54N3MQA-F01CHN1GYPM/screenshot_2020-10-13_at_9.31.36_am.png)

**Comment by Nautiyalsachin** [comment]
@iamdipanshusingh,  Can you share the razorpay-pod version, it will be mentioned in your podfile.lock.

**Comment by iamdipanshusingh** [comment]
@Nautiyalsachin it's 1.1.5

**Comment by Nautiyalsachin** [comment]
@iamdipanshusingh Try running pod update, this will update it to the latest version.

**Comment by iamdipanshusingh** [comment]
@Nautiyalsachin updated the dependency, my OS, and xcode as well... still no luck... :sweat_smile: I've even tried solutions from other similar issues... but nothing is working out for me...
plz help me figure out what's wrong here...

**Comment by Nautiyalsachin** [comment]
@iamdipanshusingh, Try creating a new sample app or use this [example](https://github.com/razorpay/razorpay-flutter/tree/master/example).

**Comment by iamdipanshusingh** [comment]
@Nautiyalsachin I had actually updated the Podfile manually due to some other package... have fixed it.. thnx for the help :slightly_smiling_face:
