### ISSUE TITLE
Error while adding in ios

### ISSUE THREAD

**Issue by achinverma** [razorpay/razorpay-flutter#68]
HI,
I am getting the below error while compiling the code for ios. Please, anyone, guide me on how to fix this.
![Screenshot 2020-04-27 at 12 49 00 PM](https://user-images.githubusercontent.com/2811593/80698752-88363d80-8af8-11ea-8044-cecf24463fd8.png)

**Comment by Nautiyalsachin** [comment]
Can you tell me the supported version mentioned in your podfile?

**Comment by achinverma** [comment]
i am using razorpay_flutter: ^1.1.3.

**Comment by achinverma** [comment]
@Nautiyalsachin , @asldevi , @ace03uec , @captn3m0 , anyone knows the solutions for this issue.
on android, it is working fine.

**Comment by Nautiyalsachin** [comment]
@achinverma, please update your pod dependency as mentioned  [here](https://github.com/razorpay/razorpay-flutter#cocoapods-could-not-find-compatible-versions-for-pod-razorpay_flutter-when-running-pod-install) in the readme. 

Let me know if it still doesn't fix the issue.
