### ISSUE TITLE
Please update your documentation to add "timeout" key in options

### ISSUE THREAD

**Issue by manishvill** [razorpay/razorpay-flutter#69]
Please update this, because it is not available in any razorpay flutter SDK API Documentation 

    var options = {
      'key': '<YOUR_KEY_HERE>',
      'amount': 100,
      'name': 'Acme Corp.',
      'description': 'Fine T-Shirt',
      'timeout': 60 //in seconds
      'prefill': {
         'contact': '8888888888',
         'email': 'test@razorpay.com'
       }
    };

**Comment by sumedht** [comment]
https://razorpay.com/docs/payment-gateway/android-integration/standard/#timeouts
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
