### ISSUE TITLE
_handlePaymentError not called after setting timeout in options

### ISSUE THREAD

**Issue by manishvill** [razorpay/razorpay-flutter#70]
After setting timeout in options variable 

     options = {
                "key": APIEndPoint.RAZORPAY_KEY,
                "amount": createOrderModel.amount,
                "currency": "INR",
                "name": APIEndPoint.RAZORPAY_NAME,
                "order_id": createOrderModel.id,
                "timeout" : 60*5,
              };

it does not call _handlePaymentError method on timeout completion and shows plain white screen. 
it does not even pops using 

     Navigator.pop(context);     //not popping that white screen

**Comment by EffyCoder** [comment]
@manishvill were you able to solve this issue?

**Comment by sumedht** [comment]
please update to our latest SDK version
Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by patelpathik** [comment]
@manishvill you got this issue fixed?
I experience same behaviour in my case.
After timeout there's just white screen.
When I press back button (after white screen) error handler becomes active.
Error handler suggests error code 2 with msg "Payment cancelled", ideally it should be regarding _timeout_
