### ISSUE TITLE
No implementation found for method resync on channel razorpay_flutter

### ISSUE THREAD

**Issue by Sathi789888** [razorpay/razorpay-flutter#75]
No implementation found for method resync on channel razorpay_flutter

## Description
We upgrade razorpay_flutter: ^1.1.4 and we faced the issue Razorpay Build failed (razorpay_flutter: 1.1.4) and resolved as per the issue id #74 and then we are getting another issue. see below:

>[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method resync on channel razorpay_flutter)
      
## Flutter Version :
version-1.15.17

## Steps To Reproduce
Install the latest version of razorpay_flutter

## Expected Results
The app works just fine with the razorpay_flutter version 1.1.3, something in 1.1.4 is breaking it

**Comment by SoorajSoman** [comment]
Hi @Sathi789888  ,
Is this a gradle sync error or a runtime error? could you please explain scenario .

**Comment by Sathi789888** [comment]
This is a runtime error and we tried to solve got an another error
`>"Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.5.16&library=checkoutjs&platform=android (1)
`
And also otp not send

**Comment by hiteshgarg002** [comment]
@Sathi789888 have you got

> 
> 
> This is a runtime error and we tried to solve got an another error
> `>"Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.5.16&library=checkoutjs&platform=android (1) `
> And also otp not send

@Sathi789888 have you got any solution for the same?

**Comment by Alok81234881** [comment]
I have same issue. How can i solve this

**Comment by Alok81234881** [comment]
Have anyone got any solution for the same?

I am getting this run time error after adding the flutter screen in my existing ios app.

**Comment by vishal-android-freak** [comment]
on iOS `resync()` should just succeed as it doesn't have any implementation in iOS. Use the master branch.

**Comment by dinesh-ant** [comment]
same issue, any solution?

**Comment by sumedht** [comment]
Update to our latest version if SDK
Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by oyyarko** [comment]
I am getting the same issue, even in the new stable package. although it was working fine in previous versions, but now it is stopped to work in that too.

**Comment by abhay1205** [comment]
same issue here, please tell how to solve this

**Comment by oyyarko** [comment]
> same issue here, please tell how to solve this

I used 1.1.1 razorpay version. Without ^ sign. And also added proground rules. It worked

**Comment by lomadapraveenreddy** [comment]
@sumedht, I am still facing the issue. Any help?
