### ISSUE TITLE
Build issue with razorpay_flutter: ^1.1.4

### ISSUE THREAD

**Issue by arunbapi1** [razorpay/razorpay-flutter#79]
After changing my flutter version to 1.1.4 i a not able to build my app. it's giving below error to me:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':razorpay_flutter'.
> Could not open cp_proj remapped class cache for eii7mfeilb85f6s74q7cms80e (C:\Users\Jiwan\.gradle\caches\5.6.2\scripts-remapped\build_2p07hukjw9b2pcsg12o0ijqma\eii7mfeilb85f6s74q7cms80e\cp_proj40e7ec637808a9c747559d26950b1d9b).
   > Could not open cp_proj generic class cache for build file 'C:\Users\Jiwan\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\razorpay_flutter-1.1.4\android\build.gradle' (C:\Users\Jiwan\.gradle\caches\5.6.2\scripts\eii7mfeilb85f6s74q7cms80e\cp_proj\cp_proj40e7ec637808a9c747559d26950b1d9b).
      > Build file 'C:\Users\Jiwan\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\razorpay_flutter-1.1.4\android\build.gradle' should not contain a package statement.
> Could not get unknown property 'android' for project ':razorpay_flutter' of type org.gradle.api.Project.

**Comment by sendtomitesh** [comment]
yes. same error to me as well on android

**Comment by rahuldange09** [comment]
until fixes revert it back to v1.1.2

**Comment by kishanhitk** [comment]
I am also facing the exact same issue.

**Comment by muhsinzyne** [comment]
@sendtomitesh  @kishanhitk  @rahuldange09  

any solutions found so far ?

**Comment by arunbapi1** [comment]
I resolved this issue. If you can see my first post where i had mentioned the error message from that if you can look into this line "C:\Users\Jiwan\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\razorpay_flutter-1.1.4\android\build.gradle'" you can go to this path except u can change the username "Jiwan" to your username and delete the first line "package android". 

It will work fine.

**Comment by muhsinzyne** [comment]
> I resolved this issue. If you can see my first post where i had mentioned the error message from that if you can look into this line "C:\Users\Jiwan\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\razorpay_flutter-1.1.4\android\build.gradle'" you can go to this path except u can change the username "Jiwan" to your username and delete the first line "package android".

when I tried I am getting some errors like 

FAILURE: Build failed with an exception.

* Where:
Script '/Users/muhsinzyne/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> BaseFlutterTask$_buildBundle_closure2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by rahuldange09** [comment]
> @sendtomitesh @kishanhitk @rahuldange09
> 
> any solutions found so far ?

Why i want never
Revet back to verison 1.1.2

**Comment by winterprogram** [comment]
No podspec found for `razorpay_flutter` in `.symlinks/plugins/razorpay_flutter/ios`
Issue while building ios

**Comment by sumedht** [comment]
Update to the latest version of Razorpay SDK, it will work fine. Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by Salam-pc** [comment]
Hi im getting the same error now

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':razorpay_flutter'.
> Could not load compiled classes for build file 'C:\Users\BFLY\AppData\Local\Pub\Cache\hosted\pub.dev\razorpay_flutter-1.3.4\android\build.gradle' from cache.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':razorpay_flutter' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':fluttertoast'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not find method implementation() for arguments [project ':package_info_plus'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not get unknown property 'android' for project ':razorpay_flutter' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Exception: Gradle task assembleDebug failed with exit code 1

this is the error 

And here is my flutter doc result 

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.6, on Microsoft Windows [Version 10.0.19044.2846], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.6)  
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.77.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

Please let me know if any of you can help me
