### ISSUE TITLE
Flutter i am not able to take build on Android, the plugin is perfectly working fine with IOS part

### ISSUE THREAD

**Issue by muhsinzyne** [razorpay/razorpay-flutter#82]
* What went wrong:
A problem occurred configuring project ':razorpay_flutter'.
> Could not open cp_proj remapped class cache for 8cr7in8w6gkp9f1he0f9femku (/Users/muhsinzyne/.gradle/caches/4.10.2/scripts-remapped/build_89b5pktjowec26ehmcdxho7i3/8cr7in8w6gkp9f1he0f9femku/cp_proj70b1361a260e0ceb212a59c45f680ebd).
   > Could not open cp_proj generic class cache for build file '/Users/muhsinzyne/development/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.1.4/android/build.gradle' (/Users/muhsinzyne/.gradle/caches/4.10.2/scripts/8cr7in8w6gkp9f1he0f9femku/cp_proj/cp_proj70b1361a260e0ceb212a59c45f680ebd).
      > Build file '/Users/muhsinzyne/development/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.1.4/android/build.gradle' should not contain a package statement.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

**Comment by shivangg66** [comment]
I am having the same issue

**Comment by AmanStreak** [comment]
I also having the same issue

**Comment by AmanStreak** [comment]
Go to this location-> Fluttersdk(where you installed the flutter sdk)/.pub-cache\hosted\pub.dartlang.org\razorpay_flutter-1.1.4\android.

then open build.gradle and remove package android.

That works for me!

I've seen this solution on previous threads.

**Comment by shivangg66** [comment]
> Go to this location-> Fluttersdk(where you installed the flutter sdk)/.pub-cache\hosted\pub.dartlang.org\razorpay_flutter-1.1.4\android.
> 
> then open build.gradle and remove package android.
> 
> That works for me!
> 
> I've seen this solution on previous threads.

Thank you so much. You solution worked.

**Comment by hrazad** [comment]
> > Go to this location-> Fluttersdk(where you installed the flutter sdk)/.pub-cache\hosted\pub.dartlang.org\razorpay_flutter-1.1.4\android.
> > then open build.gradle and remove package android.
> > That works for me!
> > I've seen this solution on previous threads.
> 
> I dont have this file razorpay_flutter-1.1.4\ what to do now the error still there

me to
