### ISSUE TITLE
when run the project i got this error

### ISSUE THREAD

**Issue by shailendra-rajpoot** [razorpay/razorpay-flutter#86]
G:\TezLaxmi\education\razor_pay\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:19: error: constructor RazorpayFlutterPlugin in class RazorpayFlutterPlugin cannot be applied to given types;
    flutterEngine.getPlugins().add(new com.razorpay.razorpay_flutter.RazorpayFlutterPlugin());
                                   ^
  required: Registrar
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by parvbhullar** [comment]
I'm facing the same issue. 
razorpay_flutter: 1.2.0

**Comment by parvbhullar** [comment]
They have an issue in new update 1.2.0
reverting back to 1.1.4 in pubspac.yaml will solve the problem
Steps
- Remove the flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.0
- change razorpay version to `razorpay_flutter: 1.1.4`
- run 
`
$ flutter clean
$ flutter pub get
$ flutter build apk
`
It solved the above-mentioned issue.

**Comment by sumedht** [comment]
@shailendra-rajpoot @parvbhullar We have updated SDK to version 1.2.1 which supports Flutter's 1.12 version changes. Please updated to latest version of SDK to fix this.
