### ISSUE TITLE
Currency not support 

### ISSUE THREAD

**Issue by suthishan** [razorpay/razorpay-flutter#88]
var options = {
      'key': ConstantValues.getGatewayTestKey(),,
      'amount': selectedPlan['sub_amount'],
      "currency": 'USD',
      'name': 'Pankaj Method',
      'description': 'Meditation App',
      'prefill': {'contact': '', 'email': ''},
      'external': {
        'wallets': ['paytm']
      }

 Invalid amount (should be passed in integer cent. Minimum value is 50 cent, i.e. $ 0.50)

it shows this error invalid amount
I have enabled International Payment also

![Screenshot (1)](https://user-images.githubusercontent.com/32566422/86121968-930b4f80-baf4-11ea-949b-474fe971804c.png)

**Comment by gourabghosh1** [comment]
@suthishan Can you please provide your MID ?

**Comment by suthishan** [comment]
MID - A5LDbbBj9JJXHH

**Comment by gourabghosh1** [comment]
@suthishan it seems like working fine , try with below -
  amount: 50,
currency: 'USD',

<img width="398" alt="Screenshot 2020-07-01 at 3 57 01 PM" src="https://user-images.githubusercontent.com/67676136/86234025-f5775500-bbb3-11ea-9c36-3bd5b510431f.png">

**Comment by suthishan** [comment]
ya thanks its working i have added amount as a invalid format
