### ISSUE TITLE
RazorPay PayPal Support

### ISSUE THREAD

**Issue by rdcoder33** [razorpay/razorpay-flutter#89]
RazorPay Provides Support for PayPal. But I can't find a way to use PayPal in this plugin, are you guys considering to add PayPal support to this plugin as well? Should I wait for this or move on? Please clarify.

**Comment by sumedht** [comment]
@razorpay/techpgintegrations

**Comment by vishal-android-freak** [comment]
This library doesn't support custom SDK integration. Watch for this space as we are a separate flutter plugin for razorpay with standard and custom checkout

**Comment by sumedht** [comment]
Closing this issue due to no further communications. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
