### ISSUE TITLE
cancel or continue payment dialog even after completion of payment transaction.

### ISSUE THREAD

**Issue by EffyCoder** [razorpay/razorpay-flutter#90]
## Description
I have integrated this plugin in our app. The payment is completed with our callback url being called and response returned with webpage. But after that, it should hand over the control to the back by calling event of payment being successful or failed one. This doesn't happen. Instead as nothing happens after waiting for some time user clicks back button and it shows a dialog 

"Do you want to cancel the ongoing payment? cancel or continue.". If pressed continue, nothing happens and if pressed cancel payment cancelled error event emitted.

## Flutter Version :
Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (3 weeks ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

## Android Studio Version :
Android Studio 4.0

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Enter amount to recharge
2.Order Id requested
3.Payment method selected from presented options
4. after some delay payment is accepted and call back url gets called
5. Signature is verified and Payment gets captured at the backend
6. Payment response is returned on a webpage which is shown in the same webview
7.After all this done, the razorpay plugin should emit event whether payment successful or failed one. But it doesn't happen.

## Expected Results
The razorpay plugin should emit event whether payment successful or failed one after the completion of transaction.

**Comment by sumedht** [comment]
@ChintanAcharya ^

**Comment by EffyCoder** [comment]
@ChintanAcharya and @sumedht  why this happens any idea?

**Comment by Nautiyalsachin** [comment]
Hey @EffyCoder, have you tried updating our plugin to latest version, this may fix this issue, let me know if this still persists.

**Comment by Abhish-Bhawsar** [comment]
EffyCoder did you get the solution? if yes ,please help us by sharing the solution
