### ISSUE TITLE
Can't build iOS app with razorpay_flutter 1.2.1 and XCode 11.5

### ISSUE THREAD

**Issue by thetpaingsoe** [razorpay/razorpay-flutter#92]
## Description

When i try to run project with razorpay_flutter 1.2.1, This error come out. 
Can't run the app and can't build the ios app.

This is error log.

Xcode build done.                                           35.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Command CompileSwift failed with a nonzero exit code
    /Users/username/Library/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.1/ios/Classes/RazorpayDelegate.swift:4:42: error: 'RazorpayPaymentCompletionProtocolWithData' is unavailable:
    cannot find Swift declaration for this protocol
    public class RazorpayDelegate: NSObject, RazorpayPaymentCompletionProtocolWithData, ExternalWalletSelectionProtocol {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Razorpay.RazorpayPaymentCompletionProtocolWithData:2:17: note: 'RazorpayPaymentCompletionProtocolWithData' has been explicitly marked unavailable here
    public protocol RazorpayPaymentCompletionProtocolWithData {
                    ^
    /Users/username/Library/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.1/ios/Classes/RazorpayDelegate.swift:4:85: error: 'ExternalWalletSelectionProtocol' is unavailable: cannot
    find Swift declaration for this protocol
    public class RazorpayDelegate: NSObject, RazorpayPaymentCompletionProtocolWithData, ExternalWalletSelectionProtocol {
                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Razorpay.ExternalWalletSelectionProtocol:2:17: note: 'ExternalWalletSelectionProtocol' has been explicitly marked unavailable here
    public protocol ExternalWalletSelectionProtocol {
                    ^
    /Users/username/Library/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.1/ios/Classes/RazorpayDelegate.swift:57:24: error: use of unresolved identifier 'RazorpayCheckout'
            let razorpay = RazorpayCheckout.initWithKey(key ?? "", andDelegateWithData: self)
                           ^~~~~~~~~~~~~~~~
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

## Flutter Version :
Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (10 days ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

## Xcode Version :
Version 11.5 (11E608c)

## Cocoapod Version :
cocoapods/1.9.3
- razorpay-pod (1.1.5)
- razorpay_flutter (1.1.4)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. XCode Version 11.5 and Flutter Version 1.17.5
2. Flutter Razor Pay Lib Version 1.2.1
3. Just Run or Build iOS ( flutter build ios)
4. Then error come out.

**Comment by Anmol92verma** [comment]
Same issue with me! Please fix this !

**Comment by Abhi9454** [comment]
Same issue here. Please resolve it ASAP

**Comment by Anmol92verma** [comment]
@Nautiyalsachin 👆  Please update any workaround atleast ?

**Comment by srivastavarnav** [comment]
Any update on this issue? - please help.

**Comment by sparkidea-codecrab** [comment]
+1 same issue

**Comment by Anmol92verma** [comment]
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F2200, locale en-IN)
    • Flutter version 1.17.5 at /Users/anmol/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

**Comment by nimi0112** [comment]
Same here. Facing build issues

**Comment by nimi0112** [comment]
@Nautiyalsachin  @sumedht  @ChintanAcharya  please acknowledge this issue

**Comment by nimi0112** [comment]
I have tried to reach out to them on Twitter. Let's see I get a response there.

https://twitter.com/nimish_nandwana/status/1283284941652934657

**Comment by nimi0112** [comment]
I have raised an support ticket and got this reply:

> Hello Nimish,
>
>Greetings from Razorpay!
>
>Thank you for all the necessary information. We are getting this checked with our development team, we will identify this and >update you further ASAP.
>We do appreciate the patience and support from your end on this.
>
>The ticket reference for your request is #75616.
>
>Here to Help :)
>Regards,
>Soubhagya J

**Comment by sparkidea-codecrab** [comment]
@nomis-rzp Hope so we will have an answer from the support soon!

**Comment by Anmol92verma** [comment]
I found a solution, here's the razorpay pod folder that works for me from my other system, 
Link to Google Drive too.
https://drive.google.com/file/d/1emzrBAYUec3xTcih3bSjwvehKwsufMZ2/view?usp=sharing

[razorpay-pod.zip](https://github.com/razorpay/razorpay-flutter/files/4933018/razorpay-pod.zip)

**Comment by thangvq95** [comment]
thanks @Anmol92verma , i found another solution as well. This issue have already solved in master branch razorpay-pod: https://github.com/razorpay/razorpay-pod.git
Latest commit is: 4159c5044489dd26687f688ddea44e80fb530e52

To solve the issue, under target 'Runner' add
 1. pod 'razorpay-pod', :git => 'https://github.com/razorpay/razorpay-pod.git', :commit => '4159c5044489dd26687f688ddea44e80fb530e52'
2. update SWIFT_VERSION to 5.2
3. flutter clean and remove razorpay-pod in ios/Pods
4. pod install and run

**Comment by thetpaingsoe** [comment]
@thangvq95 Yes, It worked!

**Comment by nimi0112** [comment]
@thetpaingsoe  it was resolved but I don't think you should close this issue, let the team itself fix and close this. It could help many others also.

**Comment by CrashOverride90** [comment]
> thanks @Anmol92verma , i found another solution as well. This issue have already solved in master branch razorpay-pod: https://github.com/razorpay/razorpay-pod.git
> Latest commit is: 4159c5044489dd26687f688ddea44e80fb530e52
> 
> To solve the issue, in Podfile, under target 'Runner' add
> 
> 1. pod 'razorpay-pod', :git => 'https://github.com/razorpay/razorpay-pod.git', :commit => '4159c5044489dd26687f688ddea44e80fb530e52'
> 2. update SWIFT_VERSION to 5.2
> 3. flutter clean and remove razorpay-pod in ios/Pods
> 4. pod install and run

This worked! Thanks

**Comment by don-k-jacob** [comment]
> my

Thanks @Anmol92verma It worked for me

**Comment by amitmaurya0** [comment]
> thanks @Anmol92verma , i found another solution as well. This issue have already solved in master branch razorpay-pod: https://github.com/razorpay/razorpay-pod.git
> Latest commit is: 4159c5044489dd26687f688ddea44e80fb530e52
> 
> To solve the issue, in Podfile, under target 'Runner' add
> 
> 1. pod 'razorpay-pod', :git => 'https://github.com/razorpay/razorpay-pod.git', :commit => '4159c5044489dd26687f688ddea44e80fb530e52'
> 2. update SWIFT_VERSION to 5.2
> 3. flutter clean and remove razorpay-pod in ios/Pods
> 4. pod install and run

can you please post your Podfile here or paste the pod runner add snippet here Please.
TIA.

**Comment by Nautiyalsachin** [comment]
Hey @thetpaingsoe, we have released a new version with the fix, please update your flutter plugin and run pod update, this will fix this issue. Closing this issue now.

**Comment by leorachit** [comment]
Still facing this issue.
