### ISSUE TITLE
Error Launching The Application on Ios Device

### ISSUE THREAD

**Issue by winterprogram** [razorpay/razorpay-flutter#94]
[!] CocoaPods could not find compatible versions for pod "razorpay_flutter":
In Podfile:
razorpay_flutter (from .symlinks/plugins/razorpay_flutter/ios)

Specs satisfying the razorpay_flutter (from .symlinks/plugins/razorpay_flutter/ios) dependency were found, but they required a higher minimum deployment target.

**Comment by sparkidea-codecrab** [comment]
This is due to your minimum deployment target being less than iOS 10.0. To change this, open ios/Podfile in your project and add/uncomment this line at the top:

# platform :ios, '9.0'
and change it to

platform :ios, '10.0'
and run pod install again in the ios directory.

**Comment by Nautiyalsachin** [comment]
Hi @winterprogram, as we have mentioned on our readme about the minimum platform support please add the mentioned changes and let me know if it works for you. Closing this issue for now. Feel free to re-open it.
